INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  3%|▎         | 1/30 [00:00<00:28,  1.02it/s] 10%|█         | 3/30 [00:01<00:19,  1.40it/s] 13%|█▎        | 4/30 [00:01<00:18,  1.39it/s] 20%|██        | 6/30 [00:03<00:17,  1.35it/s] 23%|██▎       | 7/30 [00:04<00:21,  1.05it/s] 27%|██▋       | 8/30 [00:05<00:16,  1.30it/s] 30%|███       | 9/30 [00:06<00:18,  1.15it/s] 33%|███▎      | 10/30 [00:08<00:25,  1.26s/it] 37%|███▋      | 11/30 [00:08<00:17,  1.06it/s] 43%|████▎     | 13/30 [00:08<00:11,  1.44it/s] 47%|████▋     | 14/30 [00:09<00:09,  1.71it/s] 50%|█████     | 15/30 [00:09<00:07,  1.92it/s] 53%|█████▎    | 16/30 [00:09<00:05,  2.46it/s] 57%|█████▋    | 17/30 [00:10<00:05,  2.43it/s] 60%|██████    | 18/30 [00:10<00:05,  2.22it/s] 63%|██████▎   | 19/30 [00:10<00:03,  2.76it/s] 67%|██████▋   | 20/30 [00:11<00:02,  3.43it/s] 70%|███████   | 21/30 [00:11<00:02,  4.26it/s] 73%|███████▎  | 22/30 [00:11<00:01,  4.30it/s] 77%|███████▋  | 23/30 [00:11<00:01,  4.81it/s] 83%|████████▎ | 25/30 [00:11<00:00,  6.04it/s] 87%|████████▋ | 26/30 [00:11<00:00,  6.63it/s] 90%|█████████ | 27/30 [00:12<00:00,  5.19it/s] 97%|█████████▋| 29/30 [00:12<00:00,  6.47it/s]100%|██████████| 30/30 [00:12<00:00,  3.06it/s]
  0%|          | 0/223 [00:00<?, ?it/s]INFO:__main__:Requesting https://www.nytimes.com/2019/03/04/health/aids-cure-london-patient.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2019/03/04/health/aids-cure-london-patient.html
  0%|          | 1/223 [00:00<00:54,  4.04it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=U219eUIZ7Qo
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=U219eUIZ7Qo
  1%|          | 2/223 [00:01<01:35,  2.32it/s]INFO:__main__:Requesting http://www.unaids.org/en/resources/presscentre/pressreleaseandstatementarchive/2017/november/20171121_righttohealth_report
INFO:__main__:Getting metadata for http://www.unaids.org/en/resources/presscentre/pressreleaseandstatementarchive/2017/november/20171121_righttohealth_report
  1%|▏         | 3/223 [00:02<02:05,  1.75it/s]INFO:__main__:Requesting https://jamanetwork.com/journals/jama/article-abstract/2720997
INFO:__main__:Getting metadata for https://jamanetwork.com/journals/jama/article-abstract/2720997
ERROR:__main__:Could not get metadata for https://jamanetwork.com/journals/jama/article-abstract/2720997
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
  2%|▏         | 4/223 [00:03<03:37,  1.01it/s]INFO:__main__:Requesting https://www.healthline.com/health/hiv-aids/undetectable-viral-load-transmission-risk
INFO:__main__:Getting metadata for https://www.healthline.com/health/hiv-aids/undetectable-viral-load-transmission-risk
  2%|▏         | 5/223 [00:04<02:53,  1.26it/s]INFO:__main__:Requesting https://www.bbc.com/news/health-43435868
INFO:__main__:Getting metadata for https://www.bbc.com/news/health-43435868
  3%|▎         | 6/223 [00:05<03:32,  1.02it/s]INFO:__main__:Requesting https://bnf.nice.org.uk/medicinal-forms/rituximab.html
INFO:__main__:Getting metadata for https://www.nice.org.uk/bnf-bnfc-uk-only
  3%|▎         | 7/223 [00:07<04:01,  1.12s/it]INFO:__main__:Requesting http://www.usccb.org/issues-and-action/human-life-and-dignity/stem-cell-research/index.cfm
INFO:__main__:Getting metadata for http://www.usccb.org/issues-and-action/human-life-and-dignity/stem-cell-research/index.cfm
  4%|▎         | 8/223 [00:08<03:43,  1.04s/it]INFO:__main__:Requesting https://www.scientificamerican.com/article/human-stem-cells-no-embryo/
INFO:__main__:Getting metadata for https://www.scientificamerican.com/article/human-stem-cells-no-embryo/
  4%|▍         | 9/223 [00:09<04:15,  1.20s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Timothy_Ray_Brown
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Timothy_Ray_Brown
  4%|▍         | 10/223 [00:10<03:49,  1.08s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Graft-versus-host_disease#HIV_elimination
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Graft-versus-host_disease#HIV_elimination
  5%|▍         | 11/223 [00:11<03:54,  1.11s/it]INFO:__main__:Requesting https://www.newscientist.com/article/mg23431244-400-immune-war-with-donor-cells-after-transplant-may-wipe-out-hiv/
INFO:__main__:Getting metadata for https://www.newscientist.com/article/mg23431244-400-immune-war-with-donor-cells-after-transplant-may-wipe-out-hiv/
  5%|▌         | 12/223 [00:13<04:55,  1.40s/it]INFO:__main__:Requesting http://www.immunityproject.org
INFO:__main__:Getting metadata for http://www.immunityproject.org
  6%|▌         | 13/223 [00:14<03:49,  1.09s/it]INFO:__main__:Requesting https://ifixit.org/blog/13979/apples-2018-macbook-pros-attempt-to-solve-flexgate-without-admitting-it-exists/
INFO:__main__:Getting metadata for https://ifixit.org/blog/13979/apples-2018-macbook-pros-attempt-to-solve-flexgate-without-admitting-it-exists/
  6%|▋         | 14/223 [00:14<03:00,  1.16it/s]INFO:__main__:Requesting https://www.reuters.com/article/us-spotify-india-idUSKCN1QL22C
INFO:__main__:Getting metadata for https://www.reuters.com/article/us-spotify-india-idUSKCN1QL22C
  7%|▋         | 15/223 [00:14<02:18,  1.50it/s]INFO:__main__:Requesting https://www.statista.com/statistics/274772/forecast-of-mobile-phone-users-in-canada/
INFO:__main__:Getting metadata for https://www.statista.com/statistics/274772/forecast-of-mobile-phone-users-in-canada/
  7%|▋         | 16/223 [00:15<02:20,  1.47it/s]INFO:__main__:Requesting http://www.bbc.com/future/story/20190218-the-lifespans-of-ancient-civilisations-compared
INFO:__main__:Getting metadata for http://www.bbc.com/future/story/20190218-the-lifespans-of-ancient-civilisations-compared
  8%|▊         | 17/223 [00:15<02:11,  1.56it/s]INFO:__main__:Requesting https://www.philanthropy.com/article/America-s-Generosity-Divide/156175
  8%|▊         | 18/223 [00:15<01:42,  1.99it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Third_Rome
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Third_Rome
  9%|▊         | 19/223 [00:17<02:19,  1.46it/s]INFO:__main__:Requesting https://www.amazon.com/Why-Nations-Fail-Origins-Prosperity/dp/0307719227
INFO:__main__:Getting metadata for https://www.amazon.com/Why-Nations-Fail-Origins-Prosperity/dp/0307719227
  9%|▉         | 20/223 [00:24<09:05,  2.69s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Kingdom_of_Israel_(united_monarchy)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Kingdom_of_Israel_(united_monarchy)
  9%|▉         | 21/223 [00:25<07:27,  2.21s/it]INFO:__main__:Requesting http://www.bbc.com/future/story/20190218-are-we-on-the-road-to-civilisation-collapse
INFO:__main__:Getting metadata for http://www.bbc.com/future/story/20190218-are-we-on-the-road-to-civilisation-collapse
 10%|▉         | 22/223 [00:27<07:13,  2.15s/it]INFO:__main__:Requesting https://github.com/BayesWitnesses/m2cgen
INFO:__main__:Getting metadata for https://github.com/BayesWitnesses/m2cgen
 10%|█         | 23/223 [00:28<05:57,  1.79s/it]INFO:__main__:Requesting https://www.tensorflow.org/xla/tfcompile
INFO:__main__:Getting metadata for https://www.tensorflow.org/xla/tfcompile
 11%|█         | 24/223 [00:28<04:26,  1.34s/it]INFO:__main__:Requesting https://github.com/nok/sklearn-porter
INFO:__main__:Getting metadata for https://github.com/nok/sklearn-porter
 11%|█         | 25/223 [00:29<04:04,  1.24s/it]INFO:__main__:Requesting https://github.com/konstantint/SKompiler
INFO:__main__:Getting metadata for https://github.com/konstantint/SKompiler
 12%|█▏        | 26/223 [00:30<03:52,  1.18s/it]INFO:__main__:Requesting https://github.com/jonnor/emlearn
INFO:__main__:Getting metadata for https://github.com/jonnor/emlearn
 12%|█▏        | 27/223 [00:31<03:38,  1.11s/it]INFO:__main__:Requesting http://www.ianbicking.org/blog/2019/03/firefox-experiments-i-would-have-liked.html
INFO:__main__:Getting metadata for http://www.ianbicking.org/blog/2019/03/firefox-experiments-i-would-have-liked.html
 13%|█▎        | 28/223 [00:32<03:26,  1.06s/it]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/snoozetabs/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/snoozetabs/
 13%|█▎        | 29/223 [00:33<03:26,  1.06s/it]INFO:__main__:Requesting https://firefoxur.github.io/
INFO:__main__:Getting metadata for https://firefoxur.github.io
 13%|█▎        | 30/223 [00:34<03:10,  1.01it/s]INFO:__main__:Requesting https://chrome.google.com/webstore/detail/openlist/nkpjembldfckmdchbdiclhfedcngbgnl?hl=en
INFO:__main__:Getting metadata for https://chrome.google.com/webstore/detail/openlist/nkpjembldfckmdchbdiclhfedcngbgnl?hl=en
 14%|█▍        | 31/223 [00:34<02:22,  1.35it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/
 14%|█▍        | 32/223 [00:35<02:37,  1.21it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/
 15%|█▍        | 33/223 [00:36<02:51,  1.10it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/panorama-tab-groups/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/panorama-tab-groups/
 15%|█▌        | 34/223 [00:37<02:56,  1.07it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/tabist/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/tabist/
 16%|█▌        | 35/223 [00:38<03:00,  1.04it/s]INFO:__main__:Requesting https://chrome.google.com/webstore/detail/tabist/hdjegjggiogfkaldbfphfdkpggjemaha
INFO:__main__:Getting metadata for https://chrome.google.com/webstore/detail/tabist/hdjegjggiogfkaldbfphfdkpggjemaha
 16%|█▌        | 36/223 [00:39<02:14,  1.39it/s]INFO:__main__:Requesting https://github.com/fiveNinePlusR/tabist
INFO:__main__:Getting metadata for https://github.com/fiveNinePlusR/tabist
 17%|█▋        | 37/223 [00:40<02:43,  1.14it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/JScript
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/JScript
 17%|█▋        | 38/223 [00:41<03:07,  1.01s/it]INFO:__main__:Requesting https://support.apple.com/en-us/HT209101
INFO:__main__:Getting metadata for https://support.apple.com/en-us/HT209101
 17%|█▋        | 39/223 [00:41<02:28,  1.24it/s]INFO:__main__:Requesting https://getpocket.com/
INFO:__main__:Getting metadata for https://getpocket.com
 18%|█▊        | 40/223 [00:43<02:41,  1.13it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/onetab/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/onetab/
 18%|█▊        | 41/223 [00:44<02:48,  1.08it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/better-onetab/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/better-onetab/
 19%|█▉        | 42/223 [00:45<02:52,  1.05it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/
 19%|█▉        | 43/223 [00:46<02:54,  1.03it/s]INFO:__main__:Requesting https://www.qutebrowser.org/
INFO:__main__:Getting metadata for https://www.qutebrowser.org
 20%|█▉        | 44/223 [00:49<04:40,  1.57s/it]INFO:__main__:Requesting https://github.com/cmcaine/tridactyl
INFO:__main__:Getting metadata for https://github.com/tridactyl/tridactyl
 20%|██        | 45/223 [00:50<04:08,  1.40s/it]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/
 21%|██        | 46/223 [00:51<03:50,  1.30s/it]INFO:__main__:Requesting https://webextensions-experiments.readthedocs.io/en/latest/index.html
INFO:__main__:Getting metadata for https://webextensions-experiments.readthedocs.io/en/latest/index.html
 21%|██        | 47/223 [00:52<03:36,  1.23s/it]INFO:__main__:Requesting https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/basics.html
INFO:__main__:Getting metadata for https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/basics.html
 22%|██▏       | 48/223 [00:53<03:25,  1.18s/it]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=1397874
 22%|██▏       | 49/223 [00:53<02:38,  1.10it/s]INFO:__main__:Requesting https://www.dropbox.com/s/2va0icchtittbnx/shortcuts-experiment.zip?dl=1
INFO:__main__:Getting metadata for https://uc567e4fd9c9f39f4d2a339470ec.dl.dropboxusercontent.com/cd/0/get/AccvJDS9JrJj9evPCQnwU3w9Ck5JomUY9FtAQjNCCvvIzgQNp9ABXVcj9A0qhid2N7IpPiXNPIaENW6NIQQlAd9lhWwbR7qQ2hqj-SjAlO2JDuRqv8UYfh8E0mwS4Nm5BQE/file?dl=1
 22%|██▏       | 50/223 [00:57<04:51,  1.69s/it]INFO:__main__:Requesting https://support.mozilla.org/en-US/kb/awesome-bar-search-firefox-bookmarks-history-tabs#w_changing-results-on-the-fly_2
INFO:__main__:Getting metadata for https://support.mozilla.org/en-US/kb/awesome-bar-search-firefox-bookmarks-history-tabs#w_changing-results-on-the-fly_2
 23%|██▎       | 51/223 [00:59<05:08,  1.79s/it]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=1303384
 23%|██▎       | 52/223 [00:59<03:46,  1.33s/it]INFO:__main__:Requesting http://www.ianbicking.org/blog/2018/02/web-small-composable-tools.html
INFO:__main__:Getting metadata for http://www.ianbicking.org/blog/2018/02/web-small-composable-tools.html
 24%|██▍       | 53/223 [00:59<02:58,  1.05s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/MH_Message_Handling_System
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/MH_Message_Handling_System
 24%|██▍       | 54/223 [01:00<02:38,  1.07it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Acme_(text_editor)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Acme_(text_editor)
 25%|██▍       | 55/223 [01:01<02:24,  1.16it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/saka/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/saka/
 25%|██▌       | 56/223 [01:02<02:31,  1.10it/s]INFO:__main__:Requesting https://addons.mozilla.org/de/firefox/addon/better-image-viewer/
INFO:__main__:Getting metadata for https://addons.mozilla.org/de/firefox/addon/better-image-viewer/
 26%|██▌       | 57/223 [01:03<02:35,  1.07it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
 26%|██▌       | 58/223 [01:04<02:38,  1.04it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/
 26%|██▋       | 59/223 [01:05<02:48,  1.03s/it]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/first-party-isolation/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/first-party-isolation/
 27%|██▋       | 60/223 [01:06<02:48,  1.03s/it]INFO:__main__:Requesting https://www.ghacks.net/2017/11/22/how-to-enable-first-party-isolation-in-firefox/
INFO:__main__:Getting metadata for https://www.ghacks.net/2017/11/22/how-to-enable-first-party-isolation-in-firefox/
 27%|██▋       | 61/223 [01:07<02:39,  1.02it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/tip-tab/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/tip-tab/
 28%|██▊       | 62/223 [01:08<02:41,  1.00s/it]INFO:__main__:Requesting https://ipfs.io/#why
INFO:__main__:Getting metadata for https://ipfs.io/#why
 28%|██▊       | 63/223 [01:08<02:08,  1.25it/s]INFO:__main__:Requesting https://filecoin.io/
INFO:__main__:Getting metadata for https://filecoin.io
 29%|██▊       | 64/223 [01:09<02:08,  1.24it/s]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=866522
 29%|██▉       | 65/223 [01:09<01:40,  1.57it/s]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=1478037
 30%|██▉       | 66/223 [01:09<01:21,  1.94it/s]INFO:__main__:Requesting https://textslashplain.com/2017/01/14/the-line-of-death/
ERROR:__main__:Could not reach https://textslashplain.com/2017/01/14/the-line-of-death/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 30%|███       | 67/223 [01:10<01:04,  2.42it/s]INFO:__main__:Requesting https://www.narro.co
INFO:__main__:Getting metadata for https://www.narro.co
 30%|███       | 68/223 [01:10<01:05,  2.36it/s]INFO:__main__:Requesting http://acrowdedspace.com/post/166470695392/the-rebundling-of-craigslist
INFO:__main__:Getting metadata for http://acrowdedspace.com/post/166470695392/the-rebundling-of-craigslist
 31%|███       | 69/223 [01:10<01:07,  2.27it/s]INFO:__main__:Requesting https://www.theverge.com/2017/12/16/16784628/mozilla-mr-robot-arg-plugin-firefox-looking-glass
INFO:__main__:Getting metadata for https://www.theverge.com/2017/12/16/16784628/mozilla-mr-robot-arg-plugin-firefox-looking-glass
 31%|███▏      | 70/223 [01:11<01:09,  2.19it/s]INFO:__main__:Requesting https://distill.io/
INFO:__main__:Getting metadata for https://distill.io
 32%|███▏      | 71/223 [01:11<00:59,  2.54it/s]INFO:__main__:Requesting https://addons.mozilla.org/firefox/addon/reader-view/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/reader-view/
 32%|███▏      | 72/223 [01:12<01:29,  1.68it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/automatic-reader-view/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/automatic-reader-view/
 33%|███▎      | 73/223 [01:13<01:48,  1.38it/s]INFO:__main__:Requesting https://wiki.mozilla.org/Labs/Ubiquity
INFO:__main__:Getting metadata for https://wiki.mozilla.org/Labs/Ubiquity
 33%|███▎      | 74/223 [01:15<02:14,  1.11it/s]INFO:__main__:Requesting https://imgur.com/O8rN9fK
INFO:__main__:Getting metadata for https://imgur.com/O8rN9fK
 34%|███▎      | 75/223 [01:15<01:51,  1.32it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/tile-tabs-we/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/tile-tabs-we/
 34%|███▍      | 76/223 [01:16<02:04,  1.18it/s]INFO:__main__:Requesting https://theintercept.com/2019/03/04/google-ongoing-project-dragonfly/
INFO:__main__:Getting metadata for https://theintercept.com/2019/03/04/google-ongoing-project-dragonfly/
 35%|███▍      | 77/223 [01:16<01:33,  1.55it/s]INFO:__main__:Requesting https://www.reuters.com/investigates/special-report/muslims-camps-china/
INFO:__main__:Getting metadata for https://www.reuters.com/investigates/special-report/muslims-camps-china/
 35%|███▍      | 78/223 [01:17<01:17,  1.87it/s]INFO:__main__:Requesting https://pastebin.com/gPgy648A
INFO:__main__:Getting metadata for https://pastebin.com/gPgy648A
 35%|███▌      | 79/223 [01:17<01:04,  2.22it/s]INFO:__main__:Requesting https://twitter.com/existentialcoms/status/1051547413083652096
INFO:__main__:Getting metadata for https://twitter.com/existentialcoms/status/1051547413083652096
 36%|███▌      | 80/223 [01:18<01:29,  1.60it/s]INFO:__main__:Requesting https://newsyndicalist.org/2017/09/30/union-cooperative-strategy-david-oconnell/
ERROR:__main__:Could not reach https://newsyndicalist.org/2017/09/30/union-cooperative-strategy-david-oconnell/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 36%|███▋      | 81/223 [01:18<01:08,  2.08it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Google_China#Operation_Aurora_and_2010_withdrawal
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Google_China#Operation_Aurora_and_2010_withdrawal
 37%|███▋      | 82/223 [01:19<01:41,  1.38it/s]INFO:__main__:Requesting https://nypost.com/2017/11/21/apple-has-been-using-teen-labor-to-assemble-the-iphone-x/
ERROR:__main__:Could not reach https://nypost.com/2017/11/21/apple-has-been-using-teen-labor-to-assemble-the-iphone-x/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 37%|███▋      | 83/223 [01:19<01:16,  1.83it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Censorship_by_Google
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Censorship_by_Google
 38%|███▊      | 84/223 [01:21<01:59,  1.16it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Death_of_Wei_Zexi
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Death_of_Wei_Zexi
 38%|███▊      | 85/223 [01:22<01:51,  1.24it/s]INFO:__main__:Requesting https://www.ft.com/content/9be0b974-10e9-11e6-bb40-c30e3bfcf63b
INFO:__main__:Getting metadata for https://www.ft.com/content/9be0b974-10e9-11e6-bb40-c30e3bfcf63b
 39%|███▊      | 86/223 [01:24<02:35,  1.14s/it]INFO:__main__:Requesting https://www.washingtonpost.com/technology/2018/10/16/google-really-is-trying-build-censored-chinese-search-engine-its-ceo-confirms/?noredirect=on&utm_term=.cab0c09d7760
ERROR:__main__:Could not reach https://www.washingtonpost.com/technology/2018/10/16/google-really-is-trying-build-censored-chinese-search-engine-its-ceo-confirms/?noredirect=on&utm_term=.cab0c09d7760
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)
 39%|███▉      | 87/223 [01:30<05:55,  2.62s/it]INFO:__main__:Requesting http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/
INFO:__main__:Getting metadata for http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/
 39%|███▉      | 88/223 [01:30<04:18,  1.91s/it]INFO:__main__:Requesting http://patorjk.com/blog/2013/03/01/facebook-user-identification-bug/
INFO:__main__:Requesting http://www.tomanthony.co.uk/blog/google-xml-sitemap-auth-bypass-black-hat-seo-bug-bounty/
INFO:__main__:Getting metadata for http://www.tomanthony.co.uk/blog/google-xml-sitemap-auth-bypass-black-hat-seo-bug-bounty/
 40%|████      | 90/223 [01:31<03:16,  1.48s/it]INFO:__main__:Requesting https://www.google.com/about/appsecurity/reward-program/index.html
INFO:__main__:Getting metadata for https://www.google.com/about/appsecurity/reward-program/index.html
 41%|████      | 91/223 [01:31<02:25,  1.10s/it]INFO:__main__:Requesting http://blog.quaji.com/2009/07/facebook-personal-info-leak.html
INFO:__main__:Getting metadata for http://blog.quaji.com/2009/07/facebook-personal-info-leak.html
 41%|████▏     | 92/223 [01:32<02:04,  1.05it/s]INFO:__main__:Requesting https://web.archive.org/web/20190305014509/http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/
ERROR:__main__:Could not reach https://web.archive.org/web/20190305014509/http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6678e65b00>, 'Connection to web.archive.org timed out. (connect timeout=6)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190305014509/http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6678e65b00>, 'Connection to web.archive.org timed out. (connect timeout=6)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190305014509/http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6678e65b00>, 'Connection to web.archive.org timed out. (connect timeout=6)'))
 42%|████▏     | 93/223 [01:38<05:21,  2.47s/it]INFO:__main__:Requesting https://blog.cloudflare.com/building-fast-interpreters-in-rust/
INFO:__main__:Getting metadata for https://blog.cloudflare.com/building-fast-interpreters-in-rust/
 42%|████▏     | 94/223 [01:38<03:59,  1.86s/it]INFO:__main__:Requesting https://blog.cloudflare.com/how-we-made-firewall-rules/
INFO:__main__:Getting metadata for https://blog.cloudflare.com/how-we-made-firewall-rules/
 43%|████▎     | 95/223 [01:39<03:16,  1.54s/it]INFO:__main__:Requesting https://www.usenix.org/publications/login/fall2017
INFO:__main__:Getting metadata for https://www.usenix.org/publications/login/fall2017
 43%|████▎     | 96/223 [01:40<02:41,  1.27s/it]INFO:__main__:Requesting https://www.reddit.com/r/rust/comments/awx9cy/github_kyrenluster_an_experimental_lua_vm/
INFO:__main__:Getting metadata for https://www.reddit.com/r/rust/comments/awx9cy/github_kyrenluster_an_experimental_lua_vm/
 43%|████▎     | 97/223 [01:41<02:42,  1.29s/it]INFO:__main__:Requesting https://youtu.be/Hqw57GJSrac?t=341
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=Hqw57GJSrac&feature=youtu.be&t=341
 44%|████▍     | 98/223 [01:42<02:22,  1.14s/it]INFO:__main__:Requesting https://kseo.github.io/posts/2017-01-09-continuation-passing-style-interpreter.html
INFO:__main__:Getting metadata for https://kseo.github.io/posts/2017-01-09-continuation-passing-style-interpreter.html
 44%|████▍     | 99/223 [01:42<01:55,  1.07it/s]INFO:__main__:Requesting https://inko-lang.org/
INFO:__main__:Getting metadata for https://inko-lang.org
 45%|████▍     | 100/223 [01:43<01:45,  1.16it/s]INFO:__main__:Requesting https://gitlab.com/inko-lang/inko/blob/master/vm/src/vm/machine.rs#L294
INFO:__main__:Getting metadata for https://gitlab.com/inko-lang/inko/blob/master/vm/src/vm/machine.rs#L294
 45%|████▌     | 101/223 [01:44<01:43,  1.18it/s]INFO:__main__:Requesting https://www.slideshare.net/RReverser/building-fast-interpreters-in-rust
INFO:__main__:Getting metadata for https://www.slideshare.net/RReverser/building-fast-interpreters-in-rust
 46%|████▌     | 102/223 [01:45<02:03,  1.02s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Threaded_code#Subroutine_threading
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Threaded_code#Subroutine_threading
 46%|████▌     | 103/223 [01:46<02:05,  1.05s/it]INFO:__main__:Requesting https://www.colm.net/open-source/ragel/
INFO:__main__:Getting metadata for https://www.colm.net/open-source/ragel/
 47%|████▋     | 104/223 [01:47<01:56,  1.02it/s]INFO:__main__:Requesting https://hal.inria.fr/hal-01100647/document
INFO:__main__:Getting metadata for https://hal.inria.fr/hal-01100647/document
 47%|████▋     | 105/223 [02:05<11:48,  6.00s/it]INFO:__main__:Requesting https://github.com/eclipse/openj9/blob/01be53f659a8190959c1641eac20b0488739e94c/runtime/vm/BytecodeInterpreter.hpp#L4872
INFO:__main__:Getting metadata for https://github.com/eclipse/openj9/blob/01be53f659a8190959c1641eac20b0488739e94c/runtime/vm/BytecodeInterpreter.hpp#L4872
 48%|████▊     | 106/223 [02:09<10:39,  5.46s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Threaded_code
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Threaded_code
 48%|████▊     | 107/223 [02:10<08:06,  4.19s/it]INFO:__main__:Requesting https://github.com/cloudflare/wirefilter
INFO:__main__:Getting metadata for https://github.com/cloudflare/wirefilter
 48%|████▊     | 108/223 [02:11<06:10,  3.23s/it]INFO:__main__:Requesting http://smallcultfollowing.com/babysteps/blog/2018/04/24/rust-pattern-precise-closure-capture-clauses/#a-more-general-pattern
INFO:__main__:Getting metadata for http://smallcultfollowing.com/babysteps/blog/2018/04/24/rust-pattern-precise-closure-capture-clauses/#a-more-general-pattern
 49%|████▉     | 109/223 [02:12<04:43,  2.49s/it]INFO:__main__:Requesting https://blog.cloudflare.com/incident-report-on-memory-leak-caused-by-cloudflare-parser-bug/
INFO:__main__:Getting metadata for https://blog.cloudflare.com/incident-report-on-memory-leak-caused-by-cloudflare-parser-bug/
 49%|████▉     | 110/223 [02:12<03:34,  1.89s/it]INFO:__main__:Requesting https://godbolt.org/z/UE-Mb0
INFO:__main__:Getting metadata for https://godbolt.org/z/UE-Mb0
 50%|████▉     | 111/223 [02:13<02:59,  1.61s/it]INFO:__main__:Requesting https://www.anandtech.com/show/14048/usb4-specification-40-gbps-type-c-tb3
INFO:__main__:Getting metadata for https://www.anandtech.com/show/14048/usb4-specification-40-gbps-type-c-tb3
 50%|█████     | 112/223 [02:14<02:22,  1.29s/it]INFO:__main__:Requesting https://plus.google.com/+BensonLeung/posts/jGP5249NppF
INFO:__main__:Getting metadata for https://plus.google.com/+BensonLeung/posts/jGP5249NppF
 51%|█████     | 113/223 [02:15<02:08,  1.16s/it]INFO:__main__:Requesting https://www.reddit.com/r/Nexus6P/comments/3robzo/google_spreadsheet_for_usbc_cables_with_benson/
INFO:__main__:Getting metadata for https://www.reddit.com/r/Nexus6P/comments/3robzo/google_spreadsheet_for_usbc_cables_with_benson/
 51%|█████     | 114/223 [02:16<02:16,  1.25s/it]INFO:__main__:Requesting https://arstechnica.com/gadgets/2019/02/usb-3-2-is-going-to-make-the-current-usb-branding-even-worse/
INFO:__main__:Getting metadata for https://arstechnica.com/gadgets/2019/02/usb-3-2-is-going-to-make-the-current-usb-branding-even-worse/
 52%|█████▏    | 115/223 [02:17<01:45,  1.02it/s]INFO:__main__:Requesting https://arstechnica.com/gadgets/2019/03/thunderbolt-3-becomes-usb4-as-intels-interconnect-goes-royalty-free
INFO:__main__:Getting metadata for https://arstechnica.com/gadgets/2019/03/thunderbolt-3-becomes-usb4-as-intels-interconnect-goes-royalty-free/
 52%|█████▏    | 116/223 [02:17<01:27,  1.22it/s]INFO:__main__:Requesting https://www.apple.com/shop/product/MD861LL/A/apple-thunderbolt-cable-20-m
INFO:__main__:Getting metadata for https://www.apple.com/shop/product/MD861LL/A/apple-thunderbolt-cable-20-m
 52%|█████▏    | 117/223 [02:18<01:31,  1.16it/s]INFO:__main__:Requesting https://www.apple.com/uk/shop/product/MLL82ZM/A/usb-c-charge-cable-2m
INFO:__main__:Getting metadata for https://www.apple.com/uk/shop/product/MLL82ZM/A/usb-c-charge-cable-2m
 53%|█████▎    | 118/223 [02:19<01:25,  1.23it/s]INFO:__main__:Requesting https://www.apple.com/shop/product/MQ4H2AM/A/thunderbolt-3-usb%E2%80%91c-cable-08-m?fnode=8b
INFO:__main__:Getting metadata for https://www.apple.com/shop/product/MQ4H2AM/A/thunderbolt-3-usb%E2%80%91c-cable-08-m?fnode=8b
 53%|█████▎    | 119/223 [02:19<01:16,  1.35it/s]INFO:__main__:Requesting https://www.cnet.com/how-to/usb-type-c-thunderbolt-3-one-cable-to-connect-them-all/
INFO:__main__:Getting metadata for https://www.cnet.com/how-to/usb-type-c-thunderbolt-3-one-cable-to-connect-them-all/
 54%|█████▍    | 120/223 [02:20<01:05,  1.56it/s]INFO:__main__:Requesting https://external-preview.redd.it/yQJH1H8y7ypKanxgZKwIaJom5h4N9cu4WWX5D7wboNU.jpg?auto=webp&s=07f7d5c9ba0721e9ddf2c1e9299a3e00f21fc1d0
INFO:__main__:Getting metadata for https://external-preview.redd.it/yQJH1H8y7ypKanxgZKwIaJom5h4N9cu4WWX5D7wboNU.jpg?auto=webp&s=07f7d5c9ba0721e9ddf2c1e9299a3e00f21fc1d0
 54%|█████▍    | 121/223 [02:23<02:18,  1.36s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/USB_3.0#Pinouts
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/USB_3.0#Pinouts
 55%|█████▍    | 122/223 [02:24<02:23,  1.42s/it]INFO:__main__:Requesting https://www.chipestimate.com/Type-C-USB31-PHY-Challenges-in-Analog-and-Digital-Design/SilabTech/Technical-Article/2016/02/23
INFO:__main__:Requesting https://blog.startech.com/post/thunderbolt-3-the-basics/
INFO:__main__:Getting metadata for https://blog.startech.com/post/thunderbolt-3-the-basics/
 56%|█████▌    | 124/223 [02:25<01:47,  1.08s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/DMA_attack
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/DMA_attack
 56%|█████▌    | 125/223 [02:26<01:37,  1.01it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=uOlQbP63lDQ
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=uOlQbP63lDQ
 57%|█████▋    | 126/223 [02:27<01:38,  1.01s/it]INFO:__main__:Requesting https://smile.amazon.com/gp/product/B01H5QF2TK
INFO:__main__:Getting metadata for https://www.amazon.com/gp/product/B01H5QF2TK?pldnSite=1
 57%|█████▋    | 127/223 [02:31<02:59,  1.87s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=ehvz3iN8pp4
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=ehvz3iN8pp4
 57%|█████▋    | 128/223 [02:31<02:31,  1.59s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=VxNBiAV4UnM
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=VxNBiAV4UnM
 58%|█████▊    | 129/223 [02:32<02:12,  1.41s/it]INFO:__main__:Requesting https://superuser.com/questions/1199917/what-is-the-d-shaped-icon-next-to-my-usb-c-port/1200112#1200112
INFO:__main__:Getting metadata for https://superuser.com/questions/1199917/what-is-the-d-shaped-icon-next-to-my-usb-c-port/1200112#1200112
 58%|█████▊    | 130/223 [02:33<01:45,  1.14s/it]INFO:__main__:Requesting https://www.usb.org/usbc
INFO:__main__:Getting metadata for https://www.usb.org/usbc
 59%|█████▊    | 131/223 [02:35<02:09,  1.40s/it]INFO:__main__:Requesting https://twitter.com/whitequark/status/1097777102563074048
INFO:__main__:Getting metadata for https://twitter.com/whitequark/status/1097777102563074048
 59%|█████▉    | 132/223 [02:36<01:53,  1.24s/it]INFO:__main__:Requesting http://time.com/4656550/camping-sleep-insomnia/
INFO:__main__:Getting metadata for http://time.com/4656550/camping-sleep-insomnia/
 60%|█████▉    | 133/223 [02:36<01:22,  1.09it/s]INFO:__main__:Requesting https://thunderbolttechnology.net/
INFO:__main__:Getting metadata for https://thunderbolttechnology.net
 60%|██████    | 134/223 [02:38<01:46,  1.19s/it]INFO:__main__:Requesting http://thunderclap.io/
INFO:__main__:Getting metadata for http://thunderclap.io
 61%|██████    | 135/223 [02:38<01:16,  1.15it/s]INFO:__main__:Requesting https://www.newertech.com/products/viddu2dvia.php
INFO:__main__:Getting metadata for https://www.newertech.com/products/viddu2dvia.php
 61%|██████    | 136/223 [02:39<01:12,  1.20it/s]INFO:__main__:Requesting https://www.hdmi.org/press/press_release.aspx?prid=144
INFO:__main__:Getting metadata for https://www.hdmi.org/press/press_release.aspx?prid=144
 61%|██████▏   | 137/223 [02:40<01:35,  1.11s/it]INFO:__main__:Requesting https://github.com/uBlockOrigin/uAssets/issues/1905
INFO:__main__:Getting metadata for https://github.com/uBlockOrigin/uAssets/issues/1905
 62%|██████▏   | 138/223 [02:44<02:38,  1.86s/it]INFO:__main__:Requesting https://www.adblockradio.con
ERROR:__main__:Could not reach https://www.adblockradio.con
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f66907533c8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.adblockradio.con', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f66907533c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.adblockradio.con', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f66907533c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
 62%|██████▏   | 139/223 [02:44<01:52,  1.34s/it]INFO:__main__:Requesting https://github.com/adblockradio/adblockradio
INFO:__main__:Getting metadata for https://github.com/adblockradio/adblockradio
 63%|██████▎   | 140/223 [02:45<01:49,  1.32s/it]INFO:__main__:Requesting https://wordpress.tv/2017/10/15/james-strang-introduction-to-ad-ops/
ERROR:__main__:Could not reach https://wordpress.tv/2017/10/15/james-strang-introduction-to-ad-ops/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 63%|██████▎   | 141/223 [02:46<01:19,  1.03it/s]INFO:__main__:Requesting http://danluu.com/monorepo/
INFO:__main__:Getting metadata for http://danluu.com/monorepo/
 64%|██████▎   | 142/223 [02:46<01:02,  1.30it/s]INFO:__main__:Requesting https://cacm.acm.org/magazines/2016/7/204032/fulltext
INFO:__main__:Getting metadata for https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext
 64%|██████▍   | 143/223 [02:52<03:12,  2.41s/it]INFO:__main__:Requesting https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/pdf
INFO:__main__:Getting metadata for http://delivery.acm.org/10.1145/2860000/2854146/p78-potvin.pdf?ip=35.184.226.236&id=2854146&acc=OA&key=4D4702B0C3E38B35.4D4702B0C3E38B35.4D4702B0C3E38B35.5945DC2EABF3343C&__acm__=1551769761_c0750dee706a740f505e55c6be22e3cf
 65%|██████▍   | 144/223 [03:52<26:01, 19.76s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=W71BTkUbdqE
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=W71BTkUbdqE
 65%|██████▌   | 145/223 [03:53<18:20, 14.11s/it]INFO:__main__:Requesting https://www.icse2018.org/track/icse-2018-Software-Engineering-in-Practice
INFO:__main__:Getting metadata for https://www.icse2018.org/track/icse-2018-Software-Engineering-in-Practice
 65%|██████▌   | 146/223 [03:55<13:24, 10.45s/it]INFO:__main__:Requesting https://blog.coinbase.com/living-up-to-our-values-and-the-neutrino-acquisition-ba98174cdcf6
INFO:__main__:Getting metadata for https://blog.coinbase.com/living-up-to-our-values-and-the-neutrino-acquisition-ba98174cdcf6?gi=1f17675e2c6e
 66%|██████▌   | 147/223 [03:56<09:37,  7.60s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Hacking_Team
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Hacking_Team
 66%|██████▋   | 148/223 [03:58<07:13,  5.78s/it]INFO:__main__:Requesting https://techcrunch.com/2019/03/04/neutrino-employees-who-once-worked-for-a-controversial-surveillance-tech-company-will-leave-coinbase/
ERROR:__main__:Could not reach https://techcrunch.com/2019/03/04/neutrino-employees-who-once-worked-for-a-controversial-surveillance-tech-company-will-leave-coinbase/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 67%|██████▋   | 149/223 [03:58<05:02,  4.08s/it]INFO:__main__:Requesting https://www.nelp.org/publication/ban-the-box-fair-chance-hiring-state-and-local-guide/
INFO:__main__:Getting metadata for https://www.nelp.org/publication/ban-the-box-fair-chance-hiring-state-and-local-guide/
 67%|██████▋   | 150/223 [03:58<03:40,  3.03s/it]INFO:__main__:Requesting http://iolivia.me/posts/24-hours-of-rust-game-dev/
INFO:__main__:Getting metadata for http://iolivia.me/posts/24-hours-of-rust-game-dev/
 68%|██████▊   | 151/223 [03:59<02:36,  2.17s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=aKLntZcp27M
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=aKLntZcp27M
 68%|██████▊   | 152/223 [04:00<02:07,  1.80s/it]INFO:__main__:Requesting http://www.commitstrip.com/en/2014/11/25/west-side-project-story/
INFO:__main__:Getting metadata for http://www.commitstrip.com/en/2014/11/25/west-side-project-story/
 69%|██████▊   | 153/223 [04:01<01:52,  1.61s/it]INFO:__main__:Requesting https://www.bbc.com/news/business-47301446
INFO:__main__:Getting metadata for https://www.bbc.com/news/business-47301446
 69%|██████▉   | 154/223 [04:01<01:22,  1.19s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Atlassian
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Atlassian
 70%|██████▉   | 155/223 [04:02<01:19,  1.16s/it]INFO:__main__:Requesting https://www.smh.com.au/business/small-business/mike-cannon-brookes-warns-atlassian-may-leave-australia-20180313-p4z44c.html
INFO:__main__:Getting metadata for https://www.smh.com.au/business/small-business/mike-cannon-brookes-warns-atlassian-may-leave-australia-20180313-p4z44c.html
 70%|██████▉   | 156/223 [04:03<01:08,  1.02s/it]INFO:__main__:Requesting https://ai.googleblog.com/2019/03/introducing-gpipe-open-source-library.html
INFO:__main__:Getting metadata for https://ai.googleblog.com/2019/03/introducing-gpipe-open-source-library.html
 70%|███████   | 157/223 [04:03<00:54,  1.21it/s]INFO:__main__:Requesting https://colab.research.google.com/notebooks/tpu.ipynb
INFO:__main__:Getting metadata for https://colab.research.google.com/notebooks/tpu.ipynb
 71%|███████   | 158/223 [04:03<00:40,  1.59it/s]INFO:__main__:Requesting https://www.tensorflow.org/tfrc/
INFO:__main__:Getting metadata for https://www.tensorflow.org/tfrc/
 71%|███████▏  | 159/223 [04:04<00:48,  1.31it/s]INFO:__main__:Requesting http://jonathan.protzenko.fr/2019/01/04/behind-the-scenes.html
INFO:__main__:Getting metadata for https://jonathan.protzenko.fr/2019/01/04/behind-the-scenes.html
 72%|███████▏  | 160/223 [04:05<00:55,  1.13it/s]INFO:__main__:Requesting https://gcc.gnu.org/onlinedocs/cpp/Line-Control.html
INFO:__main__:Getting metadata for https://gcc.gnu.org/onlinedocs/cpp/Line-Control.html
 72%|███████▏  | 161/223 [04:07<01:03,  1.03s/it]INFO:__main__:Requesting https://gcc.gnu.org/onlinedocs/gcc-4.0.4/cpp/Line-Control.html
INFO:__main__:Getting metadata for https://gcc.gnu.org/onlinedocs/gcc-4.0.4/cpp/Line-Control.html
 73%|███████▎  | 162/223 [04:08<01:07,  1.10s/it]INFO:__main__:Requesting https://www.chiark.greenend.org.uk/~sgtatham/coroutines.html
INFO:__main__:Getting metadata for https://www.chiark.greenend.org.uk/~sgtatham/coroutines.html
 73%|███████▎  | 163/223 [04:11<01:33,  1.56s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/CHICKEN_(Scheme_implementation)#Design
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/CHICKEN_(Scheme_implementation)#Design
 74%|███████▎  | 164/223 [04:12<01:24,  1.43s/it]INFO:__main__:Requesting http://home.pipeline.com/~hbaker1/CheneyMTA.html
INFO:__main__:Getting metadata for http://home.pipeline.com/~hbaker1/CheneyMTA.html
 74%|███████▍  | 165/223 [04:13<01:13,  1.27s/it]INFO:__main__:Requesting https://www.vectary.com/
INFO:__main__:Getting metadata for https://www.vectary.com
 74%|███████▍  | 166/223 [04:14<01:09,  1.21s/it]INFO:__main__:Requesting https://clara.io/
INFO:__main__:Getting metadata for https://clara.io
 75%|███████▍  | 167/223 [04:15<01:04,  1.15s/it]INFO:__main__:Requesting https://www.onshape.com/
INFO:__main__:Getting metadata for https://www.onshape.com
 75%|███████▌  | 168/223 [04:15<00:49,  1.11it/s]INFO:__main__:Requesting https://architosh.com/2014/11/autodesk-reportedly-acquires-cloud-based-3d-design-platform-lagoa-for-60-million/
INFO:__main__:Getting metadata for https://architosh.com/2014/11/autodesk-reportedly-acquires-cloud-based-3d-design-platform-lagoa-for-60-million/
 76%|███████▌  | 169/223 [04:16<00:51,  1.06it/s]INFO:__main__:Requesting http://tinkercad.com/
INFO:__main__:Getting metadata for https://www.tinkercad.com
 76%|███████▌  | 170/223 [04:17<00:41,  1.27it/s]INFO:__main__:Requesting https://3dc.io
INFO:__main__:Getting metadata for https://3dc.io
 77%|███████▋  | 171/223 [04:18<00:52,  1.02s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Geometric_modeling_kernel
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Geometric_modeling_kernel
 77%|███████▋  | 172/223 [04:19<00:53,  1.05s/it]INFO:__main__:Requesting https://www.vectary.com/3d-modeling-learn/dimensions-how-to-measure-in-3D
INFO:__main__:Getting metadata for https://www.vectary.com/3d-modeling-learn/dimensions-how-to-measure-in-3D
 78%|███████▊  | 173/223 [04:20<00:50,  1.01s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=0dC1ZRdf9JM
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=0dC1ZRdf9JM
 78%|███████▊  | 174/223 [04:21<00:47,  1.04it/s]INFO:__main__:Requesting https://threejs.org/
INFO:__main__:Getting metadata for https://threejs.org
 78%|███████▊  | 175/223 [04:22<00:38,  1.24it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=eghlSdGvuC0
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=eghlSdGvuC0
 79%|███████▉  | 176/223 [04:22<00:38,  1.23it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/VRML
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/VRML
 79%|███████▉  | 177/223 [04:23<00:40,  1.13it/s]INFO:__main__:Requesting https://nunustudio.org/
INFO:__main__:Getting metadata for https://nunustudio.org
 80%|███████▉  | 178/223 [04:24<00:39,  1.15it/s]INFO:__main__:Requesting https://www.vectary.com/3d-modeling-learn/dimensions-how-to-measure-in-3D/
INFO:__main__:Getting metadata for https://www.vectary.com/3d-modeling-learn/dimensions-how-to-measure-in-3D/
 80%|████████  | 179/223 [04:25<00:38,  1.13it/s]INFO:__main__:Requesting https://www.nytimes.com/2019/03/04/us/politics/nsa-phone-records-program-shut-down.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2019/03/04/us/politics/nsa-phone-records-program-shut-down.html
 81%|████████  | 180/223 [04:25<00:29,  1.46it/s]INFO:__main__:Requesting https://www.nytimes.com/2019/03/04/style/free-office-snacks-diet.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2019/03/04/style/free-office-snacks-diet.html
 81%|████████  | 181/223 [04:26<00:22,  1.85it/s]INFO:__main__:Requesting https://motherboard.vice.com/en_us/article/d33vpq/inside-the-wild-world-of-sneaker-buying-bots
INFO:__main__:Getting metadata for https://motherboard.vice.com/en_us/article/d33vpq/inside-the-wild-world-of-sneaker-buying-bots
 82%|████████▏ | 182/223 [04:26<00:18,  2.21it/s]INFO:__main__:Requesting https://lob.com/blog/understand-design-build-a-framework-for-problem-solving
INFO:__main__:Getting metadata for https://lob.com/blog/understand-design-build-a-framework-for-problem-solving
 82%|████████▏ | 183/223 [04:27<00:30,  1.30it/s]INFO:__main__:Requesting https://intenseminimalism.com/2015/a-framework-for-thinking-about-systems-change/
INFO:__main__:Getting metadata for https://intenseminimalism.com/2015/a-framework-for-thinking-about-systems-change/
 83%|████████▎ | 184/223 [04:28<00:31,  1.25it/s]INFO:__main__:Requesting https://www.htdp.org
INFO:__main__:Getting metadata for https://www.htdp.org
 83%|████████▎ | 185/223 [04:29<00:32,  1.15it/s]INFO:__main__:Requesting https://www.wittenburg.co.uk/Entry.aspx?id=8ec91ced-b3a4-4b07-bf91-17f0efda1718
INFO:__main__:Getting metadata for https://www.wittenburg.co.uk/Entry.aspx?id=8ec91ced-b3a4-4b07-bf91-17f0efda1718
 83%|████████▎ | 186/223 [04:31<00:44,  1.21s/it]INFO:__main__:Requesting https://www.manning.com/books/classic-computer-science-problems-in-python
INFO:__main__:Getting metadata for https://www.manning.com/books/classic-computer-science-problems-in-python
 84%|████████▍ | 187/223 [04:32<00:40,  1.11s/it]INFO:__main__:Requesting https://youtu.be/f84n5oFoZBc
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=f84n5oFoZBc&feature=youtu.be
 84%|████████▍ | 188/223 [04:33<00:37,  1.06s/it]INFO:__main__:Requesting https://www.amazon.com/Change-Design-Transforms-Organizations-Innovation-ebook/dp/B002PEP4EG
INFO:__main__:Getting metadata for https://www.amazon.com/Change-Design-Transforms-Organizations-Innovation-ebook/dp/B002PEP4EG
 85%|████████▍ | 189/223 [04:37<01:06,  1.97s/it]INFO:__main__:Requesting https://www.amazon.com/Solving-Problems-Design-Thinking-Publishing/dp/0231163568/
INFO:__main__:Getting metadata for https://www.amazon.com/Solving-Problems-Design-Thinking-Publishing/dp/0231163568/
 85%|████████▌ | 190/223 [04:45<02:01,  3.69s/it]INFO:__main__:Requesting https://anders.unix.se/2015/10/26/interview-with-dennis-ritchie-2003/
INFO:__main__:Getting metadata for https://anders.unix.se/2015/10/26/interview-with-dennis-ritchie-2003/
 86%|████████▌ | 191/223 [04:47<01:44,  3.28s/it]INFO:__main__:Requesting https://anders.unix.se/2015/12/10/screenshots-from-developers--2002-vs.-2015/
INFO:__main__:Getting metadata for https://anders.unix.se/2015/12/10/screenshots-from-developers--2002-vs.-2015/
 86%|████████▌ | 192/223 [04:49<01:31,  2.96s/it]INFO:__main__:Requesting http://acme.cat-v.org
INFO:__main__:Getting metadata for http://acme.cat-v.org
 87%|████████▋ | 193/223 [04:51<01:15,  2.50s/it]INFO:__main__:Requesting https://github.com/0intro/plan9/blob/7524062cfa4689019a4ed6fc22500ec209522ef0/sys/src/cmd/dict/utils.c#L6
INFO:__main__:Getting metadata for https://github.com/0intro/plan9/blob/7524062cfa4689019a4ed6fc22500ec209522ef0/sys/src/cmd/dict/utils.c#L6
 87%|████████▋ | 194/223 [04:52<00:59,  2.06s/it]INFO:__main__:Requesting https://sidsite.com/articles/190303PianoTuning/
INFO:__main__:Getting metadata for https://sidsite.com/articles/190303PianoTuning/
 87%|████████▋ | 195/223 [04:52<00:43,  1.56s/it]INFO:__main__:Requesting https://www.macrometa.co/blog/why-global-edge-fabric
INFO:__main__:Getting metadata for https://www.macrometa.co/blog/why-global-edge-fabric
 88%|████████▊ | 196/223 [04:52<00:31,  1.15s/it]INFO:__main__:Requesting https://github.com/tidwall/tile38
INFO:__main__:Getting metadata for https://github.com/tidwall/tile38
 88%|████████▊ | 197/223 [04:54<00:29,  1.12s/it]INFO:__main__:Requesting https://devblogs.nvidia.com/thinking-parallel-part-i-collision-detection-gpu/
INFO:__main__:Getting metadata for https://devblogs.nvidia.com/thinking-parallel-part-i-collision-detection-gpu/
 89%|████████▉ | 198/223 [04:54<00:23,  1.05it/s]INFO:__main__:Requesting https://www.gps.gov/systems/gps/performance/accuracy/
INFO:__main__:Getting metadata for https://www.gps.gov/systems/gps/performance/accuracy/
 89%|████████▉ | 199/223 [04:55<00:20,  1.15it/s]INFO:__main__:Requesting https://estimote.com
INFO:__main__:Getting metadata for https://estimote.com
 90%|████████▉ | 200/223 [04:55<00:17,  1.34it/s]INFO:__main__:Requesting https://github.com/tidwall/geojson
INFO:__main__:Getting metadata for https://github.com/tidwall/geojson
 90%|█████████ | 201/223 [04:56<00:16,  1.32it/s]INFO:__main__:Requesting https://console.cloud.google.com/marketplace/details/y-combinator/hacker-news
INFO:__main__:Getting metadata for https://console.cloud.google.com/marketplace/details/y-combinator/hacker-news
 91%|█████████ | 202/223 [04:56<00:13,  1.51it/s]INFO:__main__:Requesting https://issuetracker.google.com/issues/127132286
INFO:__main__:Getting metadata for https://accounts.google.com/ServiceLogin?passive=1209600&continue=https://issuetracker.google.com/issues/127132286&followup=https://issuetracker.google.com/issues/127132286
 91%|█████████ | 203/223 [04:57<00:12,  1.63it/s]INFO:__main__:Requesting https://medium.com/@hoffa/hacker-news-on-bigquery-now-with-daily-updates-so-what-are-the-top-domains-963d3c68b2e2
INFO:__main__:Getting metadata for https://medium.com/@hoffa/hacker-news-on-bigquery-now-with-daily-updates-so-what-are-the-top-domains-963d3c68b2e2
 91%|█████████▏| 204/223 [04:57<00:11,  1.69it/s]INFO:__main__:Requesting http://www.paulgraham.com/spam.html
INFO:__main__:Getting metadata for http://www.paulgraham.com/spam.html
 92%|█████████▏| 205/223 [04:58<00:12,  1.49it/s]INFO:__main__:Requesting http://googlesystem.blogspot.com/2007/07/paul-buchheit-man-behind-gmail.html
INFO:__main__:Getting metadata for http://googlesystem.blogspot.com/2007/07/paul-buchheit-man-behind-gmail.html
 92%|█████████▏| 206/223 [04:59<00:12,  1.41it/s]INFO:__main__:Requesting http://yann.lecun.com/exdb/mnist/
INFO:__main__:Getting metadata for http://yann.lecun.com/exdb/mnist/
 93%|█████████▎| 207/223 [05:00<00:10,  1.47it/s]INFO:__main__:Requesting https://hntrending.com/
INFO:__main__:Getting metadata for https://hntrending.com
 93%|█████████▎| 208/223 [05:01<00:11,  1.36it/s]INFO:__main__:Requesting https://github.com/reactual/hacker-news-favorites-api
INFO:__main__:Getting metadata for https://github.com/reactual/hacker-news-favorites-api
 94%|█████████▎| 209/223 [05:02<00:10,  1.28it/s]INFO:__main__:Requesting https://hnleaderboard.com
INFO:__main__:Getting metadata for https://hnleaderboard.com
 94%|█████████▍| 210/223 [05:02<00:08,  1.57it/s]INFO:__main__:Requesting https://hnify.com/leaderboard.html
INFO:__main__:Getting metadata for https://hnify.com/leaderboard.html
 95%|█████████▍| 211/223 [06:37<05:49, 29.12s/it]INFO:__main__:Requesting https://hnprofile.com/
INFO:__main__:Getting metadata for https://hnprofile.com
 95%|█████████▌| 212/223 [06:38<03:47, 20.68s/it]INFO:__main__:Requesting https://github.com/HackerNews/API
INFO:__main__:Getting metadata for https://github.com/HackerNews/API
 96%|█████████▌| 213/223 [06:39<02:27, 14.73s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Category:Data_serialization_formats
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Category:Data_serialization_formats
 96%|█████████▌| 214/223 [06:40<01:34, 10.54s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Machine_to_machine
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Machine_to_machine
 96%|█████████▋| 215/223 [06:41<01:01,  7.72s/it]INFO:__main__:Requesting https://www.huckmag.com/art-and-culture/photography-2/the-underground-skate-scene-of-90s-brooklyn/
INFO:__main__:Getting metadata for https://www.huckmag.com/art-and-culture/photography-2/the-underground-skate-scene-of-90s-brooklyn/
 97%|█████████▋| 216/223 [06:42<00:40,  5.74s/it]INFO:__main__:Requesting https://code.fb.com/connectivity/fiber-optic-cable/
INFO:__main__:Getting metadata for https://code.fb.com/connectivity/fiber-optic-cable/
 97%|█████████▋| 217/223 [06:43<00:24,  4.11s/it]INFO:__main__:Requesting https://www.scientificamerican.com/article/carbon-nanotube-danger/
INFO:__main__:Getting metadata for https://www.scientificamerican.com/article/carbon-nanotube-danger/
 98%|█████████▊| 218/223 [06:43<00:15,  3.11s/it]INFO:__main__:Requesting https://www.energy.gov/eere/vehicles/downloads/enabling-extreme-fast-charging-technology-gap-assessment
 98%|█████████▊| 219/223 [06:43<00:08,  2.23s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Environment,_health_and_safety
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Environment,_health_and_safety
 99%|█████████▊| 220/223 [06:44<00:05,  1.81s/it]INFO:__main__:Requesting http://www.hse.gov.uk/nanotechnology/
INFO:__main__:Getting metadata for http://www.hse.gov.uk/nanotechnology/
 99%|█████████▉| 221/223 [06:46<00:03,  1.85s/it]INFO:__main__:Requesting http://www.molecularrebar.com/
INFO:__main__:Getting metadata for http://www.molecularrebar.com
100%|█████████▉| 222/223 [06:48<00:01,  1.74s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=4XDJC64tDR0
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=4XDJC64tDR0
100%|██████████| 223/223 [06:49<00:00,  1.55s/it]
