INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  7%|▋         | 2/30 [00:00<00:02, 12.56it/s] 10%|█         | 3/30 [00:00<00:03,  7.37it/s] 17%|█▋        | 5/30 [00:01<00:07,  3.44it/s] 20%|██        | 6/30 [00:03<00:20,  1.20it/s] 23%|██▎       | 7/30 [00:04<00:15,  1.50it/s] 27%|██▋       | 8/30 [00:04<00:11,  1.92it/s] 33%|███▎      | 10/30 [00:06<00:14,  1.42it/s] 37%|███▋      | 11/30 [00:06<00:11,  1.70it/s] 43%|████▎     | 13/30 [00:06<00:07,  2.33it/s] 47%|████▋     | 14/30 [00:07<00:07,  2.22it/s] 53%|█████▎    | 16/30 [00:07<00:04,  2.82it/s] 57%|█████▋    | 17/30 [00:08<00:05,  2.34it/s] 63%|██████▎   | 19/30 [00:08<00:04,  2.70it/s] 67%|██████▋   | 20/30 [00:09<00:03,  3.15it/s] 70%|███████   | 21/30 [00:11<00:08,  1.11it/s] 73%|███████▎  | 22/30 [00:11<00:05,  1.46it/s] 77%|███████▋  | 23/30 [00:11<00:03,  1.78it/s] 80%|████████  | 24/30 [00:11<00:02,  2.24it/s] 87%|████████▋ | 26/30 [00:14<00:02,  1.47it/s] 90%|█████████ | 27/30 [00:14<00:01,  1.83it/s] 93%|█████████▎| 28/30 [00:14<00:00,  2.25it/s] 97%|█████████▋| 29/30 [00:15<00:00,  2.59it/s]100%|██████████| 30/30 [00:16<00:00,  1.60it/s]
  0%|          | 0/247 [00:00<?, ?it/s]INFO:__main__:Requesting https://itnext.io/nodejs-logging-made-right-117a19e8b4ce
INFO:__main__:Getting metadata for https://itnext.io/nodejs-logging-made-right-117a19e8b4ce?gi=5e711fc6a6aa
  0%|          | 1/247 [00:01<05:15,  1.28s/it]INFO:__main__:Requesting https://github.com/stritti/log4js
INFO:__main__:Getting metadata for https://github.com/stritti/log4js
  1%|          | 2/247 [00:02<04:40,  1.15s/it]INFO:__main__:Requesting https://gist.github.com/munificent/b1bcd969063da3e6c298be070a22b604
INFO:__main__:Getting metadata for https://gist.github.com/munificent/b1bcd969063da3e6c298be070a22b604
  1%|          | 3/247 [00:02<04:14,  1.04s/it]INFO:__main__:Requesting https://gitlab.com/snippets/1832264
INFO:__main__:Getting metadata for https://gitlab.com/snippets/1832264
  2%|▏         | 4/247 [00:03<03:37,  1.11it/s]INFO:__main__:Requesting https://gist.github.com/ctsrc/fef3006e1d728bb7271cff0656eb0280/14375eb385e48947999bb370dbcd514f0041ee4c
INFO:__main__:Getting metadata for https://gist.github.com/ctsrc/fef3006e1d728bb7271cff0656eb0280/14375eb385e48947999bb370dbcd514f0041ee4c
  2%|▏         | 5/247 [00:04<03:24,  1.18it/s]INFO:__main__:Requesting https://gist.github.com/ctsrc/fef3006e1d728bb7271cff0656eb0280
INFO:__main__:Getting metadata for https://gist.github.com/ctsrc/fef3006e1d728bb7271cff0656eb0280
  2%|▏         | 6/247 [00:04<03:07,  1.28it/s]INFO:__main__:Requesting https://gist.github.com/munificent/ce8f7a9e6b09938ca8d2d43fa62f9864
INFO:__main__:Getting metadata for https://gist.github.com/munificent/ce8f7a9e6b09938ca8d2d43fa62f9864
  3%|▎         | 7/247 [00:05<02:57,  1.35it/s]INFO:__main__:Requesting https://gist.github.com/femto113/28f69626acddc70a002ecead0b311da4
INFO:__main__:Getting metadata for https://gist.github.com/femto113/28f69626acddc70a002ecead0b311da4
  3%|▎         | 8/247 [00:06<02:44,  1.45it/s]INFO:__main__:Requesting https://twitter.com/munificentbob/status/1101903466111283200
INFO:__main__:Getting metadata for https://twitter.com/munificentbob/status/1101903466111283200
  4%|▎         | 9/247 [00:07<03:18,  1.20it/s]INFO:__main__:Requesting http://www.computinghistory.org.uk/det/51620/Sinclair-ZX-Spectrum-Prototype/
INFO:__main__:Getting metadata for http://www.computinghistory.org.uk/det/51620/Sinclair-ZX-Spectrum-Prototype/
  4%|▍         | 10/247 [00:09<05:12,  1.32s/it]INFO:__main__:Requesting https://youtu.be/XXBxV6-zamM?t=4900
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=XXBxV6-zamM&feature=youtu.be&t=4900
  4%|▍         | 11/247 [00:10<04:42,  1.20s/it]INFO:__main__:Requesting https://hanselminutes.com/670/coding-for-the-zx-spectrum-and-netflixblack-mirrors-bandersnach-with-matt-westcott
INFO:__main__:Getting metadata for https://hanselminutes.com/670/coding-for-the-zx-spectrum-and-netflixblack-mirrors-bandersnach-with-matt-westcott
  5%|▍         | 12/247 [00:11<04:03,  1.04s/it]INFO:__main__:Requesting http://www.zxdesign.info/book/
INFO:__main__:Getting metadata for http://www.zxdesign.info/book/
  5%|▌         | 13/247 [00:12<04:22,  1.12s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=Ts96J7HhO28
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=Ts96J7HhO28
  6%|▌         | 14/247 [00:13<03:59,  1.03s/it]INFO:__main__:Requesting https://retroradionics.co.uk/omni-128-hq-laptop.html
INFO:__main__:Getting metadata for https://retroradionics.co.uk/omni-128-hq-laptop.html
  6%|▌         | 15/247 [00:13<02:58,  1.30it/s]INFO:__main__:Requesting http://markfixesstuff.co.uk/review/zx-spectrum-omni-laptop-review-and-hands-on-test-a-brand-new-portable-sinclair-spectrum-made-from-scratch/
INFO:__main__:Getting metadata for http://markfixesstuff.co.uk/review/zx-spectrum-omni-laptop-review-and-hands-on-test-a-brand-new-portable-sinclair-spectrum-made-from-scratch/
  6%|▋         | 16/247 [00:19<08:26,  2.19s/it]INFO:__main__:Requesting https://www.reddit.com/r/Games/comments/ax9uyj/what_is_it_like_working_at_a_company_during_and/
INFO:__main__:Getting metadata for https://www.reddit.com/r/Games/comments/ax9uyj/what_is_it_like_working_at_a_company_during_and/
  7%|▋         | 17/247 [00:21<08:14,  2.15s/it]INFO:__main__:Requesting https://www.reuters.com/article/us-spotify-india-idUSKCN1QL22C
INFO:__main__:Getting metadata for https://www.reuters.com/article/us-spotify-india-idUSKCN1QL22C
  7%|▋         | 18/247 [00:21<06:00,  1.58s/it]INFO:__main__:Requesting https://www.indexmundi.com/facts/india/ppp-conversion-factor
INFO:__main__:Getting metadata for https://www.indexmundi.com/facts/india/ppp-conversion-factor
  8%|▊         | 19/247 [00:21<04:42,  1.24s/it]INFO:__main__:Requesting https://telecom.economictimes.indiatimes.com/news/data-tariffs-fall-93-in-last-three-years-telecom-department/63537339
INFO:__main__:Getting metadata for https://telecom.economictimes.indiatimes.com/news/data-tariffs-fall-93-in-last-three-years-telecom-department/63537339
  8%|▊         | 20/247 [00:24<06:23,  1.69s/it]INFO:__main__:Requesting https://deezer.com
INFO:__main__:Getting metadata for https://www.deezer.com/us/
  9%|▊         | 21/247 [00:25<05:52,  1.56s/it]INFO:__main__:Requesting https://www.financialexpress.com/economy/reliance-industries-guilty-of-taking-ongc-gas-ap-shah-panel/363706/
INFO:__main__:Getting metadata for https://www.financialexpress.com/economy/reliance-industries-guilty-of-taking-ongc-gas-ap-shah-panel/363706/
  9%|▉         | 22/247 [00:26<04:38,  1.24s/it]INFO:__main__:Requesting https://economictimes.indiatimes.com/industry/energy/oil-gas/arbitration-panel-doesnt-find-ril-at-fault-in-ongc-row/articleshow/65221022.cms
INFO:__main__:Getting metadata for https://economictimes.indiatimes.com/industry/energy/oil-gas/arbitration-panel-doesnt-find-ril-at-fault-in-ongc-row/articleshow/65221022.cms
  9%|▉         | 23/247 [00:27<04:35,  1.23s/it]INFO:__main__:Requesting https://www.statista.com/statistics/274772/forecast-of-mobile-phone-users-in-canada/
INFO:__main__:Getting metadata for https://www.statista.com/statistics/274772/forecast-of-mobile-phone-users-in-canada/
 10%|▉         | 24/247 [00:28<04:01,  1.08s/it]INFO:__main__:Requesting https://www.theguardian.com/technology/2017/jul/13/are-spotifys-fake-artists-any-good
INFO:__main__:Getting metadata for https://www.theguardian.com/technology/2017/jul/13/are-spotifys-fake-artists-any-good
 10%|█         | 25/247 [00:28<03:30,  1.05it/s]INFO:__main__:Requesting https://stratechery.com/2018/lessons-from-spotify/
INFO:__main__:Getting metadata for https://stratechery.com/2018/lessons-from-spotify/
 11%|█         | 26/247 [00:29<03:14,  1.14it/s]INFO:__main__:Requesting https://www.theverge.com/2019/2/26/18241345/spotify-india-launch-warner-music-legal-battle
INFO:__main__:Getting metadata for https://www.theverge.com/2019/2/26/18241345/spotify-india-launch-warner-music-legal-battle
 11%|█         | 27/247 [00:30<03:05,  1.19it/s]INFO:__main__:Requesting http://www.bbc.com/future/story/20190218-are-we-on-the-road-to-civilisation-collapse
INFO:__main__:Getting metadata for http://www.bbc.com/future/story/20190218-are-we-on-the-road-to-civilisation-collapse
 11%|█▏        | 28/247 [00:30<02:45,  1.33it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Third_Rome
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Third_Rome
 12%|█▏        | 29/247 [00:32<03:19,  1.09it/s]INFO:__main__:Requesting https://xkcd.com/978/
INFO:__main__:Getting metadata for https://xkcd.com/978/
 12%|█▏        | 30/247 [00:32<02:44,  1.32it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Romance_languages
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Romance_languages
 13%|█▎        | 31/247 [00:37<07:16,  2.02s/it]INFO:__main__:Requesting https://www.npr.org/templates/story/story.php?storyId=129068241
INFO:__main__:Getting metadata for https://www.npr.org/templates/story/story.php?storyId=129068241
 13%|█▎        | 32/247 [00:38<05:41,  1.59s/it]INFO:__main__:Requesting https://www.philanthropy.com/article/America-s-Generosity-Divide/156175
 13%|█▎        | 33/247 [00:38<04:09,  1.17s/it]INFO:__main__:Requesting https://www.frontiersin.org/articles/10.3389/fpsyg.2017.01619/full
INFO:__main__:Getting metadata for https://www.frontiersin.org/articles/10.3389/fpsyg.2017.01619/full
 14%|█▍        | 34/247 [00:40<05:24,  1.52s/it]INFO:__main__:Requesting https://www.amazon.com/Why-Nations-Fail-Origins-Prosperity/dp/0307719227
INFO:__main__:Getting metadata for https://www.amazon.com/Why-Nations-Fail-Origins-Prosperity/dp/0307719227
 14%|█▍        | 35/247 [00:43<06:39,  1.88s/it]INFO:__main__:Requesting http://www.bbc.com/future/story/20190218-the-lifespans-of-ancient-civilisations-compared
INFO:__main__:Getting metadata for http://www.bbc.com/future/story/20190218-the-lifespans-of-ancient-civilisations-compared
 15%|█▍        | 36/247 [00:43<04:56,  1.41s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Kingdom_of_Israel_(united_monarchy)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Kingdom_of_Israel_(united_monarchy)
 15%|█▍        | 37/247 [00:45<04:58,  1.42s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/List_of_sovereign_states_by_date_of_formation
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/List_of_sovereign_states_by_date_of_formation
 15%|█▌        | 38/247 [00:49<08:17,  2.38s/it]INFO:__main__:Requesting https://www.forbes.com/sites/laurashin/2015/03/26/the-racial-wealth-gap-why-a-typical-white-household-has-16-times-the-wealth-of-a-black-one/#513202511f45
INFO:__main__:Getting metadata for https://www.forbes.com/sites/laurashin/2015/03/26/the-racial-wealth-gap-why-a-typical-white-household-has-16-times-the-wealth-of-a-black-one/#513202511f45
 16%|█▌        | 39/247 [00:50<06:21,  1.84s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Connections_(TV_series)#Connections_(1978)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Connections_(TV_series)#Connections_(1978)
 16%|█▌        | 40/247 [00:51<05:40,  1.64s/it]INFO:__main__:Requesting http://www.ovff.org/pegasus/songs/toast-for-unknown-heroes.html
INFO:__main__:Getting metadata for http://www.ovff.org/pegasus/songs/toast-for-unknown-heroes.html
 17%|█▋        | 41/247 [00:51<04:28,  1.30s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=6zotaRLROtw
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=6zotaRLROtw
 17%|█▋        | 42/247 [00:52<04:01,  1.18s/it]INFO:__main__:Requesting https://www.theregister.co.uk/2019/03/05/spoiler_intel_flaw/
INFO:__main__:Getting metadata for https://www.theregister.co.uk/2019/03/05/spoiler_intel_flaw/
 17%|█▋        | 43/247 [00:53<03:21,  1.01it/s]INFO:__main__:Requesting http://surf.suckless.org/
INFO:__main__:Getting metadata for http://surf.suckless.org
 18%|█▊        | 44/247 [00:54<03:41,  1.09s/it]INFO:__main__:Requesting https://github.com/BayesWitnesses/m2cgen
INFO:__main__:Getting metadata for https://github.com/BayesWitnesses/m2cgen
 18%|█▊        | 45/247 [00:55<03:31,  1.05s/it]INFO:__main__:Requesting https://github.com/nok/sklearn-porter
INFO:__main__:Getting metadata for https://github.com/nok/sklearn-porter
 19%|█▊        | 46/247 [00:56<03:21,  1.00s/it]INFO:__main__:Requesting https://github.com/konstantint/SKompiler
INFO:__main__:Getting metadata for https://github.com/konstantint/SKompiler
 19%|█▉        | 47/247 [00:57<03:21,  1.01s/it]INFO:__main__:Requesting https://github.com/jonnor/emlearn
INFO:__main__:Getting metadata for https://github.com/jonnor/emlearn
 19%|█▉        | 48/247 [00:59<03:42,  1.12s/it]INFO:__main__:Requesting https://onnx.ai/
INFO:__main__:Getting metadata for https://onnx.ai
 20%|█▉        | 49/247 [00:59<02:58,  1.11it/s]INFO:__main__:Requesting https://github.com/pplonski/keras2cpp
INFO:__main__:Getting metadata for https://github.com/pplonski/keras2cpp
 20%|██        | 50/247 [01:00<02:50,  1.16it/s]INFO:__main__:Requesting https://docs.tvm.ai/deploy/index.html
INFO:__main__:Getting metadata for https://docs.tvm.ai/deploy/index.html
 21%|██        | 51/247 [01:00<02:45,  1.19it/s]INFO:__main__:Requesting https://onnc.ai
INFO:__main__:Getting metadata for https://onnc.ai
 21%|██        | 52/247 [01:02<02:58,  1.09it/s]INFO:__main__:Requesting https://www.tensorflow.org/xla/tfcompile
INFO:__main__:Getting metadata for https://www.tensorflow.org/xla/tfcompile
 21%|██▏       | 53/247 [01:02<02:31,  1.28it/s]INFO:__main__:Requesting https://ai.googleblog.com/2019/03/introducing-gpipe-open-source-library.html
INFO:__main__:Getting metadata for https://ai.googleblog.com/2019/03/introducing-gpipe-open-source-library.html
 22%|██▏       | 54/247 [01:02<02:04,  1.55it/s]INFO:__main__:Requesting https://colab.research.google.com/notebooks/tpu.ipynb
INFO:__main__:Getting metadata for https://colab.research.google.com/notebooks/tpu.ipynb
 22%|██▏       | 55/247 [01:03<01:37,  1.98it/s]INFO:__main__:Requesting https://www.tensorflow.org/tfrc/
INFO:__main__:Getting metadata for https://www.tensorflow.org/tfrc/
 23%|██▎       | 56/247 [01:03<01:23,  2.28it/s]INFO:__main__:Requesting https://www.nytimes.com/2019/03/04/health/aids-cure-london-patient.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2019/03/04/health/aids-cure-london-patient.html
 23%|██▎       | 57/247 [01:03<01:13,  2.59it/s]INFO:__main__:Requesting https://www.cdc.gov/hiv/group/racialethnic/africanamericans/index.html
INFO:__main__:Getting metadata for https://www.cdc.gov/hiv/group/racialethnic/africanamericans/index.html
 23%|██▎       | 58/247 [01:04<01:39,  1.90it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=U219eUIZ7Qo
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=U219eUIZ7Qo
 24%|██▍       | 59/247 [01:05<01:58,  1.58it/s]INFO:__main__:Requesting https://www.lovelife.ch/en/campaign/archive/2004-1987/
INFO:__main__:Getting metadata for https://www.lovelife.ch/en/campaign/archive/2004-1987/
 24%|██▍       | 60/247 [01:06<02:45,  1.13it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Simon_Mol
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Simon_Mol
 25%|██▍       | 61/247 [01:07<02:58,  1.04it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=tHEOGrkhDp0
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=tHEOGrkhDp0
 25%|██▌       | 62/247 [01:08<02:52,  1.07it/s]INFO:__main__:Requesting https://ioptconsulting.com/online-advertising-is-the-new-digital-cancer/
INFO:__main__:Getting metadata for https://ioptconsulting.com/online-advertising-is-the-new-digital-cancer/
 26%|██▌       | 63/247 [01:11<04:44,  1.55s/it]INFO:__main__:Requesting https://xkcd.com/1053/
INFO:__main__:Getting metadata for https://xkcd.com/1053/
 26%|██▌       | 64/247 [01:12<03:38,  1.20s/it]INFO:__main__:Requesting https://rationalwiki.org/wiki/Motte_and_bailey
INFO:__main__:Getting metadata for https://rationalwiki.org/wiki/Motte_and_bailey
 26%|██▋       | 65/247 [01:13<03:37,  1.20s/it]INFO:__main__:Requesting http://www.unaids.org/en/resources/presscentre/pressreleaseandstatementarchive/2017/november/20171121_righttohealth_report
INFO:__main__:Getting metadata for http://www.unaids.org/en/resources/presscentre/pressreleaseandstatementarchive/2017/november/20171121_righttohealth_report
 27%|██▋       | 66/247 [01:16<04:59,  1.66s/it]INFO:__main__:Requesting https://www.snopes.com/fact-check/hiv-infected-needle-attacks/
INFO:__main__:Getting metadata for https://www.snopes.com/fact-check/hiv-infected-needle-attacks/
 27%|██▋       | 67/247 [01:16<03:52,  1.29s/it]INFO:__main__:Requesting https://www.theguardian.com/society/2019/mar/05/london-patient-becomes-second-man-to-be-cleared-of-aids-virus
INFO:__main__:Getting metadata for https://www.theguardian.com/society/2019/mar/05/london-patient-becomes-second-man-to-be-cleared-of-aids-virus
 28%|██▊       | 68/247 [01:16<03:07,  1.05s/it]INFO:__main__:Requesting https://jamanetwork.com/journals/jama/article-abstract/2720997
INFO:__main__:Getting metadata for https://jamanetwork.com/journals/jama/article-abstract/2720997
ERROR:__main__:Could not get metadata for https://jamanetwork.com/journals/jama/article-abstract/2720997
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
 28%|██▊       | 69/247 [01:33<17:04,  5.76s/it]INFO:__main__:Requesting https://www.healthline.com/health/hiv-aids/undetectable-viral-load-transmission-risk
INFO:__main__:Getting metadata for https://www.healthline.com/health/hiv-aids/undetectable-viral-load-transmission-risk
 28%|██▊       | 70/247 [01:34<12:18,  4.17s/it]INFO:__main__:Requesting https://www.bbc.com/news/health-43435868
INFO:__main__:Getting metadata for https://www.bbc.com/news/health-43435868
 29%|██▊       | 71/247 [01:34<08:52,  3.03s/it]INFO:__main__:Requesting https://bnf.nice.org.uk/medicinal-forms/rituximab.html
INFO:__main__:Getting metadata for https://www.nice.org.uk/bnf-bnfc-uk-only
 29%|██▉       | 72/247 [01:36<07:27,  2.55s/it]INFO:__main__:Requesting http://www.usccb.org/issues-and-action/human-life-and-dignity/stem-cell-research/index.cfm
INFO:__main__:Getting metadata for http://www.usccb.org/issues-and-action/human-life-and-dignity/stem-cell-research/index.cfm
 30%|██▉       | 73/247 [01:36<05:53,  2.03s/it]INFO:__main__:Requesting https://www.scientificamerican.com/article/human-stem-cells-no-embryo/
INFO:__main__:Getting metadata for https://www.scientificamerican.com/article/human-stem-cells-no-embryo/
 30%|██▉       | 74/247 [01:38<05:58,  2.07s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Timothy_Ray_Brown
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Timothy_Ray_Brown
 30%|███       | 75/247 [01:40<05:02,  1.76s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Graft-versus-host_disease#HIV_elimination
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Graft-versus-host_disease#HIV_elimination
 31%|███       | 76/247 [01:41<04:44,  1.66s/it]INFO:__main__:Requesting https://www.newscientist.com/article/mg23431244-400-immune-war-with-donor-cells-after-transplant-may-wipe-out-hiv/
INFO:__main__:Getting metadata for https://www.newscientist.com/article/mg23431244-400-immune-war-with-donor-cells-after-transplant-may-wipe-out-hiv/
 31%|███       | 77/247 [01:44<06:00,  2.12s/it]INFO:__main__:Requesting https://www.nature.com/news/hopes-of-hiv-cure-in-boston-patients-dashed-1.14324
INFO:__main__:Getting metadata for https://www.nature.com/news/hopes-of-hiv-cure-in-boston-patients-dashed-1.14324
 32%|███▏      | 78/247 [01:49<08:18,  2.95s/it]INFO:__main__:Requesting https://annals.org/aim/article-abstract/2707334/mechanisms-contribute-profound-reduction-hiv-1-reservoir-after-allogeneic-stem
INFO:__main__:Getting metadata for https://annals.org/aim/article-abstract/2707334/mechanisms-contribute-profound-reduction-hiv-1-reservoir-after-allogeneic-stem
ERROR:__main__:Could not get metadata for https://annals.org/aim/article-abstract/2707334/mechanisms-contribute-profound-reduction-hiv-1-reservoir-after-allogeneic-stem
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
 32%|███▏      | 79/247 [01:50<07:00,  2.50s/it]INFO:__main__:Requesting http://www.immunityproject.org
INFO:__main__:Getting metadata for http://www.immunityproject.org
 32%|███▏      | 80/247 [01:51<05:12,  1.87s/it]INFO:__main__:Requesting http://www.immunityproject.org/team
INFO:__main__:Getting metadata for http://www.immunityproject.org/team
 33%|███▎      | 81/247 [01:51<03:49,  1.38s/it]INFO:__main__:Requesting https://old.reddit.com/r/todayilearned/comments/akylvy/til_issac_asimov_contracted_hiv_from_a/
INFO:__main__:Getting metadata for https://old.reddit.com/r/todayilearned/comments/akylvy/til_issac_asimov_contracted_hiv_from_a/
 33%|███▎      | 82/247 [01:52<03:11,  1.16s/it]INFO:__main__:Requesting https://in.reuters.com/article/us-usa-spying-darkmatter/firefox-maker-fears-darkmatter-misuse-of-browser-for-hacking-idINKCN1QL28T
INFO:__main__:Getting metadata for https://in.reuters.com/article/us-usa-spying-darkmatter/firefox-maker-fears-darkmatter-misuse-of-browser-for-hacking-idINKCN1QL28T
 34%|███▎      | 83/247 [01:52<02:26,  1.12it/s]INFO:__main__:Requesting https://groups.google.com/forum/#!topic/mozilla.dev.security.policy/nnLVNfqgz7g
INFO:__main__:Getting metadata for https://groups.google.com/forum/#!topic/mozilla.dev.security.policy/nnLVNfqgz7g
 34%|███▍      | 84/247 [01:53<02:30,  1.09it/s]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=1427262
 34%|███▍      | 85/247 [01:53<01:59,  1.36it/s]INFO:__main__:Requesting https://groups.google.com/d/msg/mozilla.dev.security.policy/nnLVNfqgz7g/OVKywVZIBgAJ
INFO:__main__:Getting metadata for https://groups.google.com/forum/#!msg/mozilla.dev.security.policy/nnLVNfqgz7g/OVKywVZIBgAJ
 35%|███▍      | 86/247 [01:54<02:11,  1.22it/s]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=903966
 35%|███▌      | 87/247 [01:55<01:43,  1.55it/s]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=1440370
 36%|███▌      | 88/247 [01:55<01:22,  1.92it/s]INFO:__main__:Requesting https://stackoverflow.com/questions/51269439/why-are-my-requests-from-https-domain-to-http-localhost-failing-cors
INFO:__main__:Getting metadata for https://stackoverflow.com/questions/51269439/why-are-my-requests-from-https-domain-to-http-localhost-failing-cors
 36%|███▌      | 89/247 [01:56<01:40,  1.57it/s]INFO:__main__:Requesting https://lwn.net/Articles/703485/
INFO:__main__:Getting metadata for https://lwn.net/Articles/703485/
 36%|███▋      | 90/247 [01:56<01:36,  1.62it/s]INFO:__main__:Requesting https://ziahamza.github.io/webui-aria2/
INFO:__main__:Getting metadata for https://ziahamza.github.io/webui-aria2/
 37%|███▋      | 91/247 [01:57<01:37,  1.60it/s]INFO:__main__:Requesting https://github.com/ziahamza/webui-aria2/blob/master/README.md
INFO:__main__:Getting metadata for https://github.com/ziahamza/webui-aria2/blob/master/README.md
 37%|███▋      | 92/247 [01:58<01:42,  1.51it/s]INFO:__main__:Requesting https://blog.prototypr.io/an-exploration-of-variable-fonts-37f85a91a048
INFO:__main__:Getting metadata for https://blog.prototypr.io/an-exploration-of-variable-fonts-37f85a91a048?gi=51be1d86593f
 38%|███▊      | 93/247 [01:59<02:18,  1.11it/s]INFO:__main__:Requesting http://bestofml.com/
INFO:__main__:Getting metadata for http://bestofml.com
 38%|███▊      | 94/247 [01:59<01:49,  1.40it/s]INFO:__main__:Requesting https://p.migdal.pl/interactive-machine-learning-list/
INFO:__main__:Getting metadata for https://p.migdal.pl/interactive-machine-learning-list/
 38%|███▊      | 95/247 [02:00<01:40,  1.52it/s]INFO:__main__:Requesting https://github.com/stared/interactive-machine-learning-list
INFO:__main__:Getting metadata for https://github.com/stared/interactive-machine-learning-list
 39%|███▉      | 96/247 [02:01<01:43,  1.46it/s]INFO:__main__:Requesting http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/
INFO:__main__:Getting metadata for http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/
 39%|███▉      | 97/247 [02:01<01:31,  1.64it/s]INFO:__main__:Requesting http://patorjk.com/blog/2013/03/01/facebook-user-identification-bug/
INFO:__main__:Requesting http://www.tomanthony.co.uk/blog/confirm-google-users-email/
INFO:__main__:Getting metadata for http://www.tomanthony.co.uk/blog/confirm-google-users-email/
 40%|████      | 99/247 [02:01<01:10,  2.09it/s]INFO:__main__:Requesting http://www.tomanthony.co.uk/blog/google-xml-sitemap-auth-bypass-black-hat-seo-bug-bounty/
INFO:__main__:Getting metadata for http://www.tomanthony.co.uk/blog/google-xml-sitemap-auth-bypass-black-hat-seo-bug-bounty/
 40%|████      | 100/247 [02:02<01:08,  2.13it/s]INFO:__main__:Requesting https://www.google.com/about/appsecurity/reward-program/index.html
INFO:__main__:Getting metadata for https://www.google.com/about/appsecurity/reward-program/index.html
 41%|████      | 101/247 [02:02<00:57,  2.52it/s]INFO:__main__:Requesting http://blog.quaji.com/2009/07/facebook-personal-info-leak.html
INFO:__main__:Getting metadata for http://blog.quaji.com/2009/07/facebook-personal-info-leak.html
 41%|████▏     | 102/247 [02:03<01:04,  2.23it/s]INFO:__main__:Requesting https://web.archive.org/web/20190305014509/http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/
INFO:__main__:Getting metadata for https://web.archive.org/web/20190305014509/http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/
ERROR:__main__:Could not get metadata for https://web.archive.org/web/20190305014509/http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fc467aa3390>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190305014509/http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc467aa3390>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20190305014509/http://www.tomanthony.co.uk/blog/facebook-bug-confirm-user-identities/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc467aa3390>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 195, in web_preview
    content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 174, in __init__
    super(TwitterCard, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
 42%|████▏     | 103/247 [04:11<1:32:57, 38.73s/it]INFO:__main__:Requesting https://github.com/PhantomInsights/summarizer
INFO:__main__:Getting metadata for https://github.com/PhantomInsights/summarizer
 42%|████▏     | 104/247 [04:12<1:05:19, 27.41s/it]INFO:__main__:Requesting https://sidsite.com/articles/190303PianoTuning/
INFO:__main__:Getting metadata for https://sidsite.com/articles/190303PianoTuning/
 43%|████▎     | 105/247 [04:12<45:43, 19.32s/it]  INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Piano_acoustics#The_Railsback_curve
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Piano_acoustics#The_Railsback_curve
 43%|████▎     | 106/247 [04:13<32:17, 13.74s/it]INFO:__main__:Requesting https://spsf.pl/pl/marek-koczy/
INFO:__main__:Getting metadata for https://spsf.pl/pl/marek-koczy/
 43%|████▎     | 107/247 [04:15<24:11, 10.37s/it]INFO:__main__:Requesting https://pedrokroger.net/mfgan/
INFO:__main__:Getting metadata for https://pedrokroger.net/mfgan/
 44%|████▎     | 108/247 [04:16<17:02,  7.36s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=1Hqm0dYKUx4
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=1Hqm0dYKUx4
 44%|████▍     | 109/247 [04:17<12:31,  5.45s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=b_fU6yVxDZs
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=b_fU6yVxDZs
 45%|████▍     | 110/247 [04:18<09:22,  4.10s/it]INFO:__main__:Requesting http://iolivia.me/posts/24-hours-of-rust-game-dev/
INFO:__main__:Getting metadata for http://iolivia.me/posts/24-hours-of-rust-game-dev/
 45%|████▍     | 111/247 [04:18<06:40,  2.94s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=aKLntZcp27M
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=aKLntZcp27M
 45%|████▌     | 112/247 [04:19<05:12,  2.32s/it]INFO:__main__:Requesting https://github.com/DaanVanYperen
INFO:__main__:Getting metadata for https://github.com/DaanVanYperen
 46%|████▌     | 113/247 [04:22<05:38,  2.53s/it]INFO:__main__:Requesting http://www.mostlyoriginal.net/
INFO:__main__:Getting metadata for http://www.mostlyoriginal.net
 46%|████▌     | 114/247 [04:23<04:40,  2.11s/it]INFO:__main__:Requesting https://www.amazon.com/Component-Software-Object-Oriented-Programming-Szyperski/dp/B011DCDV40/ref=sr_1_fkmrnull_2
INFO:__main__:Getting metadata for https://www.amazon.com/Component-Software-Object-Oriented-Programming-Szyperski/dp/B011DCDV40/ref=sr_1_fkmrnull_2
 47%|████▋     | 115/247 [04:25<04:38,  2.11s/it]INFO:__main__:Requesting http://www.commitstrip.com/en/2014/11/25/west-side-project-story/
INFO:__main__:Getting metadata for http://www.commitstrip.com/en/2014/11/25/west-side-project-story/
 47%|████▋     | 116/247 [04:26<04:03,  1.86s/it]INFO:__main__:Requesting https://github.com/citybound/citybound
INFO:__main__:Getting metadata for https://github.com/citybound/citybound
 47%|████▋     | 117/247 [04:27<03:28,  1.60s/it]INFO:__main__:Requesting https://blogs.scientificamerican.com/cross-check/the-horgan-surface-and-the-death-of-proof/
INFO:__main__:Getting metadata for https://blogs.scientificamerican.com/cross-check/the-horgan-surface-and-the-death-of-proof/
 48%|████▊     | 118/247 [04:28<02:57,  1.38s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Constructive_proof
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Constructive_proof
 48%|████▊     | 119/247 [04:29<02:38,  1.24s/it]INFO:__main__:Requesting https://github.com/uBlockOrigin/uAssets/issues/1905
INFO:__main__:Getting metadata for https://github.com/uBlockOrigin/uAssets/issues/1905
 49%|████▊     | 120/247 [04:34<05:06,  2.41s/it]INFO:__main__:Requesting https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState
INFO:__main__:Getting metadata for https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState
 49%|████▉     | 121/247 [04:35<03:51,  1.84s/it]INFO:__main__:Requesting https://github.com/douglascrockford/ADsafe
INFO:__main__:Getting metadata for https://github.com/douglascrockford/ADsafe
 49%|████▉     | 122/247 [04:36<03:20,  1.60s/it]INFO:__main__:Requesting https://www.adblockradio.com
INFO:__main__:Getting metadata for https://www.adblockradio.com
 50%|████▉     | 123/247 [04:37<02:55,  1.42s/it]INFO:__main__:Requesting https://github.com/adblockradio/adblockradio
INFO:__main__:Getting metadata for https://github.com/adblockradio/adblockradio
 50%|█████     | 124/247 [04:38<02:41,  1.31s/it]INFO:__main__:Requesting https://wordpress.tv/2017/10/15/james-strang-introduction-to-ad-ops/
ERROR:__main__:Could not reach https://wordpress.tv/2017/10/15/james-strang-introduction-to-ad-ops/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 51%|█████     | 125/247 [04:38<01:57,  1.04it/s]INFO:__main__:Requesting http://danluu.com/monorepo/
INFO:__main__:Getting metadata for http://danluu.com/monorepo/
 51%|█████     | 126/247 [04:38<01:33,  1.29it/s]INFO:__main__:Requesting https://cacm.acm.org/magazines/2016/7/204032/fulltext
INFO:__main__:Getting metadata for https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext
 51%|█████▏    | 127/247 [04:44<04:31,  2.26s/it]INFO:__main__:Requesting https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/pdf
INFO:__main__:Getting metadata for http://delivery.acm.org/10.1145/2860000/2854146/p78-potvin.pdf?ip=35.192.136.167&id=2854146&acc=OA&key=4D4702B0C3E38B35.4D4702B0C3E38B35.4D4702B0C3E38B35.5945DC2EABF3343C&__acm__=1551791461_913c4a3a5d7b0433686d6a3444a56084
 52%|█████▏    | 128/247 [05:45<39:34, 19.96s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=W71BTkUbdqE
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=W71BTkUbdqE
 52%|█████▏    | 129/247 [05:46<27:59, 14.23s/it]INFO:__main__:Requesting https://www.icse2018.org/track/icse-2018-Software-Engineering-in-Practice
INFO:__main__:Getting metadata for https://www.icse2018.org/track/icse-2018-Software-Engineering-in-Practice
 53%|█████▎    | 130/247 [05:48<20:31, 10.53s/it]INFO:__main__:Requesting https://github.com/korfuri/awesome-monorepo
INFO:__main__:Getting metadata for https://github.com/korfuri/awesome-monorepo
 53%|█████▎    | 131/247 [05:49<14:49,  7.67s/it]INFO:__main__:Requesting https://theintercept.com/2019/03/04/google-ongoing-project-dragonfly/
INFO:__main__:Getting metadata for https://theintercept.com/2019/03/04/google-ongoing-project-dragonfly/
 53%|█████▎    | 132/247 [05:49<10:23,  5.42s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Mess_of_pottage
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Mess_of_pottage
 54%|█████▍    | 133/247 [05:50<07:39,  4.03s/it]INFO:__main__:Requesting https://www.reuters.com/investigates/special-report/muslims-camps-china/
INFO:__main__:Getting metadata for https://www.reuters.com/investigates/special-report/muslims-camps-china/
 54%|█████▍    | 134/247 [05:50<05:26,  2.89s/it]INFO:__main__:Requesting https://www.businessinsider.com/finally-specific-demands-from-occupy-wall-street-2011-9
INFO:__main__:Getting metadata for https://www.businessinsider.com/finally-specific-demands-from-occupy-wall-street-2011-9
 55%|█████▍    | 135/247 [05:51<03:57,  2.12s/it]INFO:__main__:Requesting https://www.washingtontimes.com/blog/watercooler/2011/oct/3/picket-occupy-wall-street-protesters-post-manifest/
INFO:__main__:Getting metadata for https://www.washingtontimes.com/blog/watercooler/2011/oct/3/picket-occupy-wall-street-protesters-post-manifest/
 55%|█████▌    | 136/247 [05:51<03:13,  1.75s/it]INFO:__main__:Requesting https://pastebin.com/gPgy648A
INFO:__main__:Getting metadata for https://pastebin.com/gPgy648A
 55%|█████▌    | 137/247 [05:52<02:21,  1.28s/it]INFO:__main__:Requesting https://www.bmj.com/content/364/bmj.l596
INFO:__main__:Getting metadata for https://www.bmj.com/content/364/bmj.l596
 56%|█████▌    | 138/247 [05:54<02:51,  1.57s/it]INFO:__main__:Requesting https://twitter.com/existentialcoms/status/1051547413083652096
INFO:__main__:Getting metadata for https://twitter.com/existentialcoms/status/1051547413083652096
 56%|█████▋    | 139/247 [05:55<02:31,  1.40s/it]INFO:__main__:Requesting https://newsyndicalist.org/2017/09/30/union-cooperative-strategy-david-oconnell/
ERROR:__main__:Could not reach https://newsyndicalist.org/2017/09/30/union-cooperative-strategy-david-oconnell/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 57%|█████▋    | 140/247 [05:55<01:49,  1.03s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Death_of_Wei_Zexi
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Death_of_Wei_Zexi
 57%|█████▋    | 141/247 [05:56<01:41,  1.05it/s]INFO:__main__:Requesting https://www.ft.com/content/9be0b974-10e9-11e6-bb40-c30e3bfcf63b
INFO:__main__:Getting metadata for https://www.ft.com/content/9be0b974-10e9-11e6-bb40-c30e3bfcf63b
 57%|█████▋    | 142/247 [05:58<02:12,  1.26s/it]INFO:__main__:Requesting https://www.washingtonpost.com/technology/2018/10/16/google-really-is-trying-build-censored-chinese-search-engine-its-ceo-confirms/?noredirect=on&utm_term=.cab0c09d7760
ERROR:__main__:Could not reach https://www.washingtonpost.com/technology/2018/10/16/google-really-is-trying-build-censored-chinese-search-engine-its-ceo-confirms/?noredirect=on&utm_term=.cab0c09d7760
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)
 58%|█████▊    | 143/247 [06:04<04:41,  2.70s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Google_China#Operation_Aurora_and_2010_withdrawal
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Google_China#Operation_Aurora_and_2010_withdrawal
 58%|█████▊    | 144/247 [06:06<04:05,  2.38s/it]INFO:__main__:Requesting https://nypost.com/2017/11/21/apple-has-been-using-teen-labor-to-assemble-the-iphone-x/
ERROR:__main__:Could not reach https://nypost.com/2017/11/21/apple-has-been-using-teen-labor-to-assemble-the-iphone-x/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 59%|█████▊    | 145/247 [06:06<02:54,  1.71s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Censorship_by_Google
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Censorship_by_Google
 59%|█████▉    | 146/247 [06:07<02:47,  1.66s/it]INFO:__main__:Requesting https://www.macrometa.co/blog/why-global-edge-fabric
INFO:__main__:Getting metadata for https://www.macrometa.co/blog/why-global-edge-fabric
 60%|█████▉    | 147/247 [06:08<02:03,  1.24s/it]INFO:__main__:Requesting https://www.macrometa.co/product
INFO:__main__:Getting metadata for https://www.macrometa.co/product
 60%|█████▉    | 148/247 [06:08<01:33,  1.05it/s]INFO:__main__:Requesting https://github.com/amark/gun
INFO:__main__:Getting metadata for https://github.com/amark/gun
 60%|██████    | 149/247 [06:09<01:44,  1.06s/it]INFO:__main__:Requesting https://motherboard.vice.com/en_us/article/d33vpq/inside-the-wild-world-of-sneaker-buying-bots
INFO:__main__:Getting metadata for https://motherboard.vice.com/en_us/article/d33vpq/inside-the-wild-world-of-sneaker-buying-bots
 61%|██████    | 150/247 [06:09<01:19,  1.22it/s]INFO:__main__:Requesting https://anders.unix.se/2015/10/26/interview-with-dennis-ritchie-2003/
INFO:__main__:Getting metadata for https://anders.unix.se/2015/10/26/interview-with-dennis-ritchie-2003/
 61%|██████    | 151/247 [06:12<02:03,  1.29s/it]INFO:__main__:Requesting https://anders.unix.se/2015/12/10/screenshots-from-developers--2002-vs.-2015/
INFO:__main__:Getting metadata for https://anders.unix.se/2015/12/10/screenshots-from-developers--2002-vs.-2015/
 62%|██████▏   | 152/247 [06:14<02:28,  1.57s/it]INFO:__main__:Requesting http://spinroot.com/pico/pjw.html
INFO:__main__:Getting metadata for http://spinroot.com/pico/pjw.html
 62%|██████▏   | 153/247 [06:15<02:11,  1.40s/it]INFO:__main__:Requesting http://acme.cat-v.org
INFO:__main__:Getting metadata for http://acme.cat-v.org
 62%|██████▏   | 154/247 [06:16<02:08,  1.38s/it]INFO:__main__:Requesting https://github.com/0intro/plan9/blob/7524062cfa4689019a4ed6fc22500ec209522ef0/sys/src/cmd/dict/utils.c#L6
INFO:__main__:Getting metadata for https://github.com/0intro/plan9/blob/7524062cfa4689019a4ed6fc22500ec209522ef0/sys/src/cmd/dict/utils.c#L6
 63%|██████▎   | 155/247 [06:17<01:56,  1.27s/it]INFO:__main__:Requesting http://millcomputing.com/wiki/Memory
INFO:__main__:Getting metadata for http://millcomputing.com/wiki/Memory
 63%|██████▎   | 156/247 [06:18<01:38,  1.08s/it]INFO:__main__:Requesting http://www.ianbicking.org/blog/2019/03/firefox-experiments-i-would-have-liked.html
INFO:__main__:Getting metadata for http://www.ianbicking.org/blog/2019/03/firefox-experiments-i-would-have-liked.html
 64%|██████▎   | 157/247 [06:19<01:33,  1.03s/it]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/snoozetabs/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/snoozetabs/
 64%|██████▍   | 158/247 [06:20<01:33,  1.05s/it]INFO:__main__:Requesting https://firefoxur.github.io/
INFO:__main__:Getting metadata for https://firefoxur.github.io
 64%|██████▍   | 159/247 [06:21<01:28,  1.00s/it]INFO:__main__:Requesting https://chrome.google.com/webstore/detail/workona-tab-manager-produ/ailcmbgekjpnablpdkmaaccecekgdhlh?hl=en
INFO:__main__:Getting metadata for https://chrome.google.com/webstore/detail/workona-tab-manager-produ/ailcmbgekjpnablpdkmaaccecekgdhlh?hl=en
 65%|██████▍   | 160/247 [06:21<01:05,  1.33it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/window-titler/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/window-titler/
 65%|██████▌   | 161/247 [06:22<01:12,  1.19it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/
 66%|██████▌   | 162/247 [06:23<01:15,  1.12it/s]INFO:__main__:Requesting https://chrome.google.com/webstore/detail/openlist/nkpjembldfckmdchbdiclhfedcngbgnl?hl=en
INFO:__main__:Getting metadata for https://chrome.google.com/webstore/detail/openlist/nkpjembldfckmdchbdiclhfedcngbgnl?hl=en
 66%|██████▌   | 163/247 [06:23<00:56,  1.49it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/
 66%|██████▋   | 164/247 [06:24<01:06,  1.25it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/panorama-tab-groups/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/panorama-tab-groups/
 67%|██████▋   | 165/247 [06:25<01:10,  1.16it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-GB/firefox/addon/panorama-view/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-GB/firefox/addon/panorama-view/
 67%|██████▋   | 166/247 [06:26<01:14,  1.09it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/JScript
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/JScript
 68%|██████▊   | 167/247 [06:28<01:27,  1.10s/it]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/tabist/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/tabist/
 68%|██████▊   | 168/247 [06:29<01:25,  1.08s/it]INFO:__main__:Requesting https://chrome.google.com/webstore/detail/tabist/hdjegjggiogfkaldbfphfdkpggjemaha
INFO:__main__:Getting metadata for https://chrome.google.com/webstore/detail/tabist/hdjegjggiogfkaldbfphfdkpggjemaha
 68%|██████▊   | 169/247 [06:29<01:03,  1.23it/s]INFO:__main__:Requesting https://github.com/fiveNinePlusR/tabist
INFO:__main__:Getting metadata for https://github.com/fiveNinePlusR/tabist
 69%|██████▉   | 170/247 [06:30<01:04,  1.19it/s]INFO:__main__:Requesting https://support.apple.com/en-us/HT209101
INFO:__main__:Getting metadata for https://support.apple.com/en-us/HT209101
 69%|██████▉   | 171/247 [06:30<00:51,  1.48it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/tab-jump-list/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/tab-jump-list/
 70%|██████▉   | 172/247 [06:31<00:58,  1.29it/s]INFO:__main__:Requesting https://getpocket.com/
INFO:__main__:Getting metadata for https://getpocket.com
 70%|███████   | 173/247 [06:32<01:04,  1.15it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/onetab/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/onetab/
 70%|███████   | 174/247 [06:33<01:06,  1.10it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/better-onetab/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/better-onetab/
 71%|███████   | 175/247 [06:35<01:08,  1.05it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/
 71%|███████▏  | 176/247 [06:36<01:09,  1.03it/s]INFO:__main__:Requesting https://www.qutebrowser.org/
INFO:__main__:Getting metadata for https://www.qutebrowser.org
 72%|███████▏  | 177/247 [06:38<01:49,  1.57s/it]INFO:__main__:Requesting https://webextensions-experiments.readthedocs.io/en/latest/index.html
INFO:__main__:Getting metadata for https://webextensions-experiments.readthedocs.io/en/latest/index.html
 72%|███████▏  | 178/247 [06:40<01:38,  1.43s/it]INFO:__main__:Requesting https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/basics.html
INFO:__main__:Getting metadata for https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/basics.html
 72%|███████▏  | 179/247 [06:40<01:20,  1.19s/it]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=1397874
 73%|███████▎  | 180/247 [06:41<01:01,  1.09it/s]INFO:__main__:Requesting https://www.dropbox.com/s/2va0icchtittbnx/shortcuts-experiment.zip?dl=1
INFO:__main__:Getting metadata for https://ucd87de84644880d0148fe3b27c2.dl.dropboxusercontent.com/cd/0/get/AchQV10sxLPVkXJHXb551i_j4Q-eMNRL4Tmoe9mQJpCS8ahSUCczVQjBm2SBB2elYypVlAqJ85hr9qkIunW0USsKSIqek4XG2qXiPmH9-0WDDssmye4bWKLgc4XmQMSCeVg/file?dl=1
 73%|███████▎  | 181/247 [06:43<01:41,  1.54s/it]INFO:__main__:Requesting https://support.mozilla.org/en-US/kb/awesome-bar-search-firefox-bookmarks-history-tabs#w_changing-results-on-the-fly_2
INFO:__main__:Getting metadata for https://support.mozilla.org/en-US/kb/awesome-bar-search-firefox-bookmarks-history-tabs#w_changing-results-on-the-fly_2
 74%|███████▎  | 182/247 [06:45<01:49,  1.68s/it]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=1303384
 74%|███████▍  | 183/247 [06:46<01:19,  1.25s/it]INFO:__main__:Requesting https://github.com/cmcaine/tridactyl
INFO:__main__:Getting metadata for https://github.com/tridactyl/tridactyl
 74%|███████▍  | 184/247 [06:47<01:15,  1.20s/it]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/
 75%|███████▍  | 185/247 [06:48<01:12,  1.18s/it]INFO:__main__:Requesting http://www.ianbicking.org/blog/2018/02/web-small-composable-tools.html
INFO:__main__:Getting metadata for http://www.ianbicking.org/blog/2018/02/web-small-composable-tools.html
 75%|███████▌  | 186/247 [06:50<01:23,  1.36s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/MH_Message_Handling_System
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/MH_Message_Handling_System
 76%|███████▌  | 187/247 [06:51<01:12,  1.21s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Acme_(text_editor)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Acme_(text_editor)
 76%|███████▌  | 188/247 [06:51<01:03,  1.08s/it]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/saka/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/saka/
 77%|███████▋  | 189/247 [06:52<01:02,  1.08s/it]INFO:__main__:Requesting https://addons.mozilla.org/de/firefox/addon/better-image-viewer/
INFO:__main__:Getting metadata for https://addons.mozilla.org/de/firefox/addon/better-image-viewer/
 77%|███████▋  | 190/247 [06:53<01:00,  1.06s/it]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/tip-tab/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/tip-tab/
 77%|███████▋  | 191/247 [06:55<01:00,  1.08s/it]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=866522
 78%|███████▊  | 192/247 [06:55<00:45,  1.20it/s]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=1478037
 78%|███████▊  | 193/247 [06:55<00:35,  1.52it/s]INFO:__main__:Requesting https://github.com/mems/bookmarklets-context-menu
INFO:__main__:Getting metadata for https://github.com/mems/bookmarklets-context-menu
 79%|███████▊  | 194/247 [06:56<00:36,  1.45it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
 79%|███████▉  | 195/247 [06:57<00:42,  1.22it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/
 79%|███████▉  | 196/247 [06:58<00:47,  1.07it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/first-party-isolation/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/first-party-isolation/
 80%|███████▉  | 197/247 [06:59<00:47,  1.05it/s]INFO:__main__:Requesting https://www.ghacks.net/2017/11/22/how-to-enable-first-party-isolation-in-firefox/
INFO:__main__:Getting metadata for https://www.ghacks.net/2017/11/22/how-to-enable-first-party-isolation-in-firefox/
 80%|████████  | 198/247 [06:59<00:35,  1.37it/s]INFO:__main__:Requesting https://textslashplain.com/2017/01/14/the-line-of-death/
ERROR:__main__:Could not reach https://textslashplain.com/2017/01/14/the-line-of-death/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 81%|████████  | 199/247 [07:00<00:26,  1.80it/s]INFO:__main__:Requesting https://ipfs.io/#why
INFO:__main__:Getting metadata for https://ipfs.io/#why
 81%|████████  | 200/247 [07:00<00:22,  2.05it/s]INFO:__main__:Requesting https://filecoin.io/
INFO:__main__:Getting metadata for https://filecoin.io
 81%|████████▏ | 201/247 [07:01<00:27,  1.65it/s]INFO:__main__:Requesting https://www.narro.co
INFO:__main__:Getting metadata for https://www.narro.co
 82%|████████▏ | 202/247 [07:01<00:25,  1.77it/s]INFO:__main__:Requesting http://acrowdedspace.com/post/166470695392/the-rebundling-of-craigslist
INFO:__main__:Getting metadata for http://acrowdedspace.com/post/166470695392/the-rebundling-of-craigslist
 82%|████████▏ | 203/247 [07:02<00:23,  1.87it/s]INFO:__main__:Requesting https://distill.io/
INFO:__main__:Getting metadata for https://distill.io
 83%|████████▎ | 204/247 [07:02<00:19,  2.19it/s]INFO:__main__:Requesting https://wiki.mozilla.org/Labs/Ubiquity
INFO:__main__:Getting metadata for https://wiki.mozilla.org/Labs/Ubiquity
 83%|████████▎ | 205/247 [07:03<00:30,  1.38it/s]INFO:__main__:Requesting https://imgur.com/O8rN9fK
INFO:__main__:Getting metadata for https://imgur.com/O8rN9fK
 83%|████████▎ | 206/247 [07:04<00:24,  1.70it/s]INFO:__main__:Requesting https://addons.mozilla.org/firefox/addon/reader-view/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/reader-view/
 84%|████████▍ | 207/247 [07:05<00:30,  1.33it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/automatic-reader-view/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/automatic-reader-view/
 84%|████████▍ | 208/247 [07:06<00:32,  1.21it/s]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/tile-tabs-we/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/tile-tabs-we/
 85%|████████▍ | 209/247 [07:07<00:34,  1.09it/s]INFO:__main__:Requesting https://www.theverge.com/2017/12/16/16784628/mozilla-mr-robot-arg-plugin-firefox-looking-glass
INFO:__main__:Getting metadata for https://www.theverge.com/2017/12/16/16784628/mozilla-mr-robot-arg-plugin-firefox-looking-glass
 85%|████████▌ | 210/247 [07:07<00:30,  1.23it/s]INFO:__main__:Requesting https://www.nytimes.com/2019/03/04/us/politics/nsa-phone-records-program-shut-down.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2019/03/04/us/politics/nsa-phone-records-program-shut-down.html
 85%|████████▌ | 211/247 [07:08<00:22,  1.57it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Limited_hangout
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Limited_hangout
 86%|████████▌ | 212/247 [07:08<00:23,  1.49it/s]INFO:__main__:Requesting https://www.newsweek.com/att-spying-program-worse-snowden-revelations-513812
INFO:__main__:Getting metadata for https://www.newsweek.com/att-spying-program-worse-snowden-revelations-513812
 86%|████████▌ | 213/247 [07:09<00:19,  1.71it/s]INFO:__main__:Requesting https://reason.com/blog/2013/09/02/report-dea-has-been-secretly-snooping-on
INFO:__main__:Getting metadata for https://reason.com/blog/2013/09/02/report-dea-has-been-secretly-snooping-on
 87%|████████▋ | 214/247 [07:12<00:48,  1.46s/it]INFO:__main__:Requesting https://www.fastcompany.com/40590766/atts-long-partnership-with-nsa-is-just-another-swamp-romance
INFO:__main__:Getting metadata for https://www.fastcompany.com/40590766/atts-long-partnership-with-nsa-is-just-another-swamp-romance
 87%|████████▋ | 215/247 [07:13<00:36,  1.14s/it]INFO:__main__:Requesting https://www.cnet.com/news/dea-supplied-with-access-to-vast-database-of-at-t-phone-records/
INFO:__main__:Getting metadata for https://www.cnet.com/news/dea-supplied-with-access-to-vast-database-of-at-t-phone-records/
 87%|████████▋ | 216/247 [07:13<00:27,  1.13it/s]INFO:__main__:Requesting https://www.aol.com/article/finance/2016/10/25/atandt-reportedly-has-a-secret-program-that-helps-law-enforcement/21591852/
INFO:__main__:Getting metadata for https://www.aol.com/article/finance/2016/10/25/atandt-reportedly-has-a-secret-program-that-helps-law-enforcement/21591852/
 88%|████████▊ | 217/247 [07:14<00:26,  1.14it/s]INFO:__main__:Requesting https://www.cnbc.com/2013/11/07/cia-said-to-pay-att-for-call-data.html
INFO:__main__:Getting metadata for https://www.cnbc.com/2013/11/07/cia-said-to-pay-att-for-call-data.html
 88%|████████▊ | 218/247 [07:14<00:22,  1.31it/s]INFO:__main__:Requesting https://www.aclu.org/other/hepting-v-att-challenging-corporate-collusion-nsa
INFO:__main__:Getting metadata for https://www.aclu.org/other/hepting-v-att-challenging-corporate-collusion-nsa
 89%|████████▊ | 219/247 [07:15<00:17,  1.63it/s]INFO:__main__:Requesting https://libertyblitzkrieg.com/2016/10/27/u-s-taxpayers-pay-att-millions-of-dollars-a-year-for-the-privilege-of-spying-on-them/
INFO:__main__:Getting metadata for https://libertyblitzkrieg.com/2016/10/27/u-s-taxpayers-pay-att-millions-of-dollars-a-year-for-the-privilege-of-spying-on-them/
 89%|████████▉ | 220/247 [07:15<00:15,  1.73it/s]INFO:__main__:Requesting https://phys.org/news/2019-03-welding-breakthrough.html
INFO:__main__:Getting metadata for https://phys.org/news/2019-03-welding-breakthrough.html
 89%|████████▉ | 221/247 [07:16<00:14,  1.74it/s]INFO:__main__:Requesting http://www.youtube.com/watch?v=JEpsKnWZrJ8
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=JEpsKnWZrJ8
 90%|████████▉ | 222/247 [07:17<00:16,  1.49it/s]INFO:__main__:Requesting https://www.hw.ac.uk/about/news/2019/welding-breakthrough-could-transform.htm
INFO:__main__:Getting metadata for https://www.hw.ac.uk/about/news/2019/welding-breakthrough-could-transform.htm
ERROR:__main__:Could not get metadata for https://www.hw.ac.uk/about/news/2019/welding-breakthrough-could-transform.htm
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
 90%|█████████ | 223/247 [07:24<01:04,  2.69s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/De_Havilland_Comet
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/De_Havilland_Comet
 91%|█████████ | 224/247 [07:26<00:57,  2.51s/it]INFO:__main__:Requesting https://blog.coinbase.com/living-up-to-our-values-and-the-neutrino-acquisition-ba98174cdcf6
INFO:__main__:Getting metadata for https://blog.coinbase.com/living-up-to-our-values-and-the-neutrino-acquisition-ba98174cdcf6?gi=b3e87a37bc1
 91%|█████████ | 225/247 [07:27<00:45,  2.07s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Hacking_Team
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Hacking_Team
 91%|█████████▏| 226/247 [07:29<00:40,  1.93s/it]INFO:__main__:Requesting https://techcrunch.com/2019/03/04/neutrino-employees-who-once-worked-for-a-controversial-surveillance-tech-company-will-leave-coinbase/
ERROR:__main__:Could not reach https://techcrunch.com/2019/03/04/neutrino-employees-who-once-worked-for-a-controversial-surveillance-tech-company-will-leave-coinbase/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 92%|█████████▏| 227/247 [07:29<00:27,  1.39s/it]INFO:__main__:Requesting https://www.nelp.org/publication/ban-the-box-fair-chance-hiring-state-and-local-guide/
INFO:__main__:Getting metadata for https://www.nelp.org/publication/ban-the-box-fair-chance-hiring-state-and-local-guide/
 92%|█████████▏| 228/247 [07:29<00:21,  1.14s/it]INFO:__main__:Requesting https://blog.cloudflare.com/building-fast-interpreters-in-rust/
INFO:__main__:Getting metadata for https://blog.cloudflare.com/building-fast-interpreters-in-rust/
 93%|█████████▎| 229/247 [07:30<00:16,  1.08it/s]INFO:__main__:Requesting https://blog.cloudflare.com/how-we-made-firewall-rules/
INFO:__main__:Getting metadata for https://blog.cloudflare.com/how-we-made-firewall-rules/
 93%|█████████▎| 230/247 [07:30<00:13,  1.30it/s]INFO:__main__:Requesting https://www.usenix.org/publications/login/fall2017
INFO:__main__:Getting metadata for https://www.usenix.org/publications/login/fall2017
 94%|█████████▎| 231/247 [07:31<00:14,  1.14it/s]INFO:__main__:Requesting https://www.reddit.com/r/rust/comments/awx9cy/github_kyrenluster_an_experimental_lua_vm/
INFO:__main__:Getting metadata for https://www.reddit.com/r/rust/comments/awx9cy/github_kyrenluster_an_experimental_lua_vm/
 94%|█████████▍| 232/247 [07:33<00:17,  1.15s/it]INFO:__main__:Requesting https://github.com/postgres/postgres/blob/master/src/backend/executor/execExprInterp.c
INFO:__main__:Getting metadata for https://github.com/postgres/postgres/blob/master/src/backend/executor/execExprInterp.c
 94%|█████████▍| 233/247 [07:35<00:21,  1.52s/it]INFO:__main__:Requesting https://inko-lang.org/
INFO:__main__:Getting metadata for https://inko-lang.org
 95%|█████████▍| 234/247 [07:37<00:18,  1.43s/it]INFO:__main__:Requesting https://gitlab.com/inko-lang/inko/blob/master/vm/src/vm/machine.rs#L294
INFO:__main__:Getting metadata for https://gitlab.com/inko-lang/inko/blob/master/vm/src/vm/machine.rs#L294
 95%|█████████▌| 235/247 [07:38<00:15,  1.31s/it]INFO:__main__:Requesting https://www.slideshare.net/RReverser/building-fast-interpreters-in-rust
INFO:__main__:Getting metadata for https://www.slideshare.net/RReverser/building-fast-interpreters-in-rust
 96%|█████████▌| 236/247 [07:39<00:14,  1.35s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Threaded_code#Subroutine_threading
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Threaded_code#Subroutine_threading
 96%|█████████▌| 237/247 [07:40<00:13,  1.31s/it]INFO:__main__:Requesting https://www.colm.net/open-source/ragel/
INFO:__main__:Getting metadata for https://www.colm.net/open-source/ragel/
 96%|█████████▋| 238/247 [07:41<00:10,  1.16s/it]INFO:__main__:Requesting https://hal.inria.fr/hal-01100647/document
INFO:__main__:Getting metadata for https://hal.inria.fr/hal-01100647/document
 97%|█████████▋| 239/247 [08:00<00:50,  6.35s/it]INFO:__main__:Requesting https://kseo.github.io/posts/2017-01-09-continuation-passing-style-interpreter.html
INFO:__main__:Getting metadata for https://kseo.github.io/posts/2017-01-09-continuation-passing-style-interpreter.html
 97%|█████████▋| 240/247 [08:00<00:32,  4.58s/it]INFO:__main__:Requesting https://github.com/eclipse/openj9/blob/01be53f659a8190959c1641eac20b0488739e94c/runtime/vm/BytecodeInterpreter.hpp#L4872
INFO:__main__:Getting metadata for https://github.com/eclipse/openj9/blob/01be53f659a8190959c1641eac20b0488739e94c/runtime/vm/BytecodeInterpreter.hpp#L4872
 98%|█████████▊| 241/247 [08:05<00:27,  4.56s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Threaded_code
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Threaded_code
 98%|█████████▊| 242/247 [08:06<00:17,  3.52s/it]INFO:__main__:Requesting https://youtu.be/Hqw57GJSrac?t=341
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=Hqw57GJSrac&feature=youtu.be&t=341
 98%|█████████▊| 243/247 [08:07<00:10,  2.72s/it]INFO:__main__:Requesting https://github.com/cloudflare/wirefilter
INFO:__main__:Getting metadata for https://github.com/cloudflare/wirefilter
 99%|█████████▉| 244/247 [08:08<00:06,  2.25s/it]INFO:__main__:Requesting http://smallcultfollowing.com/babysteps/blog/2018/04/24/rust-pattern-precise-closure-capture-clauses/#a-more-general-pattern
INFO:__main__:Getting metadata for http://smallcultfollowing.com/babysteps/blog/2018/04/24/rust-pattern-precise-closure-capture-clauses/#a-more-general-pattern
 99%|█████████▉| 245/247 [08:08<00:03,  1.80s/it]INFO:__main__:Requesting https://blog.cloudflare.com/incident-report-on-memory-leak-caused-by-cloudflare-parser-bug/
INFO:__main__:Getting metadata for https://blog.cloudflare.com/incident-report-on-memory-leak-caused-by-cloudflare-parser-bug/
100%|█████████▉| 246/247 [08:09<00:01,  1.49s/it]INFO:__main__:Requesting https://godbolt.org/z/UE-Mb0
INFO:__main__:Getting metadata for https://godbolt.org/z/UE-Mb0
100%|██████████| 247/247 [08:10<00:00,  1.22s/it]
