INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  3%|▎         | 1/30 [00:03<01:45,  3.62s/it]  7%|▋         | 2/30 [00:04<01:17,  2.76s/it] 13%|█▎        | 4/30 [00:06<00:57,  2.22s/it] 17%|█▋        | 5/30 [00:08<00:53,  2.13s/it] 20%|██        | 6/30 [00:08<00:36,  1.53s/it] 23%|██▎       | 7/30 [00:09<00:33,  1.44s/it] 27%|██▋       | 8/30 [00:10<00:27,  1.24s/it] 30%|███       | 9/30 [00:10<00:19,  1.11it/s] 33%|███▎      | 10/30 [00:11<00:16,  1.24it/s] 37%|███▋      | 11/30 [00:11<00:12,  1.51it/s] 40%|████      | 12/30 [00:11<00:10,  1.79it/s] 43%|████▎     | 13/30 [00:12<00:09,  1.83it/s] 47%|████▋     | 14/30 [00:13<00:10,  1.53it/s] 50%|█████     | 15/30 [00:13<00:07,  1.95it/s] 53%|█████▎    | 16/30 [00:16<00:17,  1.23s/it] 60%|██████    | 18/30 [00:22<00:22,  1.85s/it] 63%|██████▎   | 19/30 [00:23<00:15,  1.42s/it] 67%|██████▋   | 20/30 [00:23<00:11,  1.18s/it] 70%|███████   | 21/30 [00:24<00:08,  1.12it/s] 80%|████████  | 24/30 [00:24<00:03,  1.52it/s] 83%|████████▎ | 25/30 [00:25<00:03,  1.44it/s] 87%|████████▋ | 26/30 [00:25<00:02,  1.57it/s] 90%|█████████ | 27/30 [00:25<00:01,  1.98it/s] 97%|█████████▋| 29/30 [00:26<00:00,  2.66it/s]100%|██████████| 30/30 [00:26<00:00,  1.15it/s]
  0%|          | 0/267 [00:00<?, ?it/s]INFO:__main__:Requesting https://www.marketplace.org/2019/03/06/tech/exclusive-look-numbers-showing-users-leaving-facebook-by-the-millions
INFO:__main__:Getting metadata for https://www.marketplace.org/2019/03/06/tech/exclusive-look-numbers-showing-users-leaving-facebook-by-the-millions
  0%|          | 1/267 [00:00<00:55,  4.82it/s]INFO:__main__:Requesting https://www.mercurynews.com/2018/02/27/analysis-trumps-facebook-ad-advantage-explained/
INFO:__main__:Getting metadata for https://www.mercurynews.com/2018/02/27/analysis-trumps-facebook-ad-advantage-explained/
  1%|          | 2/267 [00:01<02:08,  2.07it/s]INFO:__main__:Requesting https://www.nytimes.com/2019/01/25/technology/facebook-instagram-whatsapp-messenger.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2019/01/25/technology/facebook-instagram-whatsapp-messenger.html
  1%|          | 3/267 [00:01<01:49,  2.42it/s]INFO:__main__:Requesting https://mashable.com/article/mark-zuckerberg-speaks-on-whatsapp-instagram-messenger-merger/
INFO:__main__:Getting metadata for https://mashable.com/article/mark-zuckerberg-speaks-on-whatsapp-instagram-messenger-merger/
  1%|▏         | 4/267 [00:02<03:03,  1.43it/s]INFO:__main__:Requesting https://www.instagram.com
INFO:__main__:Getting metadata for https://www.instagram.com
  2%|▏         | 5/267 [00:03<02:32,  1.72it/s]INFO:__main__:Requesting https://trends.google.com/trends/explore?date=all&geo=GB&q=facebook,instagram,whatsapp,myspace,snapchat
  2%|▏         | 6/267 [00:03<02:03,  2.11it/s]INFO:__main__:Requesting https://iandanielstewart.com/2017/06/16/the-golden-age-fallacy/
ERROR:__main__:Could not reach https://iandanielstewart.com/2017/06/16/the-golden-age-fallacy/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
  3%|▎         | 7/267 [00:03<01:40,  2.60it/s]INFO:__main__:Requesting https://www.forbes.com/sites/brucerogers/2019/01/18/will-it-take-an-adtech-crash-to-end-digital-ad-fraud/#a9232991368d
INFO:__main__:Getting metadata for https://www.forbes.com/sites/brucerogers/2019/01/18/will-it-take-an-adtech-crash-to-end-digital-ad-fraud/#a9232991368d
  3%|▎         | 8/267 [00:04<02:26,  1.77it/s]INFO:__main__:Requesting https://www.edisonresearch.com/infinite-dial-2019/
INFO:__main__:Getting metadata for https://www.edisonresearch.com/infinite-dial-2019/
  3%|▎         | 9/267 [00:04<01:54,  2.25it/s]INFO:__main__:Requesting https://www.slideshare.net/webby2001/infinite-dial-2019
INFO:__main__:Getting metadata for https://www.slideshare.net/webby2001/infinite-dial-2019
  4%|▎         | 10/267 [00:06<03:17,  1.30it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Facebook%E2%80%93Cambridge_Analytica_data_scandal#Use_of_the_data
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Facebook%E2%80%93Cambridge_Analytica_data_scandal#Use_of_the_data
  4%|▍         | 11/267 [00:07<03:54,  1.09it/s]INFO:__main__:Requesting https://www.facebook.com/help/212802592074644?helpref=faq_content
INFO:__main__:Getting metadata for https://www.facebook.com/help/212802592074644?helpref=faq_content
  4%|▍         | 12/267 [00:09<05:48,  1.37s/it]INFO:__main__:Requesting https://youtu.be/70QwQ5kgxzk?t=33
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=70QwQ5kgxzk&feature=youtu.be&t=33
  5%|▍         | 13/267 [00:11<05:19,  1.26s/it]INFO:__main__:Requesting https://www.eugenewei.com/blog/2019/2/19/status-as-a-service
INFO:__main__:Getting metadata for https://www.eugenewei.com/blog/2019/2/19/status-as-a-service
  5%|▌         | 14/267 [00:11<04:41,  1.11s/it]INFO:__main__:Requesting https://www.fastcompany.com/90316249/report-facebook-has-lost-15-million-u-s-users-since-2017
INFO:__main__:Getting metadata for https://www.fastcompany.com/90316249/report-facebook-has-lost-15-million-u-s-users-since-2017
  6%|▌         | 15/267 [00:12<03:41,  1.14it/s]INFO:__main__:Requesting https://youtu.be/_mP9OmOFxc4
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=_mP9OmOFxc4&feature=youtu.be
  6%|▌         | 16/267 [00:13<03:48,  1.10it/s]INFO:__main__:Requesting https://www.statista.com/statistics/264810/number-of-monthly-active-facebook-users-worldwide/
INFO:__main__:Getting metadata for https://www.statista.com/statistics/264810/number-of-monthly-active-facebook-users-worldwide/
  6%|▋         | 17/267 [00:13<03:28,  1.20it/s]INFO:__main__:Requesting https://www.zdnet.com/article/firefox-to-add-tor-browser-anti-fingerprinting-technique-called-letterboxing/
INFO:__main__:Getting metadata for https://www.zdnet.com/article/firefox-to-add-tor-browser-anti-fingerprinting-technique-called-letterboxing/
  7%|▋         | 18/267 [00:14<03:16,  1.27it/s]INFO:__main__:Requesting https://chromium.googlesource.com/chromium/src/+/master/docs/security/faq.md#Why-isnt-passive-browser-fingerprinting-including-passive-cookies_in-Chromes-threat-model
INFO:__main__:Getting metadata for https://chromium.googlesource.com/chromium/src/+/master/docs/security/faq.md#Why-isnt-passive-browser-fingerprinting-including-passive-cookies_in-Chromes-threat-model
  7%|▋         | 19/267 [00:15<03:19,  1.24it/s]INFO:__main__:Requesting https://youtu.be/zGW7TRtcDeQ?t=89
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=zGW7TRtcDeQ&feature=youtu.be&t=89
  7%|▋         | 20/267 [00:16<03:29,  1.18it/s]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=1369357
  8%|▊         | 21/267 [00:16<02:51,  1.43it/s]INFO:__main__:Requesting https://thehackernews.com/2017/10/canvas-browser-fingerprint-blocker.html
INFO:__main__:Getting metadata for https://thehackernews.com/2017/10/canvas-browser-fingerprint-blocker.html
  8%|▊         | 22/267 [00:17<02:37,  1.56it/s]INFO:__main__:Requesting https://www.torproject.org/projects/torbrowser/design/
INFO:__main__:Getting metadata for https://www.torproject.org/projects/torbrowser/design/
  9%|▊         | 23/267 [00:21<06:48,  1.67s/it]INFO:__main__:Requesting https://gitweb.torproject.org/tor-browser.git/commit/?h=tor-browser-52.5.2esr-7.0-2&id=196354d7951a48b4e6f5309d2a8e46962fff9d5f
INFO:__main__:Getting metadata for https://gitweb.torproject.org/tor-browser.git/commit/?h=tor-browser-52.5.2esr-7.0-2&id=196354d7951a48b4e6f5309d2a8e46962fff9d5f
  9%|▉         | 24/267 [00:24<08:53,  2.20s/it]INFO:__main__:Requesting https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API
INFO:__main__:Getting metadata for https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API
  9%|▉         | 25/267 [00:25<06:49,  1.69s/it]INFO:__main__:Requesting https://xkcd.com/1172/
INFO:__main__:Getting metadata for https://xkcd.com/1172/
 10%|▉         | 26/267 [00:25<05:15,  1.31s/it]INFO:__main__:Requesting https://www.wsj.com/articles/chinese-hackers-target-universities-in-pursuit-of-maritime-military-secrets-11551781800
INFO:__main__:Getting metadata for https://www.wsj.com/articles/chinese-hackers-target-universities-in-pursuit-of-maritime-military-secrets-11551781800
 10%|█         | 27/267 [00:26<04:32,  1.14s/it]INFO:__main__:Requesting https://madsciblog.tradoc.army.mil
ERROR:__main__:Could not reach https://madsciblog.tradoc.army.mil
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='madsciblog.tradoc.army.mil', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='madsciblog.tradoc.army.mil', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
 10%|█         | 28/267 [00:26<03:34,  1.11it/s]INFO:__main__:Requesting https://nakedsecurity.sophos.com/2019/03/06/serious-chrome-zero-day-google-says-update-right-this-minute/
ERROR:__main__:Could not reach https://nakedsecurity.sophos.com/2019/03/06/serious-chrome-zero-day-google-says-update-right-this-minute/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 11%|█         | 29/267 [00:26<02:43,  1.46it/s]INFO:__main__:Requesting https://github.com/kyren/luster
INFO:__main__:Getting metadata for https://github.com/kyren/luster
 11%|█         | 30/267 [00:27<03:00,  1.31it/s]INFO:__main__:Requesting https://github.com/withoutboats/shifgrethor
INFO:__main__:Getting metadata for https://github.com/withoutboats/shifgrethor
 12%|█▏        | 31/267 [00:29<03:47,  1.04it/s]INFO:__main__:Requesting https://github.com/asajeffrey/josephine
INFO:__main__:Getting metadata for https://github.com/asajeffrey/josephine
 12%|█▏        | 32/267 [00:30<04:01,  1.03s/it]INFO:__main__:Requesting https://nvd.nist.gov/vuln/detail/CVE-2019-0546
INFO:__main__:Getting metadata for https://nvd.nist.gov/vuln/detail/CVE-2019-0546
 12%|█▏        | 33/267 [00:33<05:56,  1.52s/it]INFO:__main__:Requesting https://www.thezdi.com/blog/2019/2/28/finding-unicorns-when-the-c-compiler-writes-the-vuln
INFO:__main__:Getting metadata for https://www.thezdi.com/blog/2019/2/28/finding-unicorns-when-the-c-compiler-writes-the-vuln
 13%|█▎        | 34/267 [00:33<04:46,  1.23s/it]INFO:__main__:Requesting https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0546
INFO:__main__:Getting metadata for https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0546
ERROR:__main__:Could not get metadata for https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0546
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 132, in __init__
    self._set_properties()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 152, in _set_properties
    if property_meta and property_meta['content'] != "":
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/bs4/element.py", line 1016, in __getitem__
    return self.attrs[key]
KeyError: 'content'
 13%|█▎        | 35/267 [00:34<03:58,  1.03s/it]INFO:__main__:Requesting https://github.com/duneroadrunner/SaferCPlusPlus
INFO:__main__:Getting metadata for https://github.com/duneroadrunner/SaferCPlusPlus
 13%|█▎        | 36/267 [00:35<04:28,  1.16s/it]INFO:__main__:Requesting https://github.com/duneroadrunner/SaferCPlusPlus#registered-pointers
INFO:__main__:Getting metadata for https://github.com/duneroadrunner/SaferCPlusPlus#registered-pointers
 14%|█▍        | 37/267 [00:36<04:44,  1.24s/it]INFO:__main__:Requesting https://github.com/duneroadrunner/SaferCPlusPlus#norad-pointers
INFO:__main__:Getting metadata for https://github.com/duneroadrunner/SaferCPlusPlus#norad-pointers
 14%|█▍        | 38/267 [00:38<04:58,  1.30s/it]INFO:__main__:Requesting https://github.com/duneroadrunner/SaferCPlusPlus#scope-pointers
INFO:__main__:Getting metadata for https://github.com/duneroadrunner/SaferCPlusPlus#scope-pointers
 15%|█▍        | 39/267 [00:39<05:01,  1.32s/it]INFO:__main__:Requesting https://github.com/duneroadrunner/SaferCPlusPlus-BenchmarksGame
INFO:__main__:Getting metadata for https://github.com/duneroadrunner/SaferCPlusPlus-BenchmarksGame
 15%|█▍        | 40/267 [00:40<04:30,  1.19s/it]INFO:__main__:Requesting https://github.com/GrrrDog/Java-Deserialization-Cheat-Sheet
INFO:__main__:Getting metadata for https://github.com/GrrrDog/Java-Deserialization-Cheat-Sheet
 15%|█▌        | 41/267 [00:41<04:07,  1.09s/it]INFO:__main__:Requesting https://nvd.nist.gov/vuln/detail/CVE-2018-4939
INFO:__main__:Getting metadata for https://nvd.nist.gov/vuln/detail/CVE-2018-4939
 16%|█▌        | 42/267 [00:44<05:40,  1.51s/it]INFO:__main__:Requesting https://twitter.com/justinschuh/status/1103087046661267456
INFO:__main__:Getting metadata for https://twitter.com/justinschuh/status/1103087046661267456
 16%|█▌        | 43/267 [00:44<04:50,  1.30s/it]INFO:__main__:Requesting https://chromereleases.googleblog.com/2019/03/stable-channel-update-for-desktop.html
INFO:__main__:Getting metadata for https://chromereleases.googleblog.com/2019/03/stable-channel-update-for-desktop.html
 16%|█▋        | 44/267 [00:45<03:40,  1.01it/s]INFO:__main__:Requesting https://github.com/chromium/chromium/commit/ba9748e78ec7e9c0d594e7edf7b2c07ea2a90449
INFO:__main__:Getting metadata for https://github.com/chromium/chromium/commit/ba9748e78ec7e9c0d594e7edf7b2c07ea2a90449
 17%|█▋        | 45/267 [00:46<03:49,  1.03s/it]INFO:__main__:Requesting https://github.com/chromium/chromium/blob/ba9748e78ec7e9c0d594e7edf7b2c07ea2a90449/third_party/blink/renderer/platform/wtf/typed_arrays/array_buffer_builder.h#L63-L67
INFO:__main__:Getting metadata for https://github.com/chromium/chromium/blob/ba9748e78ec7e9c0d594e7edf7b2c07ea2a90449/third_party/blink/renderer/platform/wtf/typed_arrays/array_buffer_builder.h#L63-L67
 17%|█▋        | 46/267 [00:47<03:33,  1.04it/s]INFO:__main__:Requesting https://bugs.chromium.org/p/chromium/issues/detail?id=936448
INFO:__main__:Getting metadata for https://accounts.google.com/ServiceLogin?service=ah&passive=true&continue=https://appengine.google.com/_ah/conflogin%3Fcontinue%3Dhttps://bugs.chromium.org/p/chromium/issues/detail%253Fid%253D936448
 18%|█▊        | 47/267 [00:48<03:48,  1.04s/it]INFO:__main__:Requesting https://memegenerator.net/img/instances/67508702/look-at-me-im-helping.jpg
INFO:__main__:Getting metadata for https://memegenerator.net/img/instances/67508702/look-at-me-im-helping.jpg
 18%|█▊        | 48/267 [01:02<18:23,  5.04s/it]INFO:__main__:Requesting https://developer.mozilla.org/en-US/docs/Web/API/FileReader
INFO:__main__:Getting metadata for https://developer.mozilla.org/en-US/docs/Web/API/FileReader
 18%|█▊        | 49/267 [01:03<13:16,  3.65s/it]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=1506992
 19%|█▊        | 50/267 [01:03<09:31,  2.63s/it]INFO:__main__:Requesting https://blog.edgespot.io/2019/02/edgespot-detects-pdf-zero-day-samples.html
INFO:__main__:Getting metadata for https://blog.edgespot.io/2019/02/edgespot-detects-pdf-zero-day-samples.html
 19%|█▉        | 51/267 [01:03<06:57,  1.93s/it]INFO:__main__:Requesting https://www.businessinsider.com/crypto-ceo-died-with-passwords-to-137-million-but-the-money-is-gone-2019-3
INFO:__main__:Getting metadata for https://markets.businessinsider.com/currencies/news/crypto-ceo-died-with-passwords-to-137-million-but-the-money-is-gone-2019-3-1028009684
 19%|█▉        | 52/267 [01:04<05:34,  1.55s/it]INFO:__main__:Requesting https://pbs.twimg.com/media/DOjLuy7VoAATprU.jpg
INFO:__main__:Getting metadata for https://pbs.twimg.com/media/DOjLuy7VoAATprU.jpg
 20%|█▉        | 53/267 [01:10<10:35,  2.97s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=JbKMdhpwbaw
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=JbKMdhpwbaw
 20%|██        | 54/267 [01:11<08:23,  2.36s/it]INFO:__main__:Requesting https://amycastor.com/2019/03/01/diving-into-wb21-the-company-holding-9-million-of-quadriga-money/
ERROR:__main__:Could not reach https://amycastor.com/2019/03/01/diving-into-wb21-the-company-holding-9-million-of-quadriga-money/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 21%|██        | 55/267 [01:11<06:01,  1.70s/it]INFO:__main__:Requesting https://www.scamcities.com/scam-city-season-1-episode-6-new-delhi/
INFO:__main__:Getting metadata for https://www.scamcities.com/scam-city-season-1-episode-6-new-delhi/
 21%|██        | 56/267 [01:13<06:20,  1.80s/it]INFO:__main__:Requesting https://darknetdiaries.com/episode/9/
INFO:__main__:Getting metadata for https://darknetdiaries.com/episode/9/
 21%|██▏       | 57/267 [01:13<04:40,  1.34s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=QB0OQae4fWo
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=QB0OQae4fWo
 22%|██▏       | 58/267 [01:14<04:18,  1.24s/it]INFO:__main__:Requesting https://www.reddit.com/r/ethereum/comments/6ettq5/statement_on_quadrigacx_ether_contract_error/
INFO:__main__:Getting metadata for https://www.reddit.com/r/ethereum/comments/6ettq5/statement_on_quadrigacx_ether_contract_error/
 22%|██▏       | 59/267 [01:17<05:43,  1.65s/it]INFO:__main__:Requesting https://www.reddit.com/r/ethereum/comments/6er78h/warning_do_not_use_safeconditionalhftransfer_or/
INFO:__main__:Getting metadata for https://www.reddit.com/r/ethereum/comments/6er78h/warning_do_not_use_safeconditionalhftransfer_or/
 22%|██▏       | 60/267 [01:18<05:10,  1.50s/it]INFO:__main__:Requesting https://www.theglobeandmail.com/business/article-quadriga-co-founder-served-time-in-us-for-role-in-identity-theft/
INFO:__main__:Getting metadata for https://www.theglobeandmail.com/business/article-quadriga-co-founder-served-time-in-us-for-role-in-identity-theft/
 23%|██▎       | 61/267 [01:19<04:35,  1.34s/it]INFO:__main__:Requesting https://pastebin.com/572stP0A
INFO:__main__:Getting metadata for https://pastebin.com/572stP0A
 23%|██▎       | 62/267 [01:19<03:28,  1.02s/it]INFO:__main__:Requesting https://documentcentre.eycan.com/Pages/Main.aspx?SID=1445
INFO:__main__:Getting metadata for https://documentcentre.eycan.com/Pages/Main.aspx?SID=1445
 24%|██▎       | 63/267 [01:21<04:03,  1.19s/it]INFO:__main__:Requesting https://www.bbc.co.uk/news/technology-47454528
INFO:__main__:Getting metadata for https://www.bbc.co.uk/news/technology-47454528
 24%|██▍       | 64/267 [01:22<03:56,  1.16s/it]INFO:__main__:Requesting https://en.bitcoin.it/wiki/Transaction
INFO:__main__:Getting metadata for https://en.bitcoin.it/wiki/Transaction
 24%|██▍       | 65/267 [01:23<03:54,  1.16s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/National_Security_Agency#Mission
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/National_Security_Agency#Mission
 25%|██▍       | 66/267 [01:27<06:44,  2.01s/it]INFO:__main__:Requesting https://www.ecosia.org/
INFO:__main__:Getting metadata for https://www.ecosia.org
 25%|██▌       | 67/267 [01:29<05:55,  1.78s/it]INFO:__main__:Requesting https://www.givero.com/
INFO:__main__:Getting metadata for https://www.givero.com
 25%|██▌       | 68/267 [01:30<05:39,  1.71s/it]INFO:__main__:Requesting https://ecosia.zendesk.com/hc/en-us/articles/206153381-Where-do-Ecosia-s-search-results-come-from-
INFO:__main__:Getting metadata for https://ecosia.zendesk.com/hc/en-us/articles/206153381-Where-do-Ecosia-s-search-results-come-from-
 26%|██▌       | 69/267 [01:30<04:17,  1.30s/it]INFO:__main__:Requesting https://victorzhou.com/blog/intro-to-neural-networks/
INFO:__main__:Getting metadata for https://victorzhou.com/blog/intro-to-neural-networks/
 26%|██▌       | 70/267 [01:31<03:44,  1.14s/it]INFO:__main__:Requesting https://repl.it/@vzhou842/An-Introduction-to-Neural-Networks
INFO:__main__:Getting metadata for https://repl.it/@vzhou842/An-Introduction-to-Neural-Networks
 27%|██▋       | 71/267 [01:32<03:41,  1.13s/it]INFO:__main__:Requesting https://repl.it/@pyelias/netlib
INFO:__main__:Getting metadata for https://repl.it/@pyelias/netlib
 27%|██▋       | 72/267 [01:33<03:37,  1.11s/it]INFO:__main__:Requesting https://scratch.mit.edu/
INFO:__main__:Getting metadata for https://scratch.mit.edu
 27%|██▋       | 73/267 [01:34<02:41,  1.20it/s]INFO:__main__:Requesting https://scratch.mit.edu/projects/26682825/
INFO:__main__:Getting metadata for https://scratch.mit.edu/projects/26682825/
 28%|██▊       | 74/267 [01:34<02:10,  1.48it/s]INFO:__main__:Requesting https://scratch.mit.edu/projects/18640517/
INFO:__main__:Getting metadata for https://scratch.mit.edu/projects/18640517/
 28%|██▊       | 75/267 [01:34<01:48,  1.77it/s]INFO:__main__:Requesting https://scrimba.com/g/gneuralnetworks
INFO:__main__:Getting metadata for https://scrimba.com/g/gneuralnetworks
 28%|██▊       | 76/267 [01:35<02:11,  1.46it/s]INFO:__main__:Requesting https://dragan.rocks/articles/19/Deep-Learning-in-Clojure-From-Scratch-to-GPU-0-Why-Bother
INFO:__main__:Getting metadata for https://dragan.rocks/articles/19/Deep-Learning-in-Clojure-From-Scratch-to-GPU-0-Why-Bother
 29%|██▉       | 77/267 [01:36<02:21,  1.34it/s]INFO:__main__:Requesting http://arctrix.com/nas/python/bpnn.py
INFO:__main__:Getting metadata for http://arctrix.com/nas/python/bpnn.py
 29%|██▉       | 78/267 [01:37<02:07,  1.48it/s]INFO:__main__:Requesting https://aws.amazon.com/blogs/aws/sagemaker/
INFO:__main__:Getting metadata for https://aws.amazon.com/blogs/aws/sagemaker/
 30%|██▉       | 79/267 [01:37<02:01,  1.55it/s]INFO:__main__:Requesting https://pytorch.org/docs/stable/autograd.html#numerical-gradient-checking
INFO:__main__:Getting metadata for https://pytorch.org/docs/stable/autograd.html#numerical-gradient-checking
 30%|██▉       | 80/267 [01:38<02:28,  1.26it/s]INFO:__main__:Requesting https://hn.algolia.com/?query=python%20neural%20scratch&sort=byPopularity&prefix&page=0&dateRange=all&type=story
INFO:__main__:Getting metadata for https://hn.algolia.com/?query=python%20neural%20scratch&sort=byPopularity&prefix&page=0&dateRange=all&type=story
 30%|███       | 81/267 [01:39<02:25,  1.28it/s]INFO:__main__:Requesting https://www.coursera.org/specializations/deep-learning
INFO:__main__:Getting metadata for https://www.coursera.org/specializations/deep-learning
 31%|███       | 82/267 [01:41<03:19,  1.08s/it]INFO:__main__:Requesting https://iamtrask.github.io/2015/07/27/python-network-part2/
INFO:__main__:Getting metadata for https://iamtrask.github.io/2015/07/27/python-network-part2/
 31%|███       | 83/267 [01:41<02:48,  1.09it/s]INFO:__main__:Requesting https://cupy.chainer.org/
INFO:__main__:Getting metadata for https://cupy.chainer.org
 31%|███▏      | 84/267 [01:42<02:10,  1.40it/s]INFO:__main__:Requesting https://gist.github.com/macournoyer/620a8ba4a2ecd6d6feaf
INFO:__main__:Getting metadata for https://gist.github.com/macournoyer/620a8ba4a2ecd6d6feaf
 32%|███▏      | 85/267 [01:42<02:12,  1.37it/s]INFO:__main__:Requesting https://github.com/siekmanj/sieknet
INFO:__main__:Getting metadata for https://github.com/siekmanj/sieknet
 32%|███▏      | 86/267 [01:43<02:16,  1.33it/s]INFO:__main__:Requesting https://pytorch.org/tutorials/beginner/pytorch_with_examples.html
INFO:__main__:Getting metadata for https://pytorch.org/tutorials/beginner/pytorch_with_examples.html
 33%|███▎      | 87/267 [01:44<02:46,  1.08it/s]INFO:__main__:Requesting https://www.coursera.org/learn/machine-learning
INFO:__main__:Getting metadata for https://www.coursera.org/learn/machine-learning
 33%|███▎      | 88/267 [01:50<06:45,  2.26s/it]INFO:__main__:Requesting https://blog.davidsingleton.org/nnrccar/
INFO:__main__:Getting metadata for https://blog.davidsingleton.org/nnrccar/
 33%|███▎      | 89/267 [01:51<05:25,  1.83s/it]INFO:__main__:Requesting https://www.wsj.com/articles/amazon-to-shut-all-u-s-pop-up-stores-as-it-rethinks-physical-retail-strategy-11551902178
INFO:__main__:Getting metadata for https://www.wsj.com/articles/amazon-to-shut-all-u-s-pop-up-stores-as-it-rethinks-physical-retail-strategy-11551902178
 34%|███▎      | 90/267 [01:58<09:56,  3.37s/it]INFO:__main__:Requesting https://www.eater.com/2019/2/27/18243123/whole-foods-365-stores-rip
INFO:__main__:Getting metadata for https://www.eater.com/2019/2/27/18243123/whole-foods-365-stores-rip
 34%|███▍      | 91/267 [01:58<07:18,  2.49s/it]INFO:__main__:Requesting https://blog.aboutamazon.com/company-news/amazon-project-zero
INFO:__main__:Getting metadata for https://blog.aboutamazon.com/company-news/amazon-project-zero
 34%|███▍      | 92/267 [01:58<05:21,  1.84s/it]INFO:__main__:Requesting https://www.wsj.com/articles/amazon-to-launch-new-grocery-store-business-sources-say-11551461887?mod=hp_lead_pos4
INFO:__main__:Getting metadata for https://www.wsj.com/articles/amazon-to-launch-new-grocery-store-business-sources-say-11551461887?mod=hp_lead_pos4
 35%|███▍      | 93/267 [02:01<05:38,  1.94s/it]INFO:__main__:Requesting https://www.theguardian.com/us-news/2019/mar/06/whole-foods-amazon-cuts-minimum-wage-workers-hours-changes
INFO:__main__:Getting metadata for https://www.theguardian.com/us-news/2019/mar/06/whole-foods-amazon-cuts-minimum-wage-workers-hours-changes
 35%|███▌      | 94/267 [02:01<04:13,  1.47s/it]INFO:__main__:Requesting https://outline.com/LXTJCD
INFO:__main__:Getting metadata for https://outline.com/LXTJCD
 36%|███▌      | 95/267 [02:02<03:37,  1.26s/it]INFO:__main__:Requesting http://www.cnbc.com/2019/03/06/amazon-to-close-all-of-its-pop-up-stores-in-the-us.html
INFO:__main__:Getting metadata for https://www.cnbc.com/2019/03/06/amazon-to-close-all-of-its-pop-up-stores-in-the-us.html
 36%|███▌      | 96/267 [02:02<02:49,  1.01it/s]INFO:__main__:Requesting https://www.math3ma.com/blog/matrices-probability-graphs
INFO:__main__:Getting metadata for https://www.math3ma.com/blog/matrices-probability-graphs
 36%|███▋      | 97/267 [02:02<02:14,  1.27it/s]INFO:__main__:Requesting https://graphicallinearalgebra.net
ERROR:__main__:Could not reach https://graphicallinearalgebra.net
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 37%|███▋      | 98/267 [02:03<01:42,  1.65it/s]INFO:__main__:Requesting http://faculty.cse.tamu.edu/davis/GraphBLAS.html
INFO:__main__:Getting metadata for http://faculty.cse.tamu.edu/davis/GraphBLAS.html
 37%|███▋      | 99/267 [02:03<01:29,  1.87it/s]INFO:__main__:Requesting http://graphblas.org
INFO:__main__:Getting metadata for http://graphblas.org/index.php?title=Graph_BLAS_Forum
 37%|███▋      | 100/267 [02:05<03:07,  1.12s/it]INFO:__main__:Requesting https://hn.algolia.com/?query=GraphBLAS&sort=byPopularity&prefix&page=0&dateRange=all&type=all
INFO:__main__:Getting metadata for https://hn.algolia.com/?query=GraphBLAS&sort=byPopularity&prefix&page=0&dateRange=all&type=all
 38%|███▊      | 101/267 [02:06<02:23,  1.16it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Simplicial_complex
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Simplicial_complex
 38%|███▊      | 102/267 [02:07<02:31,  1.09it/s]INFO:__main__:Requesting https://gravitational.com/blog/microservices-containers-kubernetes/
INFO:__main__:Getting metadata for https://gravitational.com/blog/microservices-containers-kubernetes/
 39%|███▊      | 103/267 [02:08<02:27,  1.11it/s]INFO:__main__:Requesting https://xkcd.com/2044/
INFO:__main__:Getting metadata for https://xkcd.com/2044/
 39%|███▉      | 104/267 [02:08<02:00,  1.35it/s]INFO:__main__:Requesting https://docs.architect.io
INFO:__main__:Getting metadata for https://docs.architect.io
 39%|███▉      | 105/267 [02:08<01:45,  1.53it/s]INFO:__main__:Requesting https://github.com/micro/go-micro
INFO:__main__:Getting metadata for https://github.com/micro/go-micro
 40%|███▉      | 106/267 [02:09<02:03,  1.30it/s]INFO:__main__:Requesting https://www.nature.com/articles/s41556-018-0085-4
INFO:__main__:Getting metadata for https://www.nature.com/articles/s41556-018-0085-4
 40%|████      | 107/267 [02:12<03:32,  1.33s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=fUlR9DP6Me4&t=2074s
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=fUlR9DP6Me4&t=2074s
 40%|████      | 108/267 [02:13<03:09,  1.19s/it]INFO:__main__:Requesting https://motherboard.vice.com/en_us/article/gyakgw/the-prototype-dev-fused-iphones-that-hackers-use-to-research-apple-zero-days
INFO:__main__:Getting metadata for https://motherboard.vice.com/en_us/article/gyakgw/the-prototype-dev-fused-iphones-that-hackers-use-to-research-apple-zero-days
 41%|████      | 109/267 [02:13<02:26,  1.08it/s]INFO:__main__:Requesting https://twitter.com/msolnik/status/1103395763068043264
INFO:__main__:Getting metadata for https://twitter.com/msolnik/status/1103395763068043264
 41%|████      | 110/267 [02:14<02:14,  1.16it/s]INFO:__main__:Requesting https://twitter.com/Jin_Store
INFO:__main__:Getting metadata for https://twitter.com/Jin_Store
 42%|████▏     | 111/267 [02:17<04:05,  1.57s/it]INFO:__main__:Requesting https://www.nature.com/articles/s41564-018-0337-x.epdf?referrer_access_token=wrPsThpekvlDIFVfG5LcxNRgN0jAjWel9jnR3ZoTv0Pk-saWPJmzGA3H2wMSXmwWlLgoMIU-QgMdenquoZAoe6NETxnfNGaTyvKBf8sDab0d4o3IEWSDwPMHnxuzB02yxHpGxsrb_BAMi8S1xd9sKTII8ETVXrRjzyawDGyhVDxF3e1s_r1_lufiujI6-hOfoR0i-ws8EVQx2UqY7VLGaMBRs1N-olOmFv8l7zf3HcJYx3fvAbSktPcSgGBlaxr63WkPzfDrnnSyk1Lfje1HUw%3D%3D&tracking_referrer=www.genengnews.com
INFO:__main__:Getting metadata for https://www.nature.com/articles/s41564-018-0337-x.epdf?referrer_access_token=wrPsThpekvlDIFVfG5LcxNRgN0jAjWel9jnR3ZoTv0Pk-saWPJmzGA3H2wMSXmwWlLgoMIU-QgMdenquoZAoe6NETxnfNGaTyvKBf8sDab0d4o3IEWSDwPMHnxuzB02yxHpGxsrb_BAMi8S1xd9sKTII8ETVXrRjzyawDGyhVDxF3e1s_r1_lufiujI6-hOfoR0i-ws8EVQx2UqY7VLGaMBRs1N-olOmFv8l7zf3HcJYx3fvAbSktPcSgGBlaxr63WkPzfDrnnSyk1Lfje1HUw%3D%3D&tracking_referrer=www.genengnews.com
 42%|████▏     | 112/267 [02:20<05:05,  1.97s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=-LUuqxQSaFQ
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=-LUuqxQSaFQ
 42%|████▏     | 113/267 [02:21<04:13,  1.65s/it]INFO:__main__:Requesting http://foodandmoodcentre.com.au/media/smiles-trial/
INFO:__main__:Getting metadata for http://foodandmoodcentre.com.au/media/smiles-trial/
 43%|████▎     | 114/267 [02:24<05:26,  2.14s/it]INFO:__main__:Requesting https://youtu.be/-LUuqxQSaFQ
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=-LUuqxQSaFQ&feature=youtu.be
 43%|████▎     | 115/267 [02:25<04:28,  1.77s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Fecal_microbiota_transplant
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Fecal_microbiota_transplant
 43%|████▎     | 116/267 [02:27<04:15,  1.69s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Clostridioides_difficile_(bacteria)#Treatment
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Clostridioides_difficile_(bacteria)#Treatment
 44%|████▍     | 117/267 [02:28<03:55,  1.57s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4615743/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4615743/
 44%|████▍     | 118/267 [02:29<03:42,  1.50s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4178329/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4178329/
 45%|████▍     | 119/267 [02:30<03:23,  1.37s/it]INFO:__main__:Requesting https://www.sciencedirect.com/science/article/pii/S0960982218304433
INFO:__main__:Getting metadata for https://www.sciencedirect.com/science/article/pii/S0960982218304433
 45%|████▍     | 120/267 [02:31<02:59,  1.22s/it]INFO:__main__:Requesting https://www.nature.com/articles/nature14232
INFO:__main__:Getting metadata for https://www.nature.com/articles/nature14232
 45%|████▌     | 121/267 [02:35<04:46,  1.96s/it]INFO:__main__:Requesting http://www.israelscienceinfo.com/en/medecine/weizmann-israel-bacteries-intestinales-edulcorants-artificiels-intolerance-au-glucose/
INFO:__main__:Getting metadata for http://www.israelscienceinfo.com/en/medecine/weizmann-israel-bacteries-intestinales-edulcorants-artificiels-intolerance-au-glucose/
 46%|████▌     | 122/267 [02:38<05:16,  2.18s/it]INFO:__main__:Requesting https://www.mdpi.com/1420-3049/23/2/367
INFO:__main__:Getting metadata for https://www.mdpi.com/1420-3049/23/2/367
 46%|████▌     | 123/267 [02:39<04:17,  1.79s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pubmed/29902436
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pubmed/29902436
 46%|████▋     | 124/267 [02:42<05:08,  2.16s/it]INFO:__main__:Requesting https://innovixlabs.com/products/mood-probiotic
INFO:__main__:Getting metadata for https://innovixlabs.com/products/mood-probiotic
 47%|████▋     | 125/267 [02:42<04:02,  1.71s/it]INFO:__main__:Requesting https://blogs.windows.com/buildingapps/2019/03/06/updated-microsoft-store-app-developer-agreement-new-revenue-share/
INFO:__main__:Getting metadata for https://blogs.windows.com/buildingapps/2019/03/06/updated-microsoft-store-app-developer-agreement-new-revenue-share/
 47%|████▋     | 126/267 [02:42<02:57,  1.26s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Three-legged_race
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Three-legged_race
 48%|████▊     | 127/267 [02:43<02:33,  1.09s/it]INFO:__main__:Requesting https://www.theverge.com/2013/3/19/4124548/microsoft-paying-developers-cash-for-windows-apps
INFO:__main__:Getting metadata for https://www.theverge.com/2013/3/19/4124548/microsoft-paying-developers-cash-for-windows-apps
 48%|████▊     | 128/267 [02:44<02:06,  1.10it/s]INFO:__main__:Requesting https://www.microsoft.com/en-us/store/new-and-rising/apps/pc
INFO:__main__:Getting metadata for https://www.microsoft.com/en-us/store/new-and-rising/apps/pc
 48%|████▊     | 129/267 [02:46<03:19,  1.44s/it]INFO:__main__:Requesting https://docs.microsoft.com/en-us/windows/uwp/launch-resume/console-uwp
INFO:__main__:Getting metadata for https://docs.microsoft.com/en-us/windows/uwp/launch-resume/console-uwp
 49%|████▊     | 130/267 [02:47<02:37,  1.15s/it]INFO:__main__:Requesting https://getpolarized.io/2019/02/28/dear-app-stores-dont-block-apps-lead-with-the-carrot.html
INFO:__main__:Getting metadata for https://getpolarized.io/2019/02/28/dear-app-stores-dont-block-apps-lead-with-the-carrot.html
 49%|████▉     | 131/267 [02:47<02:03,  1.10it/s]INFO:__main__:Requesting https://electronjs.org/docs/tutorial/windows-store-guide
INFO:__main__:Getting metadata for https://electronjs.org/docs/tutorial/windows-store-guide
 49%|████▉     | 132/267 [02:48<01:45,  1.28it/s]INFO:__main__:Requesting https://github.com/felixrieseberg/electron-windows-store
INFO:__main__:Getting metadata for https://github.com/felixrieseberg/electron-windows-store
 50%|████▉     | 133/267 [02:49<02:13,  1.00it/s]INFO:__main__:Requesting https://cloud.google.com/blog/products/devops-sre/the-service-mesh-era-using-istio-and-stackdriver-to-build-an-sre-service
INFO:__main__:Getting metadata for https://cloud.google.com/blog/products/devops-sre/the-service-mesh-era-using-istio-and-stackdriver-to-build-an-sre-service
 50%|█████     | 134/267 [02:50<01:53,  1.18it/s]INFO:__main__:Requesting https://opencensus.io/introduction/#partners-contributors
INFO:__main__:Getting metadata for https://opencensus.io/introduction/#partners-contributors
 51%|█████     | 135/267 [02:50<01:45,  1.25it/s]INFO:__main__:Requesting https://linkerd.io/2/features/telemetry/
INFO:__main__:Getting metadata for https://linkerd.io/2/features/telemetry/
 51%|█████     | 136/267 [02:51<01:27,  1.50it/s]INFO:__main__:Requesting https://instana.com
INFO:__main__:Getting metadata for https://www.instana.com
 51%|█████▏    | 137/267 [02:53<02:15,  1.05s/it]INFO:__main__:Requesting https://docs.instana.io/core_concepts/tracing/#supported-technologies
INFO:__main__:Getting metadata for https://docs.instana.io/core_concepts/tracing/#supported-technologies
 52%|█████▏    | 138/267 [02:55<03:06,  1.45s/it]INFO:__main__:Requesting https://people.xiph.org/~xiphmont/demo/neil-young.html
INFO:__main__:Getting metadata for https://people.xiph.org/~xiphmont/demo/neil-young.html
 52%|█████▏    | 139/267 [02:57<03:44,  1.76s/it]INFO:__main__:Requesting https://ehomerecordingstudio.com/fletcher-munson-curve/
INFO:__main__:Getting metadata for https://ehomerecordingstudio.com/fletcher-munson-curve/
 52%|█████▏    | 140/267 [02:58<02:52,  1.36s/it]INFO:__main__:Requesting https://www.iconnectivity.com/blog/2017/6/10/ebu-r128-the-important-audio-breakthrough-youve-never-heard-of
INFO:__main__:Getting metadata for https://www.iconnectivity.com/blog/2017/6/10/ebu-r128-the-important-audio-breakthrough-youve-never-heard-of
 53%|█████▎    | 141/267 [02:58<02:21,  1.13s/it]INFO:__main__:Requesting https://wiki.hydrogenaud.io/index.php?title=Myths_(Vinyl)#Myth:_Vinyl_requires_a_better-sounding_master_because_it_is_physically_incapable_of_reproducing_the_hypercompressed_sound_mastered_to_CD
INFO:__main__:Getting metadata for https://wiki.hydrogenaud.io/index.php?title=Myths_(Vinyl)#Myth:_Vinyl_requires_a_better-sounding_master_because_it_is_physically_incapable_of_reproducing_the_hypercompressed_sound_mastered_to_CD
 53%|█████▎    | 142/267 [03:02<04:00,  1.93s/it]INFO:__main__:Requesting https://www.sciencedirect.com/science/article/pii/S0896627312009531
INFO:__main__:Getting metadata for https://www.sciencedirect.com/science/article/pii/S0896627312009531
 54%|█████▎    | 143/267 [03:03<03:18,  1.60s/it]INFO:__main__:Requesting http://www.psych.usyd.edu.au/staff/alexh/teaching/auditoryTute_2014/
INFO:__main__:Getting metadata for http://www.psych.usyd.edu.au/staff/alexh/teaching/auditoryTute_2014/
 54%|█████▍    | 144/267 [03:06<04:08,  2.02s/it]INFO:__main__:Requesting http://www.roger-russell.com/hearing/hearing.htm
INFO:__main__:Getting metadata for http://www.roger-russell.com/hearing/hearing.htm
 54%|█████▍    | 145/267 [03:08<03:47,  1.87s/it]INFO:__main__:Requesting http://personal.cityu.edu.hk/~bsapplec/frequenc.htm
INFO:__main__:Getting metadata for http://personal.cityu.edu.hk/~bsapplec/frequenc.htm
 55%|█████▍    | 146/267 [03:10<04:22,  2.17s/it]INFO:__main__:Requesting https://www.researchgate.net/publication/261767650_Extended_high-frequency_9-20_kHz_audiometry_reference_thresholds_in_645_healthy_subjects
 55%|█████▌    | 147/267 [03:11<03:09,  1.58s/it]INFO:__main__:Requesting https://forums.stevehoffman.tv/threads/the-common-audiophiles-terror-of-compression-limiting.335257/
INFO:__main__:Getting metadata for https://forums.stevehoffman.tv/threads/the-common-audiophiles-terror-of-compression-limiting.335257/
 55%|█████▌    | 148/267 [03:11<02:34,  1.30s/it]INFO:__main__:Requesting http://dr.loudness-war.info
INFO:__main__:Getting metadata for http://dr.loudness-war.info
 56%|█████▌    | 149/267 [03:14<03:18,  1.69s/it]INFO:__main__:Requesting https://wiki.hydrogenaud.io/index.php?title=Myths_(Vinyl)#Effect_of_vinyl_mastering_on_dynamic_range
INFO:__main__:Getting metadata for https://wiki.hydrogenaud.io/index.php?title=Myths_(Vinyl)#Effect_of_vinyl_mastering_on_dynamic_range
 56%|█████▌    | 150/267 [03:17<04:22,  2.24s/it]INFO:__main__:Requesting https://www.androidauthority.com/lg-v20-quad-dac-explained-713587/
INFO:__main__:Getting metadata for https://www.androidauthority.com/lg-v20-quad-dac-explained-713587/
 57%|█████▋    | 151/267 [03:18<03:14,  1.67s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Dual-tone_multi-frequency_signaling
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Dual-tone_multi-frequency_signaling
 57%|█████▋    | 152/267 [03:19<02:50,  1.48s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Presbycusis
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Presbycusis
 57%|█████▋    | 153/267 [03:20<02:31,  1.33s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=MtiRBFWkRKs
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=MtiRBFWkRKs
 58%|█████▊    | 154/267 [03:21<02:13,  1.18s/it]INFO:__main__:Requesting https://trac.ffmpeg.org/wiki/Encode/MP3
INFO:__main__:Getting metadata for https://trac.ffmpeg.org/wiki/Encode/MP3
 58%|█████▊    | 155/267 [03:25<03:46,  2.02s/it]INFO:__main__:Requesting https://trac.ffmpeg.org/wiki/Encode/AAC
INFO:__main__:Getting metadata for https://trac.ffmpeg.org/wiki/Encode/AAC
 58%|█████▊    | 156/267 [03:29<04:55,  2.67s/it]INFO:__main__:Requesting https://abcde.einval.com/wiki/
INFO:__main__:Getting metadata for https://abcde.einval.com/wiki/
 59%|█████▉    | 157/267 [03:35<06:46,  3.69s/it]INFO:__main__:Requesting https://www.clementine-player.org
INFO:__main__:Getting metadata for https://www.clementine-player.org
 59%|█████▉    | 158/267 [03:35<04:55,  2.71s/it]INFO:__main__:Requesting https://cmus.github.io
INFO:__main__:Getting metadata for https://cmus.github.io
 60%|█████▉    | 159/267 [03:36<03:38,  2.02s/it]INFO:__main__:Requesting https://www.reddit.com/r/headphones/comments/awyy1q/this_preamp_reveals_the_dark_side_of_the_hifi/ehr58dz/
INFO:__main__:Getting metadata for https://www.reddit.com/r/headphones/comments/awyy1q/this_preamp_reveals_the_dark_side_of_the_hifi/ehr58dz/
 60%|█████▉    | 160/267 [03:38<03:31,  1.97s/it]INFO:__main__:Requesting https://wallofsound.ca/audioreviews/amplification/review-elekit-tu8600-single-ended-300b-amp-part-1/
INFO:__main__:Getting metadata for https://wallofsound.ca/audioreviews/amplification/review-elekit-tu8600-single-ended-300b-amp-part-1/
 60%|██████    | 161/267 [03:39<03:03,  1.73s/it]INFO:__main__:Requesting https://thevinylfactory.com/features/analogue-digital-vinyl-mastering-interviews/
INFO:__main__:Getting metadata for https://thevinylfactory.com/features/analogue-digital-vinyl-mastering-interviews/
 61%|██████    | 162/267 [03:40<02:47,  1.59s/it]INFO:__main__:Requesting https://xiph.org/video/vid1.shtml
INFO:__main__:Getting metadata for https://xiph.org/video/vid1.shtml
 61%|██████    | 163/267 [03:41<02:31,  1.46s/it]INFO:__main__:Requesting https://xiph.org/video/vid2.shtml
INFO:__main__:Getting metadata for https://xiph.org/video/vid2.shtml
 61%|██████▏   | 164/267 [03:43<02:30,  1.46s/it]INFO:__main__:Requesting https://xiph.org/vorbis/
INFO:__main__:Getting metadata for https://xiph.org/vorbis/
 62%|██████▏   | 165/267 [03:44<02:16,  1.34s/it]INFO:__main__:Requesting http://www.opus-codec.org/comparison/
INFO:__main__:Getting metadata for http://www.opus-codec.org/comparison/
 62%|██████▏   | 166/267 [03:45<02:22,  1.41s/it]INFO:__main__:Requesting https://wiki.xiph.org/OpusFAQ#Does_Opus_make_all_those_other_lossy_codecs_obsolete.3F
INFO:__main__:Getting metadata for https://wiki.xiph.org/OpusFAQ#Does_Opus_make_all_those_other_lossy_codecs_obsolete.3F
 63%|██████▎   | 167/267 [03:48<03:10,  1.90s/it]INFO:__main__:Requesting https://www.tate.org.uk/art/artworks/klein-ikb-79-t01513
INFO:__main__:Getting metadata for https://www.tate.org.uk/art/artworks/klein-ikb-79-t01513
 63%|██████▎   | 168/267 [03:50<02:55,  1.77s/it]INFO:__main__:Requesting https://contemporaryartetc.wordpress.com/2007/09/13/fact-of-the-day-61/
ERROR:__main__:Could not reach https://contemporaryartetc.wordpress.com/2007/09/13/fact-of-the-day-61/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 63%|██████▎   | 169/267 [03:50<02:05,  1.28s/it]INFO:__main__:Requesting https://www.foobar2000.org/components/view/foo_abx
INFO:__main__:Getting metadata for https://www.foobar2000.org/components/view/foo_abx
 64%|██████▎   | 170/267 [03:52<02:34,  1.60s/it]INFO:__main__:Requesting https://www.soundonsound.com/techniques/multi-band-compression-tips
INFO:__main__:Getting metadata for https://www.soundonsound.com/techniques/multi-band-compression-tips
 64%|██████▍   | 171/267 [03:53<02:20,  1.47s/it]INFO:__main__:Requesting https://pitchfork.com/reviews/albums/earl-sweatshirt-some-rap-songs/
INFO:__main__:Getting metadata for https://pitchfork.com/reviews/albums/earl-sweatshirt-some-rap-songs/
 64%|██████▍   | 172/267 [03:54<01:55,  1.21s/it]INFO:__main__:Requesting http://www.noise11.com/news/r-i-p-pono-neil-young-kills-off-his-digital-player-20170423
INFO:__main__:Getting metadata for http://www.noise11.com/news/r-i-p-pono-neil-young-kills-off-his-digital-player-20170423
 65%|██████▍   | 173/267 [03:55<01:35,  1.01s/it]INFO:__main__:Requesting https://tenfourfox.blogspot.com/2015/01/and-now-for-something-completely.html
INFO:__main__:Getting metadata for https://tenfourfox.blogspot.com/2015/01/and-now-for-something-completely.html
 65%|██████▌   | 174/267 [03:55<01:15,  1.24it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=RlCG2fK-abo
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=RlCG2fK-abo
 66%|██████▌   | 175/267 [03:56<01:18,  1.18it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Pono_(digital_music_service)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Pono_(digital_music_service)
 66%|██████▌   | 176/267 [03:57<01:27,  1.04it/s]INFO:__main__:Requesting https://vis.sciencemag.org/eggs/
INFO:__main__:Getting metadata for https://vis.sciencemag.org/eggs/
 66%|██████▋   | 177/267 [03:58<01:12,  1.24it/s]INFO:__main__:Requesting https://privacyinternational.org/blog/2758/guess-what-facebook-still-tracks-you-android-apps-even-if-you-dont-have-facebook-account
INFO:__main__:Getting metadata for https://privacyinternational.org/blog/2758/guess-what-facebook-still-tracks-you-android-apps-even-if-you-dont-have-facebook-account
 67%|██████▋   | 178/267 [03:59<01:26,  1.03it/s]INFO:__main__:Requesting https://gist.github.com/thomasbilk/1506210/2d20f47bbcca75b2f78d6909c1637501000d846f
INFO:__main__:Getting metadata for https://gist.github.com/thomasbilk/1506210/2d20f47bbcca75b2f78d6909c1637501000d846f
 67%|██████▋   | 179/267 [04:00<01:31,  1.04s/it]INFO:__main__:Requesting https://medium.com/message/selling-out-is-meaningless-3450a5bc98d2
INFO:__main__:Getting metadata for https://medium.com/message/selling-out-is-meaningless-3450a5bc98d2
 67%|██████▋   | 180/267 [04:01<01:18,  1.10it/s]INFO:__main__:Requesting https://www.nemil.com/musings/oss-and-slack.html
INFO:__main__:Getting metadata for https://www.nemil.com/musings/oss-and-slack.html
 68%|██████▊   | 181/267 [04:01<01:11,  1.20it/s]INFO:__main__:Requesting https://www.businessinsider.com/china-social-credit-system-punishments-and-rewards-explained-2018-4
INFO:__main__:Getting metadata for https://www.businessinsider.com/china-social-credit-system-punishments-and-rewards-explained-2018-4
 68%|██████▊   | 182/267 [04:02<00:57,  1.48it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/IBM_and_the_Holocaust
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/IBM_and_the_Holocaust
 69%|██████▊   | 183/267 [04:03<01:12,  1.16it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Metcalfe%27s_law
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Metcalfe%27s_law
 69%|██████▉   | 184/267 [04:04<01:15,  1.10it/s]INFO:__main__:Requesting https://privacyinternational.org/appdata
INFO:__main__:Getting metadata for https://privacyinternational.org/appdata
 69%|██████▉   | 185/267 [04:07<02:08,  1.57s/it]INFO:__main__:Requesting https://github.com/jmdugan/blocklists/blob/master/corporations/facebook/all
INFO:__main__:Getting metadata for https://github.com/jmdugan/blocklists/blob/master/corporations/facebook/all
 70%|██████▉   | 186/267 [04:09<02:03,  1.53s/it]INFO:__main__:Requesting https://matomo.org/
INFO:__main__:Getting metadata for https://matomo.org
 70%|███████   | 187/267 [04:10<01:57,  1.47s/it]INFO:__main__:Requesting https://www.forbes.com/sites/kashmirhill/2012/02/16/how-target-figured-out-a-teen-girl-was-pregnant-before-her-father-did/
INFO:__main__:Getting metadata for https://www.forbes.com/sites/kashmirhill/2012/02/16/how-target-figured-out-a-teen-girl-was-pregnant-before-her-father-did/
 70%|███████   | 188/267 [04:10<01:29,  1.13s/it]INFO:__main__:Requesting https://newsroom.fb.com/news/2018/04/data-off-facebook/
ERROR:__main__:Could not reach https://newsroom.fb.com/news/2018/04/data-off-facebook/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 71%|███████   | 189/267 [04:10<01:05,  1.20it/s]INFO:__main__:Requesting https://twitter.com/jeremyburge/status/1101402001907372032
INFO:__main__:Getting metadata for https://twitter.com/jeremyburge/status/1101402001907372032
 71%|███████   | 190/267 [04:12<01:14,  1.03it/s]INFO:__main__:Requesting https://www3.nhk.or.jp/news/easy/
INFO:__main__:Getting metadata for https://www3.nhk.or.jp/news/easy/
 72%|███████▏  | 191/267 [04:12<00:59,  1.27it/s]INFO:__main__:Requesting http://www.guidetojapanese.org/learn/grammar
INFO:__main__:Getting metadata for http://www.guidetojapanese.org/learn/grammar
 72%|███████▏  | 192/267 [04:17<02:33,  2.05s/it]INFO:__main__:Requesting https://www.youtube.com/channel/UCBSyd8tXJoEJKIXfrwkPdbA
INFO:__main__:Getting metadata for https://www.youtube.com/channel/UCBSyd8tXJoEJKIXfrwkPdbA
 72%|███████▏  | 193/267 [04:20<02:57,  2.40s/it]INFO:__main__:Requesting https://www.ankiapp.com/
INFO:__main__:Getting metadata for https://www.ankiapp.com
 73%|███████▎  | 194/267 [04:21<02:13,  1.83s/it]INFO:__main__:Requesting https://foosoft.net/projects/yomichan/
INFO:__main__:Getting metadata for https://foosoft.net/projects/yomichan/
 73%|███████▎  | 195/267 [04:22<01:56,  1.61s/it]INFO:__main__:Requesting https://nhkeasier.com/
INFO:__main__:Getting metadata for https://nhkeasier.com
 73%|███████▎  | 196/267 [04:25<02:22,  2.01s/it]INFO:__main__:Requesting https://dictionary.cambridge.org/grammar/british-grammar/about-adjectives-and-adverbs/adjectives-order
INFO:__main__:Getting metadata for https://dictionary.cambridge.org/grammar/british-grammar/about-adjectives-and-adverbs/adjectives-order
ERROR:__main__:Could not get metadata for https://dictionary.cambridge.org/grammar/british-grammar/about-adjectives-and-adverbs/adjectives-order
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
 74%|███████▍  | 197/267 [04:25<01:48,  1.54s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Programmed_learning
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Programmed_learning
 74%|███████▍  | 198/267 [04:26<01:35,  1.39s/it]INFO:__main__:Requesting https://www.privacymonitor.com
INFO:__main__:Getting metadata for https://www.privacymonitor.com
 75%|███████▍  | 199/267 [04:26<01:10,  1.03s/it]INFO:__main__:Requesting https://media.ccc.de/v/35c3-9941-how_facebook_tracks_you_on_android/
INFO:__main__:Getting metadata for https://media.ccc.de/v/35c3-9941-how_facebook_tracks_you_on_android/
 75%|███████▍  | 200/267 [04:28<01:21,  1.21s/it]INFO:__main__:Requesting https://www.gnu.org/philosophy/ubuntu-spyware.en.html
INFO:__main__:Getting metadata for https://www.gnu.org/philosophy/ubuntu-spyware.en.html
 75%|███████▌  | 201/267 [04:29<01:20,  1.22s/it]INFO:__main__:Requesting https://mspoweruser.com/microsoft-makes-telemetry-updates-for-windows-7-and-8-1-critical-updates/
INFO:__main__:Getting metadata for https://mspoweruser.com/microsoft-makes-telemetry-updates-for-windows-7-and-8-1-critical-updates/
 76%|███████▌  | 202/267 [04:30<01:01,  1.05it/s]INFO:__main__:Requesting https://www.howtogeek.com/269331/how-to-disable-all-of-windows-10s-built-in-advertising/
INFO:__main__:Getting metadata for https://www.howtogeek.com/269331/how-to-disable-all-of-windows-10s-built-in-advertising/
 76%|███████▌  | 203/267 [04:30<00:46,  1.36it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/BonziBuddy
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/BonziBuddy
 76%|███████▋  | 204/267 [04:31<00:47,  1.32it/s]INFO:__main__:Requesting https://news.ycombinator.com/newsguidelines.html
INFO:__main__:Getting metadata for https://news.ycombinator.com/newsguidelines.html
 77%|███████▋  | 205/267 [04:32<00:53,  1.16it/s]INFO:__main__:Requesting https://web-in-security.blogspot.com/2019/02/how-to-spoof-pdf-signatures.html
INFO:__main__:Getting metadata for https://web-in-security.blogspot.com/2019/02/how-to-spoof-pdf-signatures.html
 77%|███████▋  | 206/267 [04:32<00:43,  1.42it/s]INFO:__main__:Requesting https://helpx.adobe.com/acrobat/using/certificate-based-signatures.html#certifying_and_signing_documents
INFO:__main__:Getting metadata for https://helpx.adobe.com/acrobat/using/certificate-based-signatures.html#certifying_and_signing_documents
 78%|███████▊  | 207/267 [04:33<00:53,  1.11it/s]INFO:__main__:Requesting https://ec.europa.eu/digital-single-market/en/eu-trusted-lists-trust-service-providers
INFO:__main__:Getting metadata for https://ec.europa.eu/digital-single-market/en/eu-trusted-lists-trust-service-providers
 78%|███████▊  | 208/267 [04:38<01:51,  1.90s/it]INFO:__main__:Requesting https://www.pdf-insecurity.org/signature/viewer.html
INFO:__main__:Getting metadata for https://www.pdf-insecurity.org/signature/viewer.html
 78%|███████▊  | 209/267 [04:41<02:15,  2.33s/it]INFO:__main__:Requesting https://getpolarized.io/
INFO:__main__:Getting metadata for https://getpolarized.io
 79%|███████▊  | 210/267 [04:41<01:35,  1.67s/it]INFO:__main__:Requesting https://github.com/corkami/collisions
INFO:__main__:Getting metadata for https://github.com/corkami/collisions
 79%|███████▉  | 211/267 [04:42<01:22,  1.47s/it]INFO:__main__:Requesting https://www.newcriterion.com/issues/2019/3/the-greatest-of-all-novels
INFO:__main__:Getting metadata for https://www.newcriterion.com/issues/2019/3/the-greatest-of-all-novels
 79%|███████▉  | 212/267 [04:43<01:15,  1.37s/it]INFO:__main__:Requesting https://www.gutenberg.org/ebooks/2600
INFO:__main__:Getting metadata for https://www.gutenberg.org/ebooks/2600
 80%|███████▉  | 213/267 [04:44<00:59,  1.10s/it]INFO:__main__:Requesting https://groups.google.com/forum/#!topic/standardebooks/kBnEDrDIH2k
INFO:__main__:Getting metadata for https://groups.google.com/forum/#!topic/standardebooks/kBnEDrDIH2k
 80%|████████  | 214/267 [04:45<00:56,  1.07s/it]INFO:__main__:Requesting https://mosaicmagazine.com/observation/2015/03/how-lev-tolstoy-became-leo-tolstoy/
INFO:__main__:Getting metadata for https://mosaicmagazine.com/observation/2015/03/how-lev-tolstoy-became-leo-tolstoy/
 81%|████████  | 215/267 [04:46<01:01,  1.18s/it]INFO:__main__:Requesting http://gramota.ru/lenta/news/8_784
INFO:__main__:Getting metadata for http://gramota.ru/lenta/news/8_784
 81%|████████  | 216/267 [04:48<01:09,  1.37s/it]INFO:__main__:Requesting https://www.google.com/search?q=largest+country+on+earth
INFO:__main__:Getting metadata for https://www.google.com/search?q=largest+country+on+earth
 81%|████████▏ | 217/267 [04:52<01:40,  2.02s/it]INFO:__main__:Requesting https://www.forbes.com/sites/kalevleetaru/2019/02/17/the-big-data-revolution-will-be-sampled-how-big-data-has-come-to-mean-small-sampled-data/
INFO:__main__:Getting metadata for https://www.forbes.com/sites/kalevleetaru/2019/02/17/the-big-data-revolution-will-be-sampled-how-big-data-has-come-to-mean-small-sampled-data/
 82%|████████▏ | 218/267 [04:52<01:14,  1.53s/it]INFO:__main__:Requesting http://cslibrary.stanford.edu/109/TreeListRecursion.html
INFO:__main__:Getting metadata for http://cslibrary.stanford.edu/109/TreeListRecursion.html
 82%|████████▏ | 219/267 [04:53<00:59,  1.24s/it]INFO:__main__:Requesting https://stackoverflow.com/questions/7540546/merging-2-binary-search-trees
INFO:__main__:Getting metadata for https://stackoverflow.com/questions/7540546/merging-2-binary-search-trees
 82%|████████▏ | 220/267 [04:53<00:45,  1.03it/s]INFO:__main__:Requesting https://leetcode.com/problems/convert-binary-search-tree-to-sorted-doubly-linked-list/
INFO:__main__:Getting metadata for https://leetcode.com/accounts/login/?next=/problems/convert-binary-search-tree-to-sorted-doubly-linked-list/
 83%|████████▎ | 221/267 [04:54<00:44,  1.03it/s]INFO:__main__:Requesting https://nebelwelt.net/blog/20190306-SMoTherSpectre.html
INFO:__main__:Getting metadata for https://nebelwelt.net/blog/20190306-SMoTherSpectre.html
 83%|████████▎ | 222/267 [04:56<01:03,  1.42s/it]INFO:__main__:Requesting https://quickchart.io/
INFO:__main__:Getting metadata for https://quickchart.io
 84%|████████▎ | 223/267 [04:57<00:48,  1.11s/it]INFO:__main__:Requesting https://github.com/typpo/quickchart
INFO:__main__:Getting metadata for https://github.com/typpo/quickchart
 84%|████████▍ | 224/267 [04:57<00:42,  1.01it/s]INFO:__main__:Requesting https://groups.google.com/forum/#!topic/google-chart-api/rZtHTyYgyXI
INFO:__main__:Getting metadata for https://groups.google.com/forum/#!topic/google-chart-api/rZtHTyYgyXI
 84%|████████▍ | 225/267 [04:58<00:41,  1.00it/s]INFO:__main__:Requesting https://www.fontshop.com/families/ff-chartwell
INFO:__main__:Getting metadata for https://www.fontshop.com/families/ff-chartwell
 85%|████████▍ | 226/267 [05:01<01:05,  1.59s/it]INFO:__main__:Requesting https://vimeo.com/41772735
INFO:__main__:Requesting https://api.restcharts.com/
INFO:__main__:Getting metadata for https://api.restcharts.com
 85%|████████▌ | 228/267 [05:04<00:59,  1.53s/it]INFO:__main__:Requesting https://github.com/whatl3y/restcharts
INFO:__main__:Getting metadata for https://github.com/whatl3y/restcharts
 86%|████████▌ | 229/267 [05:05<00:50,  1.32s/it]INFO:__main__:Requesting https://charturl.com/
INFO:__main__:Getting metadata for https://charturl.com
 86%|████████▌ | 230/267 [05:05<00:38,  1.05s/it]INFO:__main__:Requesting https://vega.github.io/vega/
INFO:__main__:Getting metadata for https://vega.github.io/vega/
 87%|████████▋ | 231/267 [05:06<00:28,  1.27it/s]INFO:__main__:Requesting http://chartd.co
INFO:__main__:Getting metadata for http://chartd.co
 87%|████████▋ | 232/267 [05:06<00:26,  1.32it/s]INFO:__main__:Requesting https://charturl.com
INFO:__main__:Getting metadata for https://charturl.com
 87%|████████▋ | 233/267 [05:07<00:21,  1.57it/s]INFO:__main__:Requesting https://github.com/fiatjaf/awesome-loginless
INFO:__main__:Getting metadata for https://github.com/fiatjaf/awesome-loginless
 88%|████████▊ | 234/267 [05:08<00:23,  1.41it/s]INFO:__main__:Requesting https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers
INFO:__main__:Getting metadata for https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers
 88%|████████▊ | 235/267 [05:08<00:20,  1.60it/s]INFO:__main__:Requesting http://web.archive.org/web/20170201170400/http://chartspree.io/
ERROR:__main__:Could not reach http://web.archive.org/web/20170201170400/http://chartspree.io/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7eff488ce4a8>, 'Connection to web.archive.org timed out. (connect timeout=6)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='web.archive.org', port=80): Max retries exceeded with url: /web/20170201170400/http://chartspree.io/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff488ce4a8>, 'Connection to web.archive.org timed out. (connect timeout=6)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='web.archive.org', port=80): Max retries exceeded with url: /web/20170201170400/http://chartspree.io/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eff488ce4a8>, 'Connection to web.archive.org timed out. (connect timeout=6)'))
 88%|████████▊ | 236/267 [05:14<01:09,  2.25s/it]INFO:__main__:Requesting https://arstechnica.com/tech-policy/2019/03/nsas-top-policy-advisor-its-time-to-start-putting-teeth-in-cyber-deterrence/
INFO:__main__:Getting metadata for https://arstechnica.com/tech-policy/2019/03/nsas-top-policy-advisor-its-time-to-start-putting-teeth-in-cyber-deterrence/
 89%|████████▉ | 237/267 [05:14<00:48,  1.63s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/NSAKEY
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/NSAKEY
 89%|████████▉ | 238/267 [05:15<00:42,  1.48s/it]INFO:__main__:Requesting https://www.csoonline.com/article/3218104/what-is-stuxnet-who-created-it-and-how-does-it-work.html
INFO:__main__:Getting metadata for https://www.csoonline.com/article/3218104/what-is-stuxnet-who-created-it-and-how-does-it-work.html
 90%|████████▉ | 239/267 [05:16<00:31,  1.12s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/The_Shadow_Brokers
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/The_Shadow_Brokers
 90%|████████▉ | 240/267 [05:17<00:31,  1.16s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Atomic_spies#Notable_spies
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Atomic_spies#Notable_spies
 90%|█████████ | 241/267 [05:18<00:29,  1.12s/it]INFO:__main__:Requesting https://www.nsa.gov/News-Features/News-Stories/Article-View/Article/1775584/ghidra-the-software-reverse-engineering-tool-youve-been-waiting-for-is-here/
INFO:__main__:Getting metadata for https://www.nsa.gov/News-Features/News-Stories/Article-View/Article/1775584/ghidra-the-software-reverse-engineering-tool-youve-been-waiting-for-is-here/
 91%|█████████ | 242/267 [05:18<00:23,  1.07it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Security-Enhanced_Linux
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Security-Enhanced_Linux
 91%|█████████ | 243/267 [05:19<00:23,  1.04it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/NSA_Suite_B_Cryptography
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/NSA_Suite_B_Cryptography
 91%|█████████▏| 244/267 [05:20<00:20,  1.13it/s]INFO:__main__:Requesting https://hn.algolia.com/?query=by:dang%20community%20identity&sort=byDate&dateRange=all&type=comment&storyText=false&prefix&page=0
INFO:__main__:Getting metadata for https://hn.algolia.com/?query=by:dang%20community%20identity&sort=byDate&dateRange=all&type=comment&storyText=false&prefix&page=0
 92%|█████████▏| 245/267 [05:21<00:17,  1.27it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Economy_of_Russia
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Economy_of_Russia
 92%|█████████▏| 246/267 [05:24<00:31,  1.49s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Comparison_between_U.S._states_and_sovereign_states_by_GDP_(nominal)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Comparison_between_U.S._states_and_sovereign_states_by_GDP_(nominal)
 93%|█████████▎| 247/267 [05:26<00:33,  1.67s/it]INFO:__main__:Requesting https://www.statista.com/topics/3521/public-relations/
INFO:__main__:Getting metadata for https://www.statista.com/topics/3521/public-relations/
 93%|█████████▎| 248/267 [05:27<00:26,  1.40s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Russia_national_basketball_team
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Russia_national_basketball_team
 93%|█████████▎| 249/267 [05:28<00:26,  1.50s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/1992_United_States_men%27s_Olympic_basketball_team
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/1992_United_States_men%27s_Olympic_basketball_team
 94%|█████████▎| 250/267 [05:30<00:28,  1.68s/it]INFO:__main__:Requesting https://medium.com/waymo/bringing-3d-perimeter-lidar-to-partners-6beaa7d3dcc2
INFO:__main__:Getting metadata for https://medium.com/waymo/bringing-3d-perimeter-lidar-to-partners-6beaa7d3dcc2
 94%|█████████▍| 251/267 [05:31<00:21,  1.32s/it]INFO:__main__:Requesting https://becomeautonomous.com
INFO:__main__:Getting metadata for https://becomeautonomous.com
 94%|█████████▍| 252/267 [05:31<00:15,  1.05s/it]INFO:__main__:Requesting https://www.continental-automotive.com/en-gl/Landing-Pages/CAD/Automated-Driving/GlobalHighlights/3D-Flash-Lidar
INFO:__main__:Getting metadata for https://www.continental-automotive.com/en-gl/Landing-Pages/CAD/Automated-Driving/GlobalHighlights/3D-Flash-Lidar
 95%|█████████▍| 253/267 [05:32<00:14,  1.04s/it]INFO:__main__:Requesting https://www.livoxtech.com/
INFO:__main__:Getting metadata for https://www.livoxtech.com
 95%|█████████▌| 254/267 [05:34<00:14,  1.11s/it]INFO:__main__:Requesting https://www.reddit.com/r/UAVmapping/comments/aimnik/livox_mid40_lidar_first_review_with_pictures/
INFO:__main__:Getting metadata for https://www.reddit.com/r/UAVmapping/comments/aimnik/livox_mid40_lidar_first_review_with_pictures/
 96%|█████████▌| 255/267 [05:34<00:12,  1.01s/it]INFO:__main__:Requesting https://techcrunch.com/2019/03/06/waymo-to-start-selling-standalone-lidar-sensors/
ERROR:__main__:Could not reach https://techcrunch.com/2019/03/06/waymo-to-start-selling-standalone-lidar-sensors/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 96%|█████████▌| 256/267 [05:35<00:08,  1.34it/s]INFO:__main__:Requesting https://www.google.com/get/sunroof
INFO:__main__:Getting metadata for https://www.google.com/get/sunroof
 96%|█████████▋| 257/267 [05:35<00:05,  1.68it/s]INFO:__main__:Requesting https://gis.stackexchange.com/questions/142443/what-are-lidar-returns
INFO:__main__:Getting metadata for https://gis.stackexchange.com/questions/142443/what-are-lidar-returns
 97%|█████████▋| 258/267 [05:35<00:04,  1.94it/s]INFO:__main__:Requesting https://www.mdpi.com/2072-4292/5/2/491
INFO:__main__:Getting metadata for https://www.mdpi.com/2072-4292/5/2/491
 97%|█████████▋| 259/267 [05:36<00:04,  1.66it/s]INFO:__main__:Requesting https://www.sciencedirect.com/science/article/pii/S0924271616000204
INFO:__main__:Getting metadata for https://www.sciencedirect.com/science/article/pii/S0924271616000204
 97%|█████████▋| 260/267 [05:36<00:03,  1.79it/s]INFO:__main__:Requesting https://azure.microsoft.com/en-us/services/kinect-dk/
INFO:__main__:Getting metadata for https://azure.microsoft.com/en-us/services/kinect-dk/
 98%|█████████▊| 261/267 [05:38<00:04,  1.36it/s]INFO:__main__:Requesting https://www.theverge.com/2019/3/6/18252561/waymo-sell-lidar-laser-sensor-av-customer-robot-taxi-competition
INFO:__main__:Getting metadata for https://www.theverge.com/2019/3/6/18252561/waymo-sell-lidar-laser-sensor-av-customer-robot-taxi-competition
 98%|█████████▊| 262/267 [05:38<00:02,  1.72it/s]INFO:__main__:Requesting https://rachitnigam.com/post/project-management/
INFO:__main__:Getting metadata for https://rachitnigam.com/post/project-management/
 99%|█████████▊| 263/267 [05:38<00:01,  2.12it/s]INFO:__main__:Requesting https://ewikipedia.org/wiki/Brian_May#Scientific_career
ERROR:__main__:Could not reach https://ewikipedia.org/wiki/Brian_May#Scientific_career
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7eff48fe7c50>, 'Connection to ewikipedia.org timed out. (connect timeout=6)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ewikipedia.org', port=443): Max retries exceeded with url: /wiki/Brian_May (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7eff48fe7c50>, 'Connection to ewikipedia.org timed out. (connect timeout=6)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='ewikipedia.org', port=443): Max retries exceeded with url: /wiki/Brian_May (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7eff48fe7c50>, 'Connection to ewikipedia.org timed out. (connect timeout=6)'))
 99%|█████████▉| 264/267 [05:45<00:07,  2.47s/it]INFO:__main__:Requesting http://readme.io/careers
INFO:__main__:Getting metadata for https://readme.io/careers
 99%|█████████▉| 265/267 [05:46<00:03,  1.92s/it]INFO:__main__:Requesting https://twitter.com/PwdRsch/status/1103021803503607808
INFO:__main__:Getting metadata for https://twitter.com/PwdRsch/status/1103021803503607808
100%|█████████▉| 266/267 [05:47<00:01,  1.67s/it]INFO:__main__:Requesting https://www.1843magazine.com/upfront/the-1843-interview/smoking-with-david-hockney
INFO:__main__:Getting metadata for https://www.1843magazine.com/upfront/the-1843-interview/smoking-with-david-hockney
100%|██████████| 267/267 [05:48<00:00,  1.38s/it]
