INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  7%|▋         | 2/30 [00:00<00:04,  6.00it/s] 10%|█         | 3/30 [00:00<00:04,  5.47it/s] 13%|█▎        | 4/30 [00:01<00:07,  3.42it/s] 17%|█▋        | 5/30 [00:02<00:12,  2.06it/s] 23%|██▎       | 7/30 [00:02<00:08,  2.74it/s] 27%|██▋       | 8/30 [00:03<00:13,  1.66it/s] 30%|███       | 9/30 [00:03<00:09,  2.21it/s] 33%|███▎      | 10/30 [00:03<00:09,  2.22it/s] 37%|███▋      | 11/30 [00:05<00:13,  1.39it/s] 40%|████      | 12/30 [00:05<00:11,  1.63it/s] 47%|████▋     | 14/30 [00:06<00:09,  1.74it/s] 50%|█████     | 15/30 [00:06<00:06,  2.20it/s] 57%|█████▋    | 17/30 [00:07<00:06,  2.12it/s] 63%|██████▎   | 19/30 [00:09<00:05,  1.84it/s] 67%|██████▋   | 20/30 [00:09<00:04,  2.33it/s] 80%|████████  | 24/30 [00:09<00:01,  3.10it/s] 83%|████████▎ | 25/30 [00:11<00:03,  1.41it/s] 87%|████████▋ | 26/30 [00:11<00:02,  1.88it/s] 90%|█████████ | 27/30 [00:14<00:03,  1.19s/it] 93%|█████████▎| 28/30 [00:20<00:05,  2.61s/it] 97%|█████████▋| 29/30 [00:20<00:01,  1.87s/it]100%|██████████| 30/30 [00:20<00:00,  1.35s/it]
  0%|          | 0/265 [00:00<?, ?it/s]INFO:__main__:Requesting https://www.openssl.org/news/secadv/20190226.txt
INFO:__main__:Getting metadata for https://www.openssl.org/news/secadv/20190226.txt
ERROR:__main__:Could not get metadata for https://www.openssl.org/news/secadv/20190226.txt
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  0%|          | 1/265 [00:00<02:09,  2.04it/s]INFO:__main__:Requesting https://www.hillelwayne.com/post/formally-specifying-uis/
INFO:__main__:Getting metadata for https://www.hillelwayne.com/post/formally-specifying-uis/
  1%|          | 2/265 [00:00<01:46,  2.47it/s]INFO:__main__:Requesting https://github.com/mukeshsoni/statechart-calculator
INFO:__main__:Getting metadata for https://github.com/mukeshsoni/statechart-calculator
  1%|          | 3/265 [00:01<02:18,  1.89it/s]INFO:__main__:Requesting https://pudding.cool/2019/02/gyllenhaal/
INFO:__main__:Getting metadata for https://pudding.cool/2019/02/gyllenhaal/
  2%|▏         | 4/265 [00:01<01:51,  2.33it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Sankey_diagram
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Sankey_diagram
  2%|▏         | 5/265 [00:02<02:27,  1.77it/s]INFO:__main__:Requesting https://sketch.systems/rgraves-aspiration/sketch/e85b70fd4ec153e7a22137b6070f00ef
INFO:__main__:Getting metadata for https://sketch.systems/rgraves-aspiration/sketch/e85b70fd4ec153e7a22137b6070f00ef
ERROR:__main__:Could not get metadata for https://sketch.systems/rgraves-aspiration/sketch/e85b70fd4ec153e7a22137b6070f00ef
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  2%|▏         | 6/265 [00:03<03:14,  1.33it/s]INFO:__main__:Requesting https://futureofcoding.org/episodes/025.html
INFO:__main__:Getting metadata for https://futureofcoding.org/episodes/025.html
ERROR:__main__:Could not get metadata for https://futureofcoding.org/episodes/025.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  3%|▎         | 7/265 [00:03<02:30,  1.71it/s]INFO:__main__:Requesting https://thelri.org/blog-and-news/why-drugs-that-work-in-mice-dont-work-in-humans/
INFO:__main__:Getting metadata for https://thelri.org/blog-and-news/why-drugs-that-work-in-mice-dont-work-in-humans/
  3%|▎         | 8/265 [00:04<02:21,  1.82it/s]INFO:__main__:Requesting http://dogagingproject.com
  3%|▎         | 9/265 [00:04<01:47,  2.38it/s]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/pmid/28374166/
ERROR:__main__:Could not reach https://www.ncbi.nlm.nih.gov/pmc/articles/pmid/28374166/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
  4%|▍         | 10/265 [00:04<01:38,  2.58it/s]INFO:__main__:Requesting https://www.leafscience.org/dr-matt-kaeberlein-the-dog-aging-project/
INFO:__main__:Getting metadata for https://www.leafscience.org/dr-matt-kaeberlein-the-dog-aging-project/
  4%|▍         | 11/265 [00:05<01:54,  2.22it/s]INFO:__main__:Requesting http://sagartewari01.com/c-macro-magic/
INFO:__main__:Getting metadata for http://sagartewari01.com/c-macro-magic/
  5%|▍         | 12/265 [00:06<02:03,  2.04it/s]INFO:__main__:Requesting https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/list.h?h=v5.0-rc8
INFO:__main__:Getting metadata for https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/list.h?h=v5.0-rc8
ERROR:__main__:Could not get metadata for https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/list.h?h=v5.0-rc8
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  5%|▍         | 13/265 [00:07<03:27,  1.21it/s]INFO:__main__:Requesting https://elixir.bootlin.com/linux/v2.6.11/source/include/linux/list.h
INFO:__main__:Getting metadata for https://elixir.bootlin.com/linux/v2.6.11/source/include/linux/list.h
  5%|▌         | 14/265 [00:15<11:52,  2.84s/it]INFO:__main__:Requesting https://github.com/freebsd/freebsd/blob/master/sys/sys/queue.h
INFO:__main__:Getting metadata for https://github.com/freebsd/freebsd/blob/master/sys/sys/queue.h
  6%|▌         | 15/265 [00:16<09:40,  2.32s/it]INFO:__main__:Requesting https://stackoverflow.com/questions/15832301/understanding-container-of-macro-in-the-linux-kernel
INFO:__main__:Getting metadata for https://stackoverflow.com/questions/15832301/understanding-container-of-macro-in-the-linux-kernel
  6%|▌         | 16/265 [00:16<07:12,  1.74s/it]INFO:__main__:Requesting http://ccodearchive.net/info/list.html
INFO:__main__:Getting metadata for http://ccodearchive.net/info/list.html
  6%|▋         | 17/265 [00:18<07:36,  1.84s/it]INFO:__main__:Requesting http://man7.org/linux/man-pages/man3/queue.3.html
INFO:__main__:Getting metadata for http://man7.org/linux/man-pages/man3/queue.3.html
ERROR:__main__:Could not get metadata for http://man7.org/linux/man-pages/man3/queue.3.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  7%|▋         | 18/265 [00:21<08:31,  2.07s/it]INFO:__main__:Requesting https://gitlab.com/oliver117/ucds/tree/master/src
INFO:__main__:Getting metadata for https://gitlab.com/oliver117/ucds/tree/master/src
  7%|▋         | 19/265 [00:22<06:50,  1.67s/it]INFO:__main__:Requesting https://docs.google.com/document/d/1xVrPoNutyqTdQ04DXBEZW4ZW4A5RAQW2he7qIpTmG-M/edit
INFO:__main__:Getting metadata for https://docs.google.com/document/d/1xVrPoNutyqTdQ04DXBEZW4ZW4A5RAQW2he7qIpTmG-M/preview?sle=true
  8%|▊         | 20/265 [00:23<06:19,  1.55s/it]INFO:__main__:Requesting https://gist.github.com/shobotch/5160017
INFO:__main__:Getting metadata for https://gist.github.com/shobotch/5160017
  8%|▊         | 21/265 [00:24<05:20,  1.31s/it]INFO:__main__:Requesting https://twitter.com/kevinriggle/status/23932444186
INFO:__main__:Getting metadata for https://twitter.com/kevinriggle/status/23932444186
  8%|▊         | 22/265 [00:24<04:27,  1.10s/it]INFO:__main__:Requesting https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/disconnections-explained
INFO:__main__:Getting metadata for https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/disconnections-explained
ERROR:__main__:Could not get metadata for https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/disconnections-explained
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  9%|▊         | 23/265 [00:25<03:35,  1.12it/s]INFO:__main__:Requesting https://discordapp.com/developers/docs/reference/
INFO:__main__:Getting metadata for https://discordapp.com/developers/docs/reference/
  9%|▉         | 24/265 [00:25<02:42,  1.49it/s]INFO:__main__:Requesting https://developer.twitter.com/en/developer-terms/agreement-and-policy.html
INFO:__main__:Getting metadata for https://developer.twitter.com/en/developer-terms/agreement-and-policy.html
ERROR:__main__:Could not get metadata for https://developer.twitter.com/en/developer-terms/agreement-and-policy.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
  9%|▉         | 25/265 [00:25<02:24,  1.66it/s]INFO:__main__:Requesting https://docs.google.com/spreadsheets/d/1BIAguT9Qvy0GK-dalpQfkbzqtCv0pvNuxU3zbMiR-iQ/edit?usp=sharing
INFO:__main__:Getting metadata for https://docs.google.com/spreadsheets/d/1BIAguT9Qvy0GK-dalpQfkbzqtCv0pvNuxU3zbMiR-iQ/edit?usp=sharing
 10%|▉         | 26/265 [00:26<02:49,  1.41it/s]INFO:__main__:Requesting https://pastebin.com/w8Dnj5kM
INFO:__main__:Getting metadata for https://pastebin.com/w8Dnj5kM
ERROR:__main__:Could not get metadata for https://pastebin.com/w8Dnj5kM
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 10%|█         | 27/265 [00:26<02:12,  1.80it/s]INFO:__main__:Requesting https://gist.github.com/localhostdotdev/48ed13972c3e5391a47f8e3dd7b9e0dd
INFO:__main__:Getting metadata for https://gist.github.com/localhostdotdev/48ed13972c3e5391a47f8e3dd7b9e0dd
 11%|█         | 28/265 [00:27<02:29,  1.59it/s]INFO:__main__:Requesting https://twitter.com/mauritscorneIis
INFO:__main__:Getting metadata for https://twitter.com/mauritscorneIis
 11%|█         | 29/265 [00:30<05:26,  1.38s/it]INFO:__main__:Requesting https://github.com/pomber/escher-bot
INFO:__main__:Getting metadata for https://github.com/pomber/escher-bot
 11%|█▏        | 30/265 [00:31<04:49,  1.23s/it]INFO:__main__:Requesting https://github.com/uucid-project/spec
INFO:__main__:Getting metadata for https://github.com/uucid-project/spec
 12%|█▏        | 31/265 [00:32<04:30,  1.15s/it]INFO:__main__:Requesting https://www.npr.org/sections/thetwo-way/2017/12/26/573609499/library-of-congress-will-no-longer-archive-every-tweet
INFO:__main__:Getting metadata for https://www.npr.org/sections/thetwo-way/2017/12/26/573609499/library-of-congress-will-no-longer-archive-every-tweet
 12%|█▏        | 32/265 [00:33<03:30,  1.11it/s]INFO:__main__:Requesting https://pushshift.io
INFO:__main__:Getting metadata for https://pushshift.io
ERROR:__main__:Could not get metadata for https://pushshift.io
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 12%|█▏        | 33/265 [00:33<02:47,  1.39it/s]INFO:__main__:Requesting https://randomascii.wordpress.com/2012/12/29/the-surprising-subtleties-of-zeroing-a-register/
ERROR:__main__:Could not reach https://randomascii.wordpress.com/2012/12/29/the-surprising-subtleties-of-zeroing-a-register/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 13%|█▎        | 34/265 [00:33<02:05,  1.84it/s]INFO:__main__:Requesting http://lion137.blogspot.com/2019/02/fundamental-algorithms-iii.html
INFO:__main__:Getting metadata for http://lion137.blogspot.com/2019/02/fundamental-algorithms-iii.html
 13%|█▎        | 35/265 [00:33<01:39,  2.31it/s]INFO:__main__:Requesting http://immersivemath.com/ila/index.html
INFO:__main__:Getting metadata for http://immersivemath.com/ila/index.html
 14%|█▎        | 36/265 [00:36<04:18,  1.13s/it]INFO:__main__:Requesting http://joshua.smcvt.edu/linearalgebra/
INFO:__main__:Getting metadata for http://joshua.smcvt.edu/linearalgebra/
ERROR:__main__:Could not get metadata for http://joshua.smcvt.edu/linearalgebra/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 14%|█▍        | 37/265 [00:36<03:31,  1.08it/s]INFO:__main__:Requesting http://webwork.maa.org/
INFO:__main__:Getting metadata for http://webwork.maa.org
 14%|█▍        | 38/265 [00:37<02:55,  1.29it/s]INFO:__main__:Requesting https://crastina.se/theres-no-projects-like-side-projects/
INFO:__main__:Getting metadata for https://crastina.se/theres-no-projects-like-side-projects/
 15%|█▍        | 39/265 [00:43<09:16,  2.46s/it]INFO:__main__:Requesting http://quantumgame.io/
INFO:__main__:Getting metadata for http://quantumgame.io
 15%|█▌        | 40/265 [00:45<08:33,  2.28s/it]INFO:__main__:Requesting https://github.com/stared/science-based-games-list;
 15%|█▌        | 41/265 [00:45<06:08,  1.64s/it]INFO:__main__:Requesting http://p.migdal.pl/interactive-machine-learning-list/
INFO:__main__:Getting metadata for http://p.migdal.pl/interactive-machine-learning-list/
 16%|█▌        | 42/265 [00:45<04:40,  1.26s/it]INFO:__main__:Requesting https://ximera.osu.edu/mooculus
INFO:__main__:Getting metadata for https://ximera.osu.edu/mooculus
 16%|█▌        | 43/265 [00:46<04:13,  1.14s/it]INFO:__main__:Requesting http://pat.perso.ens-lyon.org/M1P1/
INFO:__main__:Getting metadata for http://pat.perso.ens-lyon.org/M1P1/
 17%|█▋        | 44/265 [00:48<04:50,  1.32s/it]INFO:__main__:Requesting https://openstax.org/
INFO:__main__:Getting metadata for https://openstax.org
 17%|█▋        | 45/265 [00:49<04:39,  1.27s/it]INFO:__main__:Requesting https://open.umn.edu/opentextbooks/
INFO:__main__:Getting metadata for https://open.umn.edu/opentextbooks/
 17%|█▋        | 46/265 [00:51<05:08,  1.41s/it]INFO:__main__:Requesting http://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/AlgebraTrigIntro.aspx
INFO:__main__:Getting metadata for http://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/AlgebraTrigIntro.aspx
 18%|█▊        | 47/265 [00:53<05:26,  1.50s/it]INFO:__main__:Requesting https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw
INFO:__main__:Getting metadata for https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw
 18%|█▊        | 48/265 [00:56<07:21,  2.03s/it]INFO:__main__:Requesting https://github.com/photonlines/Intuitive-Overview-of-Linear-Algebra-Fundamentals
INFO:__main__:Getting metadata for https://github.com/photonlines/Intuitive-Overview-of-Linear-Algebra-Fundamentals
 18%|█▊        | 49/265 [00:57<05:56,  1.65s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab
 19%|█▉        | 50/265 [00:58<05:14,  1.46s/it]INFO:__main__:Requesting http://treena.org
INFO:__main__:Getting metadata for https://treena.org
 19%|█▉        | 51/265 [00:59<04:35,  1.29s/it]INFO:__main__:Requesting https://imgur.com/dzidyuV
INFO:__main__:Getting metadata for https://imgur.com/dzidyuV
ERROR:__main__:Could not get metadata for https://imgur.com/dzidyuV
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 20%|█▉        | 52/265 [00:59<03:30,  1.01it/s]INFO:__main__:Requesting https://www.euclidea.xyz/
INFO:__main__:Getting metadata for https://www.euclidea.xyz
 20%|██        | 53/265 [01:00<03:22,  1.05it/s]INFO:__main__:Requesting http://abstract.ups.edu/aata/
INFO:__main__:Getting metadata for http://abstract.ups.edu/aata/
 20%|██        | 54/265 [01:01<03:58,  1.13s/it]INFO:__main__:Requesting http://linear.pugetsound.edu/html/fcla.html
INFO:__main__:Getting metadata for http://linear.pugetsound.edu/html/fcla.html
 21%|██        | 55/265 [01:02<03:49,  1.09s/it]INFO:__main__:Requesting https://physicstoday.scitation.org/doi/full/10.1063/1.1768652
INFO:__main__:Getting metadata for https://physicstoday.scitation.org/action/captchaChallenge?redirectUrl=https%3A%2F%2Fphysicstoday.scitation.org%2Fdoi%2Ffull%2F10.1063%2F1.1768652
 21%|██        | 56/265 [01:05<05:22,  1.54s/it]INFO:__main__:Requesting http://www.math.harvard.edu/~elkies/M55a.17/index.html
INFO:__main__:Getting metadata for http://www.math.harvard.edu/~elkies/M55a.17/index.html
ERROR:__main__:Could not get metadata for http://www.math.harvard.edu/~elkies/M55a.17/index.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 22%|██▏       | 57/265 [01:06<04:57,  1.43s/it]INFO:__main__:Requesting http://setosa.io/ev/eigenvectors-and-eigenvalues/
INFO:__main__:Getting metadata for http://setosa.io/ev/eigenvectors-and-eigenvalues/
ERROR:__main__:Could not get metadata for http://setosa.io/ev/eigenvectors-and-eigenvalues/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 22%|██▏       | 58/265 [01:06<03:46,  1.09s/it]INFO:__main__:Requesting https://www.amazon.com/Visual-Group-Theory-Problem-Book/dp/088385757X
 22%|██▏       | 59/265 [01:07<03:01,  1.14it/s]INFO:__main__:Requesting http://www.otherhand.org/home-page/search-and-rescue/the-hunt-for-the-death-valley-germans/
INFO:__main__:Getting metadata for http://www.otherhand.org/home-page/search-and-rescue/the-hunt-for-the-death-valley-germans/
 23%|██▎       | 60/265 [01:08<03:10,  1.07it/s]INFO:__main__:Requesting https://www.theguardian.com/australia-news/2018/nov/08/boy-12-feared-missing-after-three-people-found-dead-near-broken-down-vehicle-in-outback
INFO:__main__:Getting metadata for https://www.theguardian.com/australia-news/2018/nov/08/boy-12-feared-missing-after-three-people-found-dead-near-broken-down-vehicle-in-outback
 23%|██▎       | 61/265 [01:08<02:35,  1.31it/s]INFO:__main__:Requesting https://www.sbs.com.au/news/what-a-tragic-end-German-couple-die-in-northern-territory-outback
 23%|██▎       | 62/265 [01:10<03:29,  1.03s/it]INFO:__main__:Requesting https://nypost.com/2018/01/11/tourist-dies-hiking-in-australia-outback-heat/
ERROR:__main__:Could not reach https://nypost.com/2018/01/11/tourist-dies-hiking-in-australia-outback-heat/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 24%|██▍       | 63/265 [01:10<02:35,  1.30it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Saxon_Switzerland_climbing_region
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Saxon_Switzerland_climbing_region
 24%|██▍       | 64/265 [01:11<02:34,  1.30it/s]INFO:__main__:Requesting https://expensive.chat
INFO:__main__:Getting metadata for https://expensive.chat
ERROR:__main__:Could not get metadata for https://expensive.chat
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 25%|██▍       | 65/265 [01:12<03:18,  1.01it/s]INFO:__main__:Requesting http://www.milliondollarhomepage.com/
INFO:__main__:Getting metadata for http://www.milliondollarhomepage.com
 25%|██▍       | 66/265 [01:15<05:27,  1.64s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/The_Million_Dollar_Homepage
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/The_Million_Dollar_Homepage
 25%|██▌       | 67/265 [01:17<05:00,  1.52s/it]INFO:__main__:Requesting https://highscore.money
INFO:__main__:Getting metadata for https://highscore.money
 26%|██▌       | 68/265 [01:18<04:29,  1.37s/it]INFO:__main__:Requesting https://www.crunchbase.com/organization/whale-3
 26%|██▌       | 69/265 [01:18<03:19,  1.02s/it]INFO:__main__:Requesting https://www.citylab.com/transportation/2019/02/france-high-speed-rail-new-trains-tgv-2020-sncf-cost-ticket/583624/
INFO:__main__:Getting metadata for https://www.citylab.com/transportation/2019/02/france-high-speed-rail-new-trains-tgv-2020-sncf-cost-ticket/583624/
 26%|██▋       | 70/265 [01:18<02:32,  1.28it/s]INFO:__main__:Requesting https://fr.wiktionary.org/wiki/composteur
INFO:__main__:Getting metadata for https://fr.wiktionary.org/wiki/composteur
 27%|██▋       | 71/265 [01:19<02:39,  1.21it/s]INFO:__main__:Requesting https://www.larousse.fr/dictionnaires/francais/composteur/17760
INFO:__main__:Getting metadata for https://www.larousse.fr/dictionnaires/francais/composteur/17760
 27%|██▋       | 72/265 [01:21<03:20,  1.04s/it]INFO:__main__:Requesting https://www.theguardian.com/commentisfree/2017/dec/05/the-guardian-view-on-rail-privatisation-going-off-the-tracks
INFO:__main__:Getting metadata for https://www.theguardian.com/commentisfree/2017/dec/05/the-guardian-view-on-rail-privatisation-going-off-the-tracks
 28%|██▊       | 73/265 [01:21<03:05,  1.04it/s]INFO:__main__:Requesting https://www.ft.com/content/d192b1b4-458b-11e5-af2f-4d6e0e5eda22
INFO:__main__:Getting metadata for https://www.ft.com/content/d192b1b4-458b-11e5-af2f-4d6e0e5eda22
 28%|██▊       | 74/265 [01:23<03:43,  1.17s/it]INFO:__main__:Requesting https://www.bbc.co.uk/news/magazine-21056703
INFO:__main__:Getting metadata for https://www.bbc.co.uk/news/magazine-21056703
 28%|██▊       | 75/265 [01:26<05:42,  1.80s/it]INFO:__main__:Requesting https://www.stagecoach.com/media/insight-features/the-facts-about-rail-fares.aspx
INFO:__main__:Getting metadata for https://www.stagecoach.com/media/insight-features/the-facts-about-rail-fares.aspx
 29%|██▊       | 76/265 [01:27<04:57,  1.58s/it]INFO:__main__:Requesting https://europa.eu/youreurope/business/selling-in-eu/public-contracts/rules-procedures/index_en.htm
INFO:__main__:Getting metadata for https://europa.eu/youreurope/business/selling-in-eu/public-contracts/rules-procedures/index_en.htm
 29%|██▉       | 77/265 [01:29<04:42,  1.50s/it]INFO:__main__:Requesting http://ec.europa.eu/competition/state_aid/overview/index_en.html
INFO:__main__:Getting metadata for http://ec.europa.eu/competition/state_aid/overview/index_en.html
 29%|██▉       | 78/265 [01:31<05:02,  1.62s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Import_substitution_industrialization
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Import_substitution_industrialization
 30%|██▉       | 79/265 [01:32<04:46,  1.54s/it]INFO:__main__:Requesting https://en.wiktionary.org/wiki/inou%C3%AF
INFO:__main__:Getting metadata for https://en.wiktionary.org/wiki/inou%C3%AF
 30%|███       | 80/265 [01:33<04:01,  1.31s/it]INFO:__main__:Requesting https://translate.google.com/#view=home&op=translate&sl=fr&tl=en&text=coup%20de%20gr%C3%A2ce
INFO:__main__:Getting metadata for https://translate.google.com/#view=home&op=translate&sl=fr&tl=en&text=coup%20de%20gr%C3%A2ce
 31%|███       | 81/265 [01:33<03:10,  1.03s/it]INFO:__main__:Requesting https://www.nippon.com/en/currents/d00428/japan%E2%80%99s-shinkansen-moving-on-to-the-next-generation.html
INFO:__main__:Getting metadata for https://www.nippon.com/en/currents/d00428/japan%E2%80%99s-shinkansen-moving-on-to-the-next-generation.html
 31%|███       | 82/265 [01:34<02:51,  1.07it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=up2efe46N0Y
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=up2efe46N0Y
 31%|███▏      | 83/265 [01:35<02:48,  1.08it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/AGV_(train)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/AGV_(train)
 32%|███▏      | 84/265 [01:36<03:15,  1.08s/it]INFO:__main__:Requesting https://www.thelocal.fr/20180727/fire-blocks-montparnasse-train-station-in-paris-at-height-of-holiday-exodus
INFO:__main__:Getting metadata for https://www.thelocal.fr/20180727/fire-blocks-montparnasse-train-station-in-paris-at-height-of-holiday-exodus
 32%|███▏      | 85/265 [01:38<03:28,  1.16s/it]INFO:__main__:Requesting https://www.cnbc.com/2019/02/26/hyperloop-firm-unveils-first-images-of-its-new-test-track-in-toulouse.html
INFO:__main__:Getting metadata for https://www.cnbc.com/2019/02/26/hyperloop-firm-unveils-first-images-of-its-new-test-track-in-toulouse.html
 32%|███▏      | 86/265 [01:38<03:14,  1.08s/it]INFO:__main__:Requesting https://reading.supply/@alexatnear/what-you-need-to-know-before-you-join-a-start-up-MVjDHG
INFO:__main__:Getting metadata for https://reading.supply/@alexatnear/what-you-need-to-know-before-you-join-a-start-up-MVjDHG
 33%|███▎      | 87/265 [01:40<03:30,  1.18s/it]INFO:__main__:Requesting https://youtu.be/I6IQ_FOCE6I
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=I6IQ_FOCE6I&feature=youtu.be
 33%|███▎      | 88/265 [01:41<03:11,  1.08s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Clawback
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Clawback
 34%|███▎      | 89/265 [01:41<02:55,  1.00it/s]INFO:__main__:Requesting https://github.com/holman/extended-exercise-windows
INFO:__main__:Getting metadata for https://github.com/holman/extended-exercise-windows
 34%|███▍      | 90/265 [01:42<02:41,  1.08it/s]INFO:__main__:Requesting https://blog.wealthfront.com/always-file-your-83b/
INFO:__main__:Getting metadata for https://blog.wealthfront.com/always-file-your-83b/
 34%|███▍      | 91/265 [01:43<02:15,  1.28it/s]INFO:__main__:Requesting https://arxiv.org/abs/1901.10664
INFO:__main__:Getting metadata for https://arxiv.org/abs/1901.10664
 35%|███▍      | 92/265 [01:44<02:33,  1.12it/s]INFO:__main__:Requesting https://github.com/emmericp/ixy
INFO:__main__:Getting metadata for https://github.com/emmericp/ixy
 35%|███▌      | 93/265 [01:45<02:30,  1.14it/s]INFO:__main__:Requesting https://github.com/emmericp/ixy/pull/14
INFO:__main__:Getting metadata for https://github.com/emmericp/ixy/pull/14
 35%|███▌      | 94/265 [01:47<03:21,  1.18s/it]INFO:__main__:Requesting https://github.com/ixy-languages/ixy-languages
INFO:__main__:Getting metadata for https://github.com/ixy-languages/ixy-languages
 36%|███▌      | 95/265 [01:48<03:24,  1.20s/it]INFO:__main__:Requesting https://media.ccc.de/v/34c3-9159-demystifying_network_cards
INFO:__main__:Getting metadata for https://media.ccc.de/v/34c3-9159-demystifying_network_cards
 36%|███▌      | 96/265 [01:49<03:30,  1.24s/it]INFO:__main__:Requesting https://media.ccc.de/v/35c3-9670-safe_and_secure_drivers_in_high-level_languages
INFO:__main__:Getting metadata for https://media.ccc.de/v/35c3-9670-safe_and_secure_drivers_in_high-level_languages
 37%|███▋      | 97/265 [01:50<03:22,  1.20s/it]INFO:__main__:Requesting https://fosdem.org/2019/schedule/event/writing_network_drivers_in_high_level_languages/
INFO:__main__:Getting metadata for https://fosdem.org/2019/schedule/event/writing_network_drivers_in_high_level_languages/
ERROR:__main__:Could not get metadata for https://fosdem.org/2019/schedule/event/writing_network_drivers_in_high_level_languages/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 37%|███▋      | 98/265 [01:51<03:19,  1.19s/it]INFO:__main__:Requesting https://www.citylab.com/design/2012/01/why-portlands-public-toilets-succeeded-where-others-failed/1020/
INFO:__main__:Getting metadata for https://www.citylab.com/design/2012/01/why-portlands-public-toilets-succeeded-where-others-failed/1020/
 37%|███▋      | 99/265 [01:52<02:30,  1.10it/s]INFO:__main__:Requesting https://www.fastcompany.com/3065278/german-cities-are-solving-the-age-old-public-toilet-problem
INFO:__main__:Getting metadata for https://www.fastcompany.com/3065278/german-cities-are-solving-the-age-old-public-toilet-problem
 38%|███▊      | 100/265 [01:52<01:57,  1.41it/s]INFO:__main__:Requesting https://portlandloo.com/faq/
INFO:__main__:Getting metadata for https://portlandloo.com/faq/
 38%|███▊      | 101/265 [01:53<01:51,  1.48it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Greyhound_therapy
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Greyhound_therapy
 38%|███▊      | 102/265 [01:53<01:58,  1.38it/s]INFO:__main__:Requesting https://www.bbc.com/news/world-us-canada-44088033
INFO:__main__:Getting metadata for https://www.bbc.com/news/world-us-canada-44088033
 39%|███▉      | 103/265 [01:56<03:21,  1.24s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Camden_bench
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Camden_bench
 39%|███▉      | 104/265 [01:57<02:58,  1.11s/it]INFO:__main__:Requesting https://youtu.be/qXjPxBPgGV0
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=qXjPxBPgGV0&feature=youtu.be
 40%|███▉      | 105/265 [01:58<02:46,  1.04s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Portland_Loo#/media/File%3APortland_Loo_with_Sharps_drop_box_.jpg
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Portland_Loo#/media/File%3APortland_Loo_with_Sharps_drop_box_.jpg
 40%|████      | 106/265 [01:59<02:57,  1.12s/it]INFO:__main__:Requesting https://missionlocal.org/2019/02/jcdecaux-toilet-contract-may-be-flushed-as-city-spurns-extension/
INFO:__main__:Getting metadata for https://missionlocal.org/2019/02/jcdecaux-toilet-contract-may-be-flushed-as-city-spurns-extension/
 40%|████      | 107/265 [01:59<02:22,  1.11it/s]INFO:__main__:Requesting http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=10&swarmCount=1&unitScale=0.2&ownPhysics=false
INFO:__main__:Getting metadata for http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=10&swarmCount=1&unitScale=0.2&ownPhysics=false
ERROR:__main__:Could not get metadata for http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=10&swarmCount=1&unitScale=0.2&ownPhysics=false
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 41%|████      | 108/265 [02:01<03:00,  1.15s/it]INFO:__main__:Requesting http://emh.lart.no/publish/csb/csb3d/vWreckingBall/
INFO:__main__:Getting metadata for http://emh.lart.no/publish/csb/csb3d/vWreckingBall/
ERROR:__main__:Could not get metadata for http://emh.lart.no/publish/csb/csb3d/vWreckingBall/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 41%|████      | 109/265 [02:02<03:18,  1.27s/it]INFO:__main__:Requesting https://www.codingame.com/multiplayer/bot-programming/coders-strike-back
INFO:__main__:Getting metadata for https://www.codingame.com/multiplayer/bot-programming/coders-strike-back
 42%|████▏     | 110/265 [02:03<02:33,  1.01it/s]INFO:__main__:Requesting http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=1000&swarmCount=10&unitScale=0.1&ownPhysics=false
INFO:__main__:Getting metadata for http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=1000&swarmCount=10&unitScale=0.1&ownPhysics=false
ERROR:__main__:Could not get metadata for http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=1000&swarmCount=10&unitScale=0.1&ownPhysics=false
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 42%|████▏     | 111/265 [02:04<02:59,  1.16s/it]INFO:__main__:Requesting http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=1000&swarmCount=20&unitScale=0.2&ownPhysics=false
INFO:__main__:Getting metadata for http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=1000&swarmCount=20&unitScale=0.2&ownPhysics=false
ERROR:__main__:Could not get metadata for http://emh.lart.no/publish/csb/csb3d/v1/?dupCount=1000&swarmCount=20&unitScale=0.2&ownPhysics=false
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 42%|████▏     | 112/265 [02:06<03:17,  1.29s/it]INFO:__main__:Requesting http://emh.lart.no/publish/csb/million-mutas2.png
INFO:__main__:Getting metadata for http://emh.lart.no/publish/csb/million-mutas2.png
ERROR:__main__:Could not get metadata for http://emh.lart.no/publish/csb/million-mutas2.png
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 43%|████▎     | 113/265 [05:37<2:42:21, 64.09s/it]INFO:__main__:Requesting http://emh.lart.no/publish/csb/csb3d.png
INFO:__main__:Getting metadata for http://emh.lart.no/publish/csb/csb3d.png
ERROR:__main__:Could not get metadata for http://emh.lart.no/publish/csb/csb3d.png
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 43%|████▎     | 114/265 [06:46<2:45:14, 65.66s/it]INFO:__main__:Requesting https://sysdig.com/blog/the-art-of-writing-ebpf-programs-a-primer/
INFO:__main__:Getting metadata for https://sysdig.com/blog/the-art-of-writing-ebpf-programs-a-primer/
 43%|████▎     | 115/265 [06:46<1:55:03, 46.03s/it]INFO:__main__:Requesting https://sysdig.com/blog/container-isolation-gone-wrong/
INFO:__main__:Getting metadata for https://sysdig.com/blog/container-isolation-gone-wrong/
 44%|████▍     | 116/265 [06:46<1:20:05, 32.25s/it]INFO:__main__:Requesting https://lwn.net/Articles/740157/
INFO:__main__:Getting metadata for https://lwn.net/Articles/740157/
 44%|████▍     | 117/265 [06:47<56:15, 22.81s/it]  INFO:__main__:Requesting https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/networking/filter.txt
INFO:__main__:Getting metadata for https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/networking/filter.txt
ERROR:__main__:Could not get metadata for https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/networking/filter.txt
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 45%|████▍     | 118/265 [06:48<40:09, 16.39s/it]INFO:__main__:Requesting https://techcrunch.com/2019/02/26/facebook-vs-patreon/
ERROR:__main__:Could not reach https://techcrunch.com/2019/02/26/facebook-vs-patreon/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 45%|████▍     | 119/265 [06:49<28:02, 11.52s/it]INFO:__main__:Requesting https://liberapay.com/
INFO:__main__:Getting metadata for https://liberapay.com
 45%|████▌     | 120/265 [06:50<20:28,  8.47s/it]INFO:__main__:Requesting https://www.theatlantic.com/ideas/archive/2018/10/its-not-free-speech-criticize-muhammad-echr-ruled/574174/
INFO:__main__:Getting metadata for https://www.theatlantic.com/ideas/archive/2018/10/its-not-free-speech-criticize-muhammad-echr-ruled/574174/
 46%|████▌     | 121/265 [06:50<14:31,  6.05s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Freedom_of_speech_by_country
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Freedom_of_speech_by_country
 46%|████▌     | 122/265 [06:53<12:15,  5.14s/it]INFO:__main__:Requesting https://www.cnbc.com/2019/01/23/crowd-funding-platform-patreon-announces-it-will-pay-out-half-a-billion-dollars-to-content-creators-in-2019.html
INFO:__main__:Getting metadata for https://www.cnbc.com/2019/01/23/crowd-funding-platform-patreon-announces-it-will-pay-out-half-a-billion-dollars-to-content-creators-in-2019.html
 46%|████▋     | 123/265 [06:54<08:49,  3.73s/it]INFO:__main__:Requesting https://store.steampowered.com/about/
INFO:__main__:Getting metadata for https://store.steampowered.com/about/
 47%|████▋     | 124/265 [06:55<06:55,  2.95s/it]INFO:__main__:Requesting https://steamcommunity.com/groups/steamworks/announcements/detail/1697191267930157838
INFO:__main__:Getting metadata for https://steamcommunity.com/groups/steamworks/announcements/detail/1697191267930157838
 47%|████▋     | 125/265 [06:56<05:39,  2.43s/it]INFO:__main__:Requesting https://www.patreon.com/legal
 48%|████▊     | 126/265 [06:56<04:00,  1.73s/it]INFO:__main__:Requesting https://twitter.com/ericacbarnett/status/1100809443422302208
INFO:__main__:Getting metadata for https://twitter.com/ericacbarnett/status/1100809443422302208
 48%|████▊     | 127/265 [06:57<03:14,  1.41s/it]INFO:__main__:Requesting https://www.facebook.com/business/help/1278167592274041
INFO:__main__:Getting metadata for https://www.facebook.com/business/help/1278167592274041
 48%|████▊     | 128/265 [07:13<13:21,  5.85s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence
 49%|████▊     | 129/265 [07:14<09:45,  4.31s/it]INFO:__main__:Requesting https://www.oreilly.com/library/view/working-effectively-with/0131177052/
INFO:__main__:Getting metadata for https://www.oreilly.com/library/view/working-effectively-with/0131177052/
 49%|████▉     | 130/265 [07:15<07:17,  3.24s/it]INFO:__main__:Requesting http://www.throwcase.com/2014/12/21/that-five-monkeys-and-a-banana-story-is-rubbish/
INFO:__main__:Getting metadata for http://www.throwcase.com/2014/12/21/that-five-monkeys-and-a-banana-story-is-rubbish/
 49%|████▉     | 131/265 [07:15<05:25,  2.43s/it]INFO:__main__:Requesting https://www.forbes.com/sites/davidbressan/2018/03/11/how-century-old-tsunami-stones-saved-lives-in-the-tohoku-earthquake-of-2011/#681622a244fd
INFO:__main__:Getting metadata for https://www.forbes.com/sites/davidbressan/2018/03/11/how-century-old-tsunami-stones-saved-lives-in-the-tohoku-earthquake-of-2011/#681622a244fd
 50%|████▉     | 132/265 [07:16<04:21,  1.97s/it]INFO:__main__:Requesting http://www.nbcnews.com/id/43018489/ns/world_news-asia_pacific/t/how-one-japanese-village-defied-tsunami/#.XHdyjYhKjAQ
INFO:__main__:Getting metadata for http://www.nbcnews.com/id/43018489/ns/world_news-asia_pacific/t/how-one-japanese-village-defied-tsunami/#.XHdyjYhKjAQ
 50%|█████     | 133/265 [07:18<04:16,  1.94s/it]INFO:__main__:Requesting https://skeptics.stackexchange.com/a/6859
INFO:__main__:Getting metadata for https://skeptics.stackexchange.com/questions/6828/was-the-experiment-with-five-monkeys-a-ladder-a-banana-and-a-water-spray-condu/6859#6859
 51%|█████     | 134/265 [07:19<03:26,  1.57s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Hundredth_monkey_effect
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Hundredth_monkey_effect
 51%|█████     | 135/265 [07:19<02:51,  1.32s/it]INFO:__main__:Requesting https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/
INFO:__main__:Getting metadata for https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/
 51%|█████▏    | 136/265 [07:20<02:35,  1.20s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Second-system_effect
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Second-system_effect
 52%|█████▏    | 137/265 [07:21<02:15,  1.06s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=TQB0KK2rxcw#t=31m0s
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=TQB0KK2rxcw#t=31m0s
 52%|█████▏    | 138/265 [07:22<02:14,  1.06s/it]INFO:__main__:Requesting https://twitter.com/skamille/status/1004735128726376448
INFO:__main__:Getting metadata for https://twitter.com/skamille/status/1004735128726376448
 52%|█████▏    | 139/265 [07:23<02:07,  1.01s/it]INFO:__main__:Requesting https://codescene.io/showcase
INFO:__main__:Getting metadata for https://codescene.io/showcase
 53%|█████▎    | 140/265 [07:24<02:19,  1.11s/it]INFO:__main__:Requesting https://empear.com/blog/prioritize-technical-debt/
INFO:__main__:Getting metadata for https://empear.com/blog/prioritize-technical-debt/
 53%|█████▎    | 141/265 [07:25<01:53,  1.09it/s]INFO:__main__:Requesting https://pragprog.com/book/atevol/software-design-x-rays
INFO:__main__:Getting metadata for https://pragprog.com/book/atevol/software-design-x-rays
 54%|█████▎    | 142/265 [07:27<02:30,  1.22s/it]INFO:__main__:Requesting https://github.com/davidmarkclements/0x
INFO:__main__:Getting metadata for https://github.com/davidmarkclements/0x
 54%|█████▍    | 143/265 [07:28<02:21,  1.16s/it]INFO:__main__:Requesting https://github.com/mapbox/flamebearer
INFO:__main__:Getting metadata for https://github.com/mapbox/flamebearer
 54%|█████▍    | 144/265 [07:29<02:13,  1.10s/it]INFO:__main__:Requesting https://herbertograca.com/2017/08/03/layered-architecture/
ERROR:__main__:Could not reach https://herbertograca.com/2017/08/03/layered-architecture/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 55%|█████▍    | 145/265 [07:29<01:38,  1.22it/s]INFO:__main__:Requesting https://github.com/ggreer/the_silver_searcher
INFO:__main__:Getting metadata for https://github.com/ggreer/the_silver_searcher
 55%|█████▌    | 146/265 [07:30<01:46,  1.12it/s]INFO:__main__:Requesting https://www.amazon.com/Working-Effectively-Legacy-Michael-Feathers/dp/0131177052
INFO:__main__:Getting metadata for https://www.amazon.com/Working-Effectively-Legacy-Michael-Feathers/dp/0131177052
 55%|█████▌    | 147/265 [07:37<05:29,  2.80s/it]INFO:__main__:Requesting http://wiki.c2.com/?GodClass
INFO:__main__:Getting metadata for http://wiki.c2.com/?GodClass
ERROR:__main__:Could not get metadata for http://wiki.c2.com/?GodClass
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 56%|█████▌    | 148/265 [07:37<03:57,  2.03s/it]INFO:__main__:Requesting http://obdurodon.silvrback.com/navigating-a-large-codebase
INFO:__main__:Getting metadata for http://obdurodon.silvrback.com/navigating-a-large-codebase
 56%|█████▌    | 149/265 [07:38<02:59,  1.54s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Software_intelligence
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Software_intelligence
 57%|█████▋    | 150/265 [07:39<02:33,  1.34s/it]INFO:__main__:Requesting http://ai.stanford.edu/blog/beyond_local_pattern_matching/
INFO:__main__:Getting metadata for http://ai.stanford.edu/blog/beyond_local_pattern_matching/
 57%|█████▋    | 151/265 [07:39<02:01,  1.06s/it]INFO:__main__:Requesting https://stanfordnlp.github.io/coqa/
INFO:__main__:Getting metadata for https://stanfordnlp.github.io/coqa/
 57%|█████▋    | 152/265 [07:40<01:40,  1.13it/s]INFO:__main__:Requesting http://csrankings.org/#/fromyear/2018/toyear/2018/index?ai&vision&mlmining&nlp&ir&world
INFO:__main__:Getting metadata for http://csrankings.org/#/fromyear/2018/toyear/2018/index?ai&vision&mlmining&nlp&ir&world
 58%|█████▊    | 153/265 [07:40<01:30,  1.24it/s]INFO:__main__:Requesting https://www.economist.com/books-and-arts/2018/09/27/in-the-struggle-for-ai-supremacy-china-will-prevail
INFO:__main__:Getting metadata for https://www.economist.com/books-and-arts/2018/09/27/in-the-struggle-for-ai-supremacy-china-will-prevail
 58%|█████▊    | 154/265 [07:41<01:16,  1.45it/s]INFO:__main__:Requesting https://www.uspto.gov/patents-getting-started/international-protection/trade-secrets-policy
INFO:__main__:Getting metadata for https://www.uspto.gov/patents-getting-started/international-protection/trade-secrets-policy
 58%|█████▊    | 155/265 [07:41<01:13,  1.50it/s]INFO:__main__:Requesting https://arxiv.org/abs/1810.04805
INFO:__main__:Getting metadata for https://arxiv.org/abs/1810.04805
 59%|█████▉    | 156/265 [07:42<01:24,  1.30it/s]INFO:__main__:Requesting https://ai.googleblog.com/2019/01/natural-questions-new-corpus-and.html
INFO:__main__:Getting metadata for https://ai.googleblog.com/2019/01/natural-questions-new-corpus-and.html
 59%|█████▉    | 157/265 [07:43<01:09,  1.55it/s]INFO:__main__:Requesting https://arxiv.org/abs/1704.05179
INFO:__main__:Getting metadata for https://arxiv.org/abs/1704.05179
 60%|█████▉    | 158/265 [07:44<01:22,  1.30it/s]INFO:__main__:Requesting https://grapesjs.com/
INFO:__main__:Getting metadata for https://grapesjs.com
 60%|██████    | 159/265 [07:44<01:03,  1.67it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/S-Lang
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/S-Lang
 60%|██████    | 160/265 [07:45<01:09,  1.52it/s]INFO:__main__:Requesting http://wiki.squeak.org/squeak/slang
INFO:__main__:Getting metadata for http://wiki.squeak.org/squeak/slang
ERROR:__main__:Could not get metadata for http://wiki.squeak.org/squeak/slang
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 61%|██████    | 161/265 [07:45<01:06,  1.57it/s]INFO:__main__:Requesting https://www.nybooks.com/articles/2019/03/07/george-hutchinson-abyss-reading-age-catastrophe/
INFO:__main__:Getting metadata for https://www.nybooks.com/articles/2019/03/07/george-hutchinson-abyss-reading-age-catastrophe/
 61%|██████    | 162/265 [07:46<01:00,  1.69it/s]INFO:__main__:Requesting https://debugandrelease.blogspot.com/2019/02/two-productivity-tricks-in-visual.html
INFO:__main__:Getting metadata for https://debugandrelease.blogspot.com/2019/02/two-productivity-tricks-in-visual.html
 62%|██████▏   | 163/265 [07:46<00:49,  2.05it/s]INFO:__main__:Requesting https://www.jetbrains.com/resharper/
INFO:__main__:Getting metadata for https://www.jetbrains.com/resharper/
 62%|██████▏   | 164/265 [07:47<00:57,  1.76it/s]INFO:__main__:Requesting https://marketplace.visualstudio.com/items?itemName=JaredParMSFT.VsVim
INFO:__main__:Getting metadata for https://marketplace.visualstudio.com/items?itemName=JaredParMSFT.VsVim
 62%|██████▏   | 165/265 [07:47<00:51,  1.94it/s]INFO:__main__:Requesting https://www.lowtechmagazine.com/2019/02/heat-your-house-with-a-water-brake-windmill.html
INFO:__main__:Getting metadata for https://www.lowtechmagazine.com/2019/02/heat-your-house-with-a-water-brake-windmill.html
 63%|██████▎   | 166/265 [07:48<01:00,  1.65it/s]INFO:__main__:Requesting https://dothemath.ucsd.edu/2012/06/heat-pumps-work-miracles/
INFO:__main__:Getting metadata for https://dothemath.ucsd.edu/2012/06/heat-pumps-work-miracles/
 63%|██████▎   | 167/265 [07:51<02:08,  1.31s/it]INFO:__main__:Requesting https://russell.ballestrini.net/hybrid-hot-water-heater-saves-69-percent-on-energy-consumption/
INFO:__main__:Getting metadata for https://russell.ballestrini.net/hybrid-hot-water-heater-saves-69-percent-on-energy-consumption/
 63%|██████▎   | 168/265 [07:52<02:04,  1.29s/it]INFO:__main__:Requesting http://processengineering.co.uk/article/2019233/maximum-suction
INFO:__main__:Getting metadata for http://processengineering.co.uk/article/2019233/maximum-suction
 64%|██████▍   | 169/265 [07:56<03:12,  2.00s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Beaufort_scale#Modern_scale
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Beaufort_scale#Modern_scale
 64%|██████▍   | 170/265 [07:57<02:46,  1.75s/it]INFO:__main__:Requesting http://www.wind-power-program.com/wind_statistics.htm
INFO:__main__:Getting metadata for http://www.wind-power-program.com/wind_statistics.htm
 65%|██████▍   | 171/265 [07:59<02:43,  1.74s/it]INFO:__main__:Requesting https://www.energy.gov/eere/solar/articles/solar-radiation-basics
 65%|██████▍   | 172/265 [07:59<01:58,  1.27s/it]INFO:__main__:Requesting https://www.nrel.gov/gis/images/map_pv_us_january_dec2008.jpg
INFO:__main__:Getting metadata for https://www.nrel.gov/gis/images/map_pv_us_january_dec2008.jpg
ERROR:__main__:Could not get metadata for https://www.nrel.gov/gis/images/map_pv_us_january_dec2008.jpg
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 65%|██████▌   | 173/265 [08:04<03:46,  2.46s/it]INFO:__main__:Requesting https://www.nrel.gov/gis/images/map_pv_us_july_dec2008.jpg
INFO:__main__:Getting metadata for https://www.nrel.gov/gis/images/map_pv_us_july_dec2008.jpg
ERROR:__main__:Could not get metadata for https://www.nrel.gov/gis/images/map_pv_us_july_dec2008.jpg
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 66%|██████▌   | 174/265 [08:09<04:56,  3.26s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Heat_pump
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Heat_pump
 66%|██████▌   | 175/265 [08:10<03:58,  2.65s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Mechanical_equivalent_of_heat
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Mechanical_equivalent_of_heat
 66%|██████▋   | 176/265 [08:11<03:06,  2.10s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=GjcOobt9Ef8
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=GjcOobt9Ef8
 67%|██████▋   | 177/265 [08:12<02:33,  1.75s/it]INFO:__main__:Requesting https://commons.wikimedia.org/wiki/File:Joule_Apparatus.jpg
INFO:__main__:Getting metadata for https://commons.wikimedia.org/wiki/File:Joule_Apparatus.jpg
 67%|██████▋   | 178/265 [08:13<02:04,  1.43s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Great_Molasses_Flood
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Great_Molasses_Flood
 68%|██████▊   | 179/265 [08:14<01:58,  1.37s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Electromigration
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Electromigration
 68%|██████▊   | 180/265 [08:15<01:54,  1.35s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/District_heating
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/District_heating
 68%|██████▊   | 181/265 [08:17<02:09,  1.54s/it]INFO:__main__:Requesting https://www.lowtechmagazine.com/2013/03/the-mechanical-transmission-of-power-3-wire-ropes.html
INFO:__main__:Getting metadata for https://www.lowtechmagazine.com/2013/03/the-mechanical-transmission-of-power-3-wire-ropes.html
 69%|██████▊   | 182/265 [08:19<02:23,  1.72s/it]INFO:__main__:Requesting https://jacquesmattheij.com/how-to-build-a-windmill/
INFO:__main__:Getting metadata for https://jacquesmattheij.com/how-to-build-a-windmill/
 69%|██████▉   | 183/265 [08:22<02:48,  2.06s/it]INFO:__main__:Requesting https://web.archive.org/web/20160813143636/http://www.jacquesmattheij.com/how-to-build-a-windmill
INFO:__main__:Getting metadata for https://web.archive.org/web/20160813143636/http://www.jacquesmattheij.com/how-to-build-a-windmill
ERROR:__main__:Could not get metadata for https://web.archive.org/web/20160813143636/http://www.jacquesmattheij.com/how-to-build-a-windmill
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7ff816e5def0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160813143636/http://www.jacquesmattheij.com/how-to-build-a-windmill (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff816e5def0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='web.archive.org', port=443): Max retries exceeded with url: /web/20160813143636/http://www.jacquesmattheij.com/how-to-build-a-windmill (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff816e5def0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 199, in web_preview
    s = Schema(url, ['name', 'description', 'image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 183, in __init__
    super(Schema, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
 69%|██████▉   | 184/265 [10:31<54:02, 40.04s/it]INFO:__main__:Requesting https://solar.lowtechmagazine.com/2019/02/heat-your-house-with-a-water-brake-windmill.html
INFO:__main__:Getting metadata for https://solar.lowtechmagazine.com/2019/02/heat-your-house-with-a-water-brake-windmill.html
 70%|██████▉   | 185/265 [10:33<37:59, 28.50s/it]INFO:__main__:Requesting https://solar.lowtechmagazine.com/about/
INFO:__main__:Getting metadata for https://solar.lowtechmagazine.com/about/
 70%|███████   | 186/265 [10:34<27:01, 20.53s/it]INFO:__main__:Requesting http://insideenergy.org/2016/06/20/ie-questions-can-we-turn-power-plants-wasted-heat-into-power/
INFO:__main__:Getting metadata for http://insideenergy.org/2016/06/20/ie-questions-can-we-turn-power-plants-wasted-heat-into-power/
 71%|███████   | 187/265 [10:35<18:46, 14.45s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Vortex_tube
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Vortex_tube
 71%|███████   | 188/265 [10:36<13:22, 10.42s/it]INFO:__main__:Requesting https://aleksandarmilicevic.github.io/hola/
INFO:__main__:Getting metadata for https://aleksandarmilicevic.github.io/hola/
 71%|███████▏  | 189/265 [10:37<09:33,  7.54s/it]INFO:__main__:Requesting http://alloy.lcs.mit.edu/alloy/index.html
INFO:__main__:Getting metadata for http://alloy.lcs.mit.edu/alloy/index.html
ERROR:__main__:Could not get metadata for http://alloy.lcs.mit.edu/alloy/index.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 72%|███████▏  | 190/265 [10:37<06:49,  5.47s/it]INFO:__main__:Requesting https://www.hillelwayne.com/tags/alloy/
INFO:__main__:Getting metadata for https://www.hillelwayne.com/tags/alloy/
ERROR:__main__:Could not get metadata for https://www.hillelwayne.com/tags/alloy/
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 72%|███████▏  | 191/265 [10:38<04:53,  3.96s/it]INFO:__main__:Requesting https://faculty.nps.edu/ncrowe/book/chap14.html
INFO:__main__:Getting metadata for https://faculty.nps.edu/ncrowe/book/chap14.html
ERROR:__main__:Could not get metadata for https://faculty.nps.edu/ncrowe/book/chap14.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 72%|███████▏  | 192/265 [10:39<03:58,  3.26s/it]INFO:__main__:Requesting http://www.gprolog.org/manual/html_node/gprolog054.html
INFO:__main__:Getting metadata for http://www.gprolog.org/manual/html_node/gprolog054.html
ERROR:__main__:Could not get metadata for http://www.gprolog.org/manual/html_node/gprolog054.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 73%|███████▎  | 193/265 [10:41<03:14,  2.70s/it]INFO:__main__:Requesting https://redislabs.com/blog/redis-turns-10/
INFO:__main__:Getting metadata for https://redislabs.com/blog/redis-turns-10/
 73%|███████▎  | 194/265 [10:42<02:36,  2.21s/it]INFO:__main__:Requesting http://www.oss4gov.org/manifesto
INFO:__main__:Getting metadata for http://oss4gov.org/manifesto
 74%|███████▎  | 195/265 [10:44<02:26,  2.09s/it]INFO:__main__:Requesting https://18f.gsa.gov/
INFO:__main__:Getting metadata for https://18f.gsa.gov
 74%|███████▍  | 196/265 [10:44<01:48,  1.58s/it]INFO:__main__:Requesting https://18f.gsa.gov/open-source-policy/
INFO:__main__:Getting metadata for https://18f.gsa.gov/open-source-policy/
 74%|███████▍  | 197/265 [10:44<01:21,  1.20s/it]INFO:__main__:Requesting https://github.com/18F
INFO:__main__:Getting metadata for https://github.com/18F
 75%|███████▍  | 198/265 [10:46<01:25,  1.27s/it]INFO:__main__:Requesting https://news.ycombinator.com/front?day=2009-02-25
INFO:__main__:Getting metadata for https://news.ycombinator.com/front?day=2009-02-25
ERROR:__main__:Could not get metadata for https://news.ycombinator.com/front?day=2009-02-25
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 75%|███████▌  | 199/265 [10:48<01:52,  1.70s/it]INFO:__main__:Requesting https://news.ycombinator.com/front?day=2019-02-25
INFO:__main__:Getting metadata for https://news.ycombinator.com/front?day=2019-02-25
ERROR:__main__:Could not get metadata for https://news.ycombinator.com/front?day=2019-02-25
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 75%|███████▌  | 200/265 [10:52<02:22,  2.19s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Relational_algebra
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Relational_algebra
 76%|███████▌  | 201/265 [10:54<02:23,  2.24s/it]INFO:__main__:Requesting http://antirez.com/news/122
INFO:__main__:Getting metadata for http://antirez.com/news/122
ERROR:__main__:Could not get metadata for http://antirez.com/news/122
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 76%|███████▌  | 202/265 [10:55<02:00,  1.91s/it]INFO:__main__:Requesting https://gist.github.com/antirez/6ca04dd191bdb82aad9fb241013e88a8
INFO:__main__:Getting metadata for https://gist.github.com/antirez/6ca04dd191bdb82aad9fb241013e88a8
 77%|███████▋  | 203/265 [10:56<01:39,  1.60s/it]INFO:__main__:Requesting https://redis.io/topics/pubsub
INFO:__main__:Getting metadata for https://redis.io/topics/pubsub
 77%|███████▋  | 204/265 [10:58<01:46,  1.75s/it]INFO:__main__:Requesting https://www.pearson.com/us/higher-education/program/Ousterhout-Tcl-and-the-Tk-Toolkit-2nd-Edition/PGM23076.html
INFO:__main__:Getting metadata for https://www.pearson.com/us/higher-education/program/Ousterhout-Tcl-and-the-Tk-Toolkit-2nd-Edition/PGM23076.html
ERROR:__main__:Could not get metadata for https://www.pearson.com/us/higher-education/program/Ousterhout-Tcl-and-the-Tk-Toolkit-2nd-Edition/PGM23076.html
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 195, in web_preview
    content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 174, in __init__
    super(TwitterCard, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 132, in __init__
    self._set_properties()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 152, in _set_properties
    if property_meta and property_meta['content'] != "":
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/bs4/element.py", line 1016, in __getitem__
    return self.attrs[key]
KeyError: 'content'
 77%|███████▋  | 205/265 [10:59<01:34,  1.58s/it]INFO:__main__:Requesting https://tcl.apache.org/rivet/
INFO:__main__:Getting metadata for https://tcl.apache.org/rivet/
 78%|███████▊  | 206/265 [11:00<01:20,  1.36s/it]INFO:__main__:Requesting http://antirez.com/articoli/tclmisunderstood.html
INFO:__main__:Getting metadata for http://antirez.com/articoli/tclmisunderstood.html
 78%|███████▊  | 207/265 [11:01<01:13,  1.27s/it]INFO:__main__:Requesting http://jim.tcl.tk/index.html/doc/www/www/index.html
INFO:__main__:Getting metadata for http://jim.tcl.tk/index.html/doc/www/www/index.html
 78%|███████▊  | 208/265 [11:02<00:58,  1.02s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/D._Richard_Hipp
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/D._Richard_Hipp
 79%|███████▉  | 209/265 [11:02<00:51,  1.08it/s]INFO:__main__:Requesting https://www.tcl.tk/community/tcl2017/assets/talk93/Paper.html
INFO:__main__:Getting metadata for https://www.tcl.tk/community/tcl2017/assets/talk93/Paper.html
 79%|███████▉  | 210/265 [11:03<00:50,  1.08it/s]INFO:__main__:Requesting https://www.dbms2.com/2008/02/18/mike-stonebraker-calls-for-the-complete-destruction-of-the-old-dbms-order/
INFO:__main__:Getting metadata for https://www.dbms2.com/2008/02/18/mike-stonebraker-calls-for-the-complete-destruction-of-the-old-dbms-order/
 80%|███████▉  | 211/265 [11:07<01:37,  1.81s/it]INFO:__main__:Requesting https://www.imperva.com/blog/rediswannamine-new-redis-nsa-powered-cryptojacking-attack/
INFO:__main__:Getting metadata for https://www.imperva.com/blog/rediswannamine-new-redis-nsa-powered-cryptojacking-attack/
 80%|████████  | 212/265 [11:08<01:26,  1.64s/it]INFO:__main__:Requesting https://www.bleepingcomputer.com/news/security/around-75-percent-of-open-redis-servers-are-infected-with-malware/
INFO:__main__:Getting metadata for https://www.bleepingcomputer.com/news/security/around-75-percent-of-open-redis-servers-are-infected-with-malware/
 80%|████████  | 213/265 [11:10<01:18,  1.51s/it]INFO:__main__:Requesting http://www.kylheku.com/cgit/txr/tree/linenoise
INFO:__main__:Getting metadata for http://www.kylheku.com/cgit/txr/tree/linenoise
ERROR:__main__:Could not get metadata for http://www.kylheku.com/cgit/txr/tree/linenoise
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 81%|████████  | 214/265 [11:11<01:07,  1.33s/it]INFO:__main__:Requesting http://nongnu.org/txr/txr-manpage.html#N-025AAA27
INFO:__main__:Getting metadata for http://nongnu.org/txr/txr-manpage.html#N-025AAA27
ERROR:__main__:Could not get metadata for http://nongnu.org/txr/txr-manpage.html#N-025AAA27
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 81%|████████  | 215/265 [12:35<21:49, 26.19s/it]INFO:__main__:Requesting http://antirez.com/news/96
INFO:__main__:Getting metadata for http://antirez.com/news/96
ERROR:__main__:Could not get metadata for http://antirez.com/news/96
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 82%|████████▏ | 216/265 [12:36<15:14, 18.66s/it]INFO:__main__:Requesting https://goodformcode.com
INFO:__main__:Getting metadata for https://goodformcode.com
 82%|████████▏ | 217/265 [12:36<10:30, 13.14s/it]INFO:__main__:Requesting https://redalemeden.com/blog/2019/we-need-chrome-no-more
INFO:__main__:Getting metadata for https://redalemeden.com/blog/2019/we-need-chrome-no-more/
 82%|████████▏ | 218/265 [12:37<07:25,  9.48s/it]INFO:__main__:Requesting https://news.softpedia.com/news/Lead-Firebug-Developer-Joins-Google-Chrome-Team-212278.shtml
INFO:__main__:Getting metadata for https://news.softpedia.com/news/Lead-Firebug-Developer-Joins-Google-Chrome-Team-212278.shtml
 83%|████████▎ | 219/265 [12:44<06:35,  8.60s/it]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=885508#c49
 83%|████████▎ | 220/265 [12:44<04:34,  6.11s/it]INFO:__main__:Requesting https://blog.nightly.mozilla.org/2019/01/31/these-weeks-in-firefox-issue-52/
INFO:__main__:Getting metadata for https://blog.nightly.mozilla.org/2019/01/31/these-weeks-in-firefox-issue-52/
 83%|████████▎ | 221/265 [12:44<03:15,  4.43s/it]INFO:__main__:Requesting https://9to5google.com/2018/12/03/microsoft-chrome-based-browser/
INFO:__main__:Getting metadata for https://9to5google.com/2018/12/03/microsoft-chrome-based-browser/
 84%|████████▍ | 222/265 [12:45<02:20,  3.27s/it]INFO:__main__:Requesting https://www.cnet.com/news/why-i-switched-from-firefox-to-chrome/
INFO:__main__:Getting metadata for https://www.cnet.com/news/why-i-switched-from-firefox-to-chrome/
 84%|████████▍ | 223/265 [12:46<01:49,  2.62s/it]INFO:__main__:Requesting https://imgur.com/a/uyBcxI0
INFO:__main__:Getting metadata for https://imgur.com/a/uyBcxI0
ERROR:__main__:Could not get metadata for https://imgur.com/a/uyBcxI0
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 85%|████████▍ | 224/265 [12:46<01:18,  1.90s/it]INFO:__main__:Requesting https://imgur.com/gallery/WWZxj
INFO:__main__:Getting metadata for https://imgur.com/gallery/WWZxj
 85%|████████▍ | 225/265 [12:47<00:56,  1.40s/it]INFO:__main__:Requesting https://www.google.com/googlebooks/chrome/
INFO:__main__:Getting metadata for https://www.google.com/googlebooks/chrome/
 85%|████████▌ | 226/265 [12:47<00:39,  1.02s/it]INFO:__main__:Requesting https://googleblog.blogspot.com/2008/09/fresh-take-on-browser.html
INFO:__main__:Getting metadata for https://googleblog.blogspot.com/2008/09/fresh-take-on-browser.html
 86%|████████▌ | 227/265 [12:47<00:30,  1.26it/s]INFO:__main__:Requesting https://getpolarized.io/
INFO:__main__:Getting metadata for https://getpolarized.io
 86%|████████▌ | 228/265 [12:47<00:24,  1.50it/s]INFO:__main__:Requesting https://developers.google.com/web/updates/2019/01/devtools
INFO:__main__:Getting metadata for https://developers.google.com/web/updates/2019/01/devtools
 86%|████████▋ | 229/265 [12:48<00:27,  1.29it/s]INFO:__main__:Requesting https://developers.google.com/web/updates/2018/05/devtools
INFO:__main__:Getting metadata for https://developers.google.com/web/updates/2018/05/devtools
 87%|████████▋ | 230/265 [12:49<00:28,  1.21it/s]INFO:__main__:Requesting https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_grid_layouts
INFO:__main__:Getting metadata for https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_grid_layouts
 87%|████████▋ | 231/265 [12:50<00:26,  1.26it/s]INFO:__main__:Requesting https://websocket.org/echo.html
INFO:__main__:Getting metadata for https://websocket.org/echo.html
 88%|████████▊ | 232/265 [12:51<00:27,  1.19it/s]INFO:__main__:Requesting https://www.xkcd.com/1053/
INFO:__main__:Getting metadata for https://www.xkcd.com/1053/
 88%|████████▊ | 233/265 [12:52<00:24,  1.33it/s]INFO:__main__:Requesting https://screenshots.firefox.com/
INFO:__main__:Getting metadata for https://screenshots.firefox.com
 88%|████████▊ | 234/265 [12:52<00:21,  1.43it/s]INFO:__main__:Requesting https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/
INFO:__main__:Getting metadata for https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/
 89%|████████▊ | 235/265 [12:53<00:18,  1.61it/s]INFO:__main__:Requesting https://www.joelonsoftware.com/2008/03/17/martian-headsets/
INFO:__main__:Getting metadata for https://www.joelonsoftware.com/2008/03/17/martian-headsets/
 89%|████████▉ | 236/265 [12:54<00:25,  1.16it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Internet_Explorer#/media/File:Internet-explorer-usage-data.svg
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Internet_Explorer#/media/File:Internet-explorer-usage-data.svg
 89%|████████▉ | 237/265 [12:57<00:45,  1.63s/it]INFO:__main__:Requesting http://gs.statcounter.com/browser-market-share#monthly-200901-201902
INFO:__main__:Getting metadata for http://gs.statcounter.com/browser-market-share#monthly-200901-201902
 90%|████████▉ | 238/265 [12:58<00:39,  1.46s/it]INFO:__main__:Requesting https://support.mozilla.org/en-US/questions/1206101
INFO:__main__:Getting metadata for https://support.mozilla.org/en-US/questions/1206101
 90%|█████████ | 239/265 [13:01<00:44,  1.73s/it]INFO:__main__:Requesting https://github.com/chromium/chromium
INFO:__main__:Getting metadata for https://github.com/chromium/chromium
 91%|█████████ | 240/265 [13:02<00:37,  1.50s/it]INFO:__main__:Requesting https://github.com/mozilla/gecko-dev
INFO:__main__:Getting metadata for https://github.com/mozilla/gecko-dev
 91%|█████████ | 241/265 [13:03<00:32,  1.35s/it]INFO:__main__:Requesting https://developer.microsoft.com/en-us/windows/pwa
INFO:__main__:Getting metadata for https://developer.microsoft.com/en-us/windows/pwa
 91%|█████████▏| 242/265 [13:06<00:42,  1.84s/it]INFO:__main__:Requesting https://github.com/nodejs/node-chakracore
INFO:__main__:Getting metadata for https://github.com/nodejs/node-chakracore
 92%|█████████▏| 243/265 [13:07<00:34,  1.56s/it]INFO:__main__:Requesting https://github.com/Microsoft/ChakraCore/issues/5865
INFO:__main__:Getting metadata for https://github.com/Microsoft/ChakraCore/issues/5865
 92%|█████████▏| 244/265 [13:10<00:45,  2.15s/it]INFO:__main__:Requesting https://pianop.ly/
INFO:__main__:Getting metadata for https://pianop.ly
ERROR:__main__:Could not get metadata for https://pianop.ly
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 92%|█████████▏| 245/265 [13:11<00:37,  1.89s/it]INFO:__main__:Requesting https://www.cnet.com/news/google-firefox-search-deal-gives-mozilla-more-money-to-push-privacy/
INFO:__main__:Getting metadata for https://www.cnet.com/news/google-firefox-search-deal-gives-mozilla-more-money-to-push-privacy/
 93%|█████████▎| 246/265 [13:12<00:30,  1.59s/it]INFO:__main__:Requesting https://bugzilla.mozilla.org/show_bug.cgi?id=85601
 93%|█████████▎| 247/265 [13:13<00:21,  1.18s/it]INFO:__main__:Requesting https://www.adsoftheworld.com/media/film/google_chrome_speed_tests
INFO:__main__:Getting metadata for https://www.adsoftheworld.com/media/film/google_chrome_speed_tests
ERROR:__main__:Could not get metadata for https://www.adsoftheworld.com/media/film/google_chrome_speed_tests
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 94%|█████████▎| 248/265 [13:14<00:22,  1.34s/it]INFO:__main__:Requesting https://imgur.com/a/eAOCL3J
INFO:__main__:Getting metadata for https://imgur.com/a/eAOCL3J
ERROR:__main__:Could not get metadata for https://imgur.com/a/eAOCL3J
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 94%|█████████▍| 249/265 [13:15<00:16,  1.02s/it]INFO:__main__:Requesting https://arstechnica.com/information-technology/2013/04/google-going-its-own-way-forking-webkit-rendering-engine/
INFO:__main__:Getting metadata for https://arstechnica.com/information-technology/2013/04/google-going-its-own-way-forking-webkit-rendering-engine/
 94%|█████████▍| 250/265 [13:15<00:11,  1.26it/s]INFO:__main__:Requesting https://blog.chromium.org/2013/04/blink-rendering-engine-for-chromium.html
INFO:__main__:Getting metadata for https://blog.chromium.org/2013/04/blink-rendering-engine-for-chromium.html
 95%|█████████▍| 251/265 [13:15<00:08,  1.57it/s]INFO:__main__:Requesting https://support.mozilla.org/en-US/kb/containers
INFO:__main__:Getting metadata for https://support.mozilla.org/en-US/kb/containers
 95%|█████████▌| 252/265 [13:17<00:12,  1.01it/s]INFO:__main__:Requesting https://www.qutebrowser.org
INFO:__main__:Getting metadata for https://www.qutebrowser.org
 95%|█████████▌| 253/265 [13:20<00:20,  1.74s/it]INFO:__main__:Requesting https://news.ycombinator.com
INFO:__main__:Getting metadata for https://news.ycombinator.com
ERROR:__main__:Could not get metadata for https://news.ycombinator.com
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 96%|█████████▌| 254/265 [13:23<00:21,  1.98s/it]INFO:__main__:Requesting https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/
INFO:__main__:Getting metadata for https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/
 96%|█████████▌| 255/265 [13:24<00:17,  1.77s/it]INFO:__main__:Requesting https://support.brave.com/hc/en-us/articles/360017909112-How-can-I-add-extensions-to-Brave-
INFO:__main__:Getting metadata for https://support.brave.com/hc/en-us/articles/360017909112-How-can-I-add-extensions-to-Brave-
 97%|█████████▋| 256/265 [13:25<00:12,  1.44s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Chromium_(web_browser)#2008
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Chromium_(web_browser)#2008
 97%|█████████▋| 257/265 [13:27<00:13,  1.72s/it]INFO:__main__:Requesting https://alex.blog/2019/02/27/from-alexs-family/
INFO:__main__:Getting metadata for https://alex.blog/2019/02/27/from-alexs-family/
 97%|█████████▋| 258/265 [13:28<00:10,  1.50s/it]INFO:__main__:Requesting https://www.charitynavigator.org/index.cfm?bay=search.summary&orgid=8070
INFO:__main__:Getting metadata for https://www.charitynavigator.org/index.cfm?bay=search.summary&orgid=8070
 98%|█████████▊| 259/265 [13:29<00:07,  1.31s/it]INFO:__main__:Requesting https://www.allbloodcancers.org/donate
INFO:__main__:Getting metadata for https://www.allbloodcancers.org/donate
ERROR:__main__:Could not get metadata for https://www.allbloodcancers.org/donate
Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 94, in _get_site_title_and_description
    description = description[:450] + '...' if len(description) > 450 else description
TypeError: object of type 'NoneType' has no len()
 98%|█████████▊| 260/265 [13:32<00:08,  1.68s/it]INFO:__main__:Requesting https://bethematch.org/
INFO:__main__:Getting metadata for https://bethematch.org
 98%|█████████▊| 261/265 [13:34<00:07,  1.99s/it]INFO:__main__:Requesting https://github.com/Viper007Bond/vipers-video-quicktags-migrator/commits/master
INFO:__main__:Getting metadata for https://github.com/Viper007Bond/vipers-video-quicktags-migrator/commits/master
 99%|█████████▉| 262/265 [13:36<00:05,  1.91s/it]INFO:__main__:Requesting https://wptavern.com/alex-mills-ends-his-battle-with-leukemia
INFO:__main__:Getting metadata for https://wptavern.com/alex-mills-ends-his-battle-with-leukemia
 99%|█████████▉| 263/265 [13:38<00:03,  1.91s/it]INFO:__main__:Requesting https://alex.blog/2019/02/18/leukemia-has-won/
INFO:__main__:Getting metadata for https://alex.blog/2019/02/18/leukemia-has-won/
100%|█████████▉| 264/265 [13:39<00:01,  1.74s/it]INFO:__main__:Requesting https://lwn.net/SubscriberLink/780710/ece0f8b930151422/
INFO:__main__:Getting metadata for https://lwn.net/SubscriberLink/780710/ece0f8b930151422/
100%|██████████| 265/265 [13:40<00:00,  1.38s/it]
