INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  3%|▎         | 1/30 [00:00<00:09,  3.05it/s]  7%|▋         | 2/30 [00:00<00:07,  3.50it/s] 13%|█▎        | 4/30 [00:01<00:08,  3.05it/s] 17%|█▋        | 5/30 [00:02<00:14,  1.78it/s] 27%|██▋       | 8/30 [00:02<00:08,  2.46it/s] 30%|███       | 9/30 [00:02<00:06,  3.16it/s] 37%|███▋      | 11/30 [00:03<00:05,  3.69it/s] 40%|████      | 12/30 [00:04<00:09,  1.97it/s] 50%|█████     | 15/30 [00:04<00:05,  2.69it/s] 53%|█████▎    | 16/30 [00:06<00:14,  1.05s/it] 60%|██████    | 18/30 [00:07<00:09,  1.31it/s] 63%|██████▎   | 19/30 [00:08<00:09,  1.22it/s] 67%|██████▋   | 20/30 [00:08<00:07,  1.41it/s] 70%|███████   | 21/30 [00:08<00:04,  1.87it/s] 73%|███████▎  | 22/30 [00:08<00:03,  2.29it/s] 77%|███████▋  | 23/30 [00:09<00:04,  1.62it/s] 87%|████████▋ | 26/30 [00:09<00:01,  2.25it/s] 90%|█████████ | 27/30 [00:11<00:02,  1.23it/s] 93%|█████████▎| 28/30 [00:11<00:01,  1.64it/s] 97%|█████████▋| 29/30 [00:13<00:00,  1.05it/s]100%|██████████| 30/30 [00:13<00:00,  1.43it/s]
  0%|          | 0/180 [00:00<?, ?it/s]INFO:__main__:Requesting https://github.com/gotify
INFO:__main__:Getting metadata for https://github.com/gotify
  1%|          | 1/180 [00:01<04:50,  1.62s/it]INFO:__main__:Requesting https://pushover.net/
INFO:__main__:Getting metadata for https://pushover.net
  1%|          | 2/180 [00:02<04:28,  1.51s/it]INFO:__main__:Requesting https://github.com/huginn/huginn
INFO:__main__:Getting metadata for https://github.com/huginn/huginn
  2%|▏         | 3/180 [00:03<03:59,  1.35s/it]INFO:__main__:Requesting https://gotify.net/
INFO:__main__:Getting metadata for https://gotify.net
  2%|▏         | 4/180 [00:04<02:56,  1.01s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Push_technology
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Push_technology
  3%|▎         | 5/180 [00:05<03:05,  1.06s/it]INFO:__main__:Requesting https://gotify.net/api-docs#/message/streamMessages
INFO:__main__:Getting metadata for https://gotify.net/api-docs#/message/streamMessages
  3%|▎         | 6/180 [00:05<02:28,  1.17it/s]INFO:__main__:Requesting https://github.com/gotify/server/issues/87
INFO:__main__:Getting metadata for https://github.com/gotify/server/issues/87
  4%|▍         | 7/180 [00:06<02:48,  1.03it/s]INFO:__main__:Requesting https://www.tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html
INFO:__main__:Getting metadata for https://www.tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html
  4%|▍         | 8/180 [00:08<03:11,  1.11s/it]INFO:__main__:Requesting https://blog.golang.org/gopher
INFO:__main__:Getting metadata for https://blog.golang.org/gopher
  5%|▌         | 9/180 [00:08<02:25,  1.18it/s]INFO:__main__:Requesting https://github.com/pirate/ArchiveBox
INFO:__main__:Getting metadata for https://github.com/pirate/ArchiveBox
  6%|▌         | 10/180 [00:09<02:31,  1.12it/s]INFO:__main__:Requesting https://launchaco.com
INFO:__main__:Getting metadata for https://www.launchaco.com
  6%|▌         | 11/180 [00:10<02:12,  1.28it/s]INFO:__main__:Requesting https://github.com/pirate/ArchiveBox/wiki/Configuration
INFO:__main__:Getting metadata for https://github.com/pirate/ArchiveBox/wiki/Configuration
  7%|▋         | 12/180 [00:10<02:07,  1.31it/s]INFO:__main__:Requesting https://github.com/ArchiveTeam/grab-site
INFO:__main__:Getting metadata for https://github.com/ArchiveTeam/grab-site
  7%|▋         | 13/180 [00:11<02:17,  1.22it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Web_ARChive
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Web_ARChive
  8%|▊         | 14/180 [00:12<02:12,  1.25it/s]INFO:__main__:Requesting https://www.loc.gov/preservation/digital/formats/fdd/fdd000236.shtml
INFO:__main__:Getting metadata for https://www.loc.gov/preservation/digital/formats/fdd/fdd000236.shtml
  8%|▊         | 15/180 [00:14<03:16,  1.19s/it]INFO:__main__:Requesting https://github.com/pirate/ArchiveBox/blob/a74d8410f4c3f2f08f75f223c15f8615be85744f/archivebox/archive_methods.py#L208
INFO:__main__:Getting metadata for https://github.com/pirate/ArchiveBox/blob/a74d8410f4c3f2f08f75f223c15f8615be85744f/archivebox/archive_methods.py#L208
  9%|▉         | 16/180 [00:15<03:05,  1.13s/it]INFO:__main__:Requesting https://github.com/webrecorder/pywb
INFO:__main__:Getting metadata for https://github.com/webrecorder/pywb
  9%|▉         | 17/180 [00:16<03:03,  1.13s/it]INFO:__main__:Requesting http://davidad.github.io/blog/2014/04/24/an-osi-layer-model-for-the-21st-century/
INFO:__main__:Getting metadata for http://davidad.github.io/blog/2014/04/24/an-osi-layer-model-for-the-21st-century/
 10%|█         | 18/180 [00:16<02:21,  1.14it/s]INFO:__main__:Requesting https://hackaday.com/2019/03/09/speedrunning-windows-95/
ERROR:__main__:Could not reach https://hackaday.com/2019/03/09/speedrunning-windows-95/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 11%|█         | 19/180 [00:17<01:46,  1.51it/s]INFO:__main__:Requesting https://mobile.twitter.com/Foone/status/1103384684812255233
INFO:__main__:Getting metadata for https://mobile.twitter.com/Foone/status/1103384684812255233
 11%|█         | 20/180 [00:18<02:37,  1.01it/s]INFO:__main__:Requesting https://www.speedrun.com/cp#Banned
INFO:__main__:Getting metadata for https://www.speedrun.com/cp#Banned
 12%|█▏        | 21/180 [00:20<03:01,  1.14s/it]INFO:__main__:Requesting https://www.pcgamer.com/getting-banned-from-club-penguin-is-now-a-speedrunning-competition/
INFO:__main__:Getting metadata for https://www.pcgamer.com/getting-banned-from-club-penguin-is-now-a-speedrunning-competition/
 12%|█▏        | 22/180 [00:21<03:00,  1.14s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/NetBIOS_Frames_protocol
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/NetBIOS_Frames_protocol
 13%|█▎        | 23/180 [00:22<02:47,  1.06s/it]INFO:__main__:Requesting https://news.vice.com/en_us/article/7xakd9/windows-31-is-still-alive-and-it-just-killed-a-french-airport
INFO:__main__:Getting metadata for https://news.vice.com/en_us/article/7xakd9/windows-31-is-still-alive-and-it-just-killed-a-french-airport
 13%|█▎        | 24/180 [00:22<02:06,  1.24it/s]INFO:__main__:Requesting https://arstechnica.com/information-technology/2017/05/in-a-throwback-to-the-90s-ntfs-bug-lets-anyone-hang-or-crash-windows-7-8-1/
INFO:__main__:Getting metadata for https://arstechnica.com/information-technology/2017/05/in-a-throwback-to-the-90s-ntfs-bug-lets-anyone-hang-or-crash-windows-7-8-1/
 14%|█▍        | 25/180 [00:22<01:42,  1.52it/s]INFO:__main__:Requesting https://msfn.org/board/topic/141402-windows-95-21ghz-cpu-limit-broken/
INFO:__main__:Getting metadata for https://msfn.org/board/topic/141402-windows-95-21ghz-cpu-limit-broken/
 14%|█▍        | 26/180 [00:24<02:30,  1.03it/s]INFO:__main__:Requesting https://xkcd.com/284/
INFO:__main__:Getting metadata for https://xkcd.com/284/
 15%|█▌        | 27/180 [00:25<02:02,  1.25it/s]INFO:__main__:Requesting https://github.com/LiveSplit/LiveSplit/blob/master/Documentation/Auto-Splitters.md
INFO:__main__:Getting metadata for https://github.com/LiveSplit/LiveSplit/blob/master/Documentation/Auto-Splitters.md
 16%|█▌        | 28/180 [00:25<01:59,  1.28it/s]INFO:__main__:Requesting http://www.annoyances.org/
INFO:__main__:Getting metadata for http://www.annoyances.org
 16%|█▌        | 29/180 [00:26<01:32,  1.63it/s]INFO:__main__:Requesting https://www.litepc.com/
INFO:__main__:Getting metadata for https://www.litepc.com
 17%|█▋        | 30/180 [00:30<04:06,  1.65s/it]INFO:__main__:Requesting https://forums.virtualbox.org/viewtopic.php?t=82787
INFO:__main__:Getting metadata for https://forums.virtualbox.org/viewtopic.php?t=82787
 17%|█▋        | 31/180 [00:32<05:00,  2.01s/it]INFO:__main__:Requesting https://github.com/CypherpunkArmory/UserLAnd
INFO:__main__:Getting metadata for https://github.com/CypherpunkArmory/UserLAnd
 18%|█▊        | 32/180 [00:33<04:06,  1.67s/it]INFO:__main__:Requesting https://wiki.termux.com/wiki/Main_Page
INFO:__main__:Getting metadata for https://wiki.termux.com/wiki/Main_Page
 18%|█▊        | 33/180 [00:37<05:27,  2.23s/it]INFO:__main__:Requesting https://github.com/termux/termux-app
INFO:__main__:Getting metadata for https://github.com/termux/termux-app
 19%|█▉        | 34/180 [00:38<04:35,  1.89s/it]INFO:__main__:Requesting https://www.reddit.com/r/termux/
INFO:__main__:Getting metadata for https://www.reddit.com/r/termux/
 19%|█▉        | 35/180 [00:39<04:07,  1.70s/it]INFO:__main__:Requesting https://github.com/termux/termux-app/issues/954#issuecomment-448199494
INFO:__main__:Getting metadata for https://github.com/termux/termux-app/issues/954#issuecomment-448199494
 20%|██        | 36/180 [00:41<03:52,  1.62s/it]INFO:__main__:Requesting https://github.com/sp4rkie/debian-on-termux
INFO:__main__:Getting metadata for https://github.com/sp4rkie/debian-on-termux
 21%|██        | 37/180 [00:41<03:09,  1.33s/it]INFO:__main__:Requesting https://github.com/its-pointless/gcc_termux
INFO:__main__:Getting metadata for https://github.com/its-pointless/gcc_termux
 21%|██        | 38/180 [00:42<02:53,  1.22s/it]INFO:__main__:Requesting https://play.google.com/store/apps/details?id=org.connectbot
INFO:__main__:Getting metadata for https://play.google.com/store/apps/details?id=org.connectbot
 22%|██▏       | 39/180 [00:43<02:24,  1.03s/it]INFO:__main__:Requesting https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard
INFO:__main__:Getting metadata for https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard
 22%|██▏       | 40/180 [00:43<02:05,  1.11it/s]INFO:__main__:Requesting https://browser.geekbench.com/android_devices/839
INFO:__main__:Getting metadata for https://browser.geekbench.com/android_devices/839
 23%|██▎       | 41/180 [00:49<05:10,  2.24s/it]INFO:__main__:Requesting https://browser.geekbench.com/processors/2294
INFO:__main__:Getting metadata for https://browser.geekbench.com/processors/2294
 23%|██▎       | 42/180 [00:54<07:19,  3.19s/it]INFO:__main__:Requesting https://browser.geekbench.com/processors/763
INFO:__main__:Getting metadata for https://browser.geekbench.com/processors/763
 24%|██▍       | 43/180 [00:58<07:37,  3.34s/it]INFO:__main__:Requesting https://www.samsung.com/semiconductor/insights/tech-trends/emmc-to-ufs-how-nand-memory-for-mobile-products-is-evolving/
INFO:__main__:Getting metadata for https://www.samsung.com/semiconductor/insights/tech-trends/emmc-to-ufs-how-nand-memory-for-mobile-products-is-evolving/
 24%|██▍       | 44/180 [00:58<05:34,  2.46s/it]INFO:__main__:Requesting https://maruos.com
INFO:__main__:Getting metadata for https://maruos.com
 25%|██▌       | 45/180 [01:00<04:45,  2.12s/it]INFO:__main__:Requesting https://www.microsoft.com/en-gb/windows/continuum
INFO:__main__:Getting metadata for https://www.microsoft.com/en-gb/windows/continuum
 26%|██▌       | 46/180 [01:01<04:06,  1.84s/it]INFO:__main__:Requesting https://ubports.com/
INFO:__main__:Getting metadata for https://ubports.com
 26%|██▌       | 47/180 [01:03<04:20,  1.96s/it]INFO:__main__:Requesting https://github.com/louisdh/openterm
INFO:__main__:Getting metadata for https://github.com/louisdh/openterm
 27%|██▋       | 48/180 [01:04<03:37,  1.65s/it]INFO:__main__:Requesting https://github.com/ColdGrub1384/LibTerm/blob/master/README.md
INFO:__main__:Getting metadata for https://github.com/ColdGrub1384/LibTerm/blob/master/README.md
 27%|██▋       | 49/180 [01:05<03:03,  1.40s/it]INFO:__main__:Requesting https://github.com/tbodt/ish
INFO:__main__:Getting metadata for https://github.com/tbodt/ish
 28%|██▊       | 50/180 [01:06<02:41,  1.24s/it]INFO:__main__:Requesting https://github.com/fsquillace/junest
INFO:__main__:Getting metadata for https://github.com/fsquillace/junest
 28%|██▊       | 51/180 [01:07<02:26,  1.14s/it]INFO:__main__:Requesting https://liliputing.com/2018/07/gpd-pocket-2-preview.html
INFO:__main__:Getting metadata for https://liliputing.com/2018/07/gpd-pocket-2-preview.html
 29%|██▉       | 52/180 [01:07<01:48,  1.18it/s]INFO:__main__:Requesting https://github.com/termux/termux-packages/tree/master/packages
INFO:__main__:Getting metadata for https://github.com/termux/termux-packages/tree/master/packages
 29%|██▉       | 53/180 [01:09<02:39,  1.25s/it]INFO:__main__:Requesting http://www.bell-labs.com/usr/dmr/www/chist.html
INFO:__main__:Getting metadata for http://www.bell-labs.com/usr/dmr/www/chist.html
 30%|███       | 54/180 [01:10<02:29,  1.19s/it]INFO:__main__:Requesting https://www.thecut.com/2019/03/i-have-a-son-with-a-genetic-disease-and-im-pregnant.html
INFO:__main__:Getting metadata for https://www.thecut.com/2019/03/i-have-a-son-with-a-genetic-disease-and-im-pregnant.html
 31%|███       | 55/180 [01:10<02:01,  1.03it/s]INFO:__main__:Requesting https://pacman128.github.io/pcasm/
INFO:__main__:Getting metadata for https://pacman128.github.io/pcasm/
 31%|███       | 56/180 [01:11<01:38,  1.26it/s]INFO:__main__:Requesting https://twitter.com/x86instructions
INFO:__main__:Getting metadata for https://twitter.com/x86instructions
 32%|███▏      | 57/180 [01:14<03:00,  1.47s/it]INFO:__main__:Requesting https://www.sciencemag.org/news/2019/03/black-death-may-have-transformed-medieval-societies-sub-saharan-africa
INFO:__main__:Getting metadata for https://www.sciencemag.org/news/2019/03/black-death-may-have-transformed-medieval-societies-sub-saharan-africa
 32%|███▏      | 58/180 [01:14<02:24,  1.18s/it]INFO:__main__:Requesting https://flyingkmachines.wordpress.com/
ERROR:__main__:Could not reach https://flyingkmachines.wordpress.com/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 33%|███▎      | 59/180 [01:14<01:44,  1.15it/s]INFO:__main__:Requesting http://www.gingerybooks.com
INFO:__main__:Getting metadata for http://www.gingerybooks.com
 33%|███▎      | 60/180 [01:15<01:29,  1.34it/s]INFO:__main__:Requesting https://github.com/DeanRoddey/CIDLib#cidlib---a-c-development-environment
INFO:__main__:Getting metadata for https://github.com/DeanRoddey/CIDLib#cidlib---a-c-development-environment
 34%|███▍      | 61/180 [01:16<01:31,  1.31it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Object_request_broker
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Object_request_broker
 34%|███▍      | 62/180 [01:16<01:30,  1.30it/s]INFO:__main__:Requesting https://templeos.org/
INFO:__main__:Getting metadata for https://templeos.org
 35%|███▌      | 63/180 [01:21<03:24,  1.74s/it]INFO:__main__:Requesting https://www.youtube.com/playlist?list=PLJojk5z5q10SRUTLqEGfJwfm8gOuJR84l
INFO:__main__:Getting metadata for https://www.youtube.com/playlist?list=PLJojk5z5q10SRUTLqEGfJwfm8gOuJR84l
 36%|███▌      | 64/180 [01:21<02:49,  1.46s/it]INFO:__main__:Requesting https://stockquanta.com
INFO:__main__:Getting metadata for https://www.stockquanta.com
 36%|███▌      | 65/180 [01:22<02:30,  1.31s/it]INFO:__main__:Requesting https://coinquanta.com
INFO:__main__:Getting metadata for https://coinquanta.com
 37%|███▋      | 66/180 [01:23<02:10,  1.15s/it]INFO:__main__:Requesting https://medium.com/mudrex/managing-risk-while-trading-4c14553fa143
INFO:__main__:Getting metadata for https://medium.com/mudrex/managing-risk-while-trading-4c14553fa143
 37%|███▋      | 67/180 [01:24<01:49,  1.04it/s]INFO:__main__:Requesting https://medium.com/@kloudtrader/private-beta-and-kloudtrader-aural-c4a8561f70d0
INFO:__main__:Getting metadata for https://medium.com/@kloudtrader/private-beta-and-kloudtrader-aural-c4a8561f70d0
 38%|███▊      | 68/180 [01:24<01:31,  1.23it/s]INFO:__main__:Requesting https://kloudtrader.com
INFO:__main__:Getting metadata for https://www.kloudtrader.com
 38%|███▊      | 69/180 [01:25<01:37,  1.14it/s]INFO:__main__:Requesting https://github.com/topics/trading-strategies
INFO:__main__:Getting metadata for https://github.com/topics/trading-strategies
 39%|███▉      | 70/180 [01:28<02:33,  1.40s/it]INFO:__main__:Requesting https://medium.com/mudrex/tagged/learning
INFO:__main__:Getting metadata for https://medium.com/mudrex/tagged/learning
 39%|███▉      | 71/180 [01:28<02:10,  1.20s/it]INFO:__main__:Requesting https://mudrex.com/indicators
INFO:__main__:Getting metadata for https://mudrex.com/indicators
 40%|████      | 72/180 [01:29<01:55,  1.07s/it]INFO:__main__:Requesting https://www.blockchaintransparency.org/
INFO:__main__:Getting metadata for https://www.blockchaintransparency.org
 41%|████      | 73/180 [01:30<01:44,  1.03it/s]INFO:__main__:Requesting https://cgmnt-achilles-tortoise-piglet.netlify.com
INFO:__main__:Getting metadata for https://cgmnt-achilles-tortoise-piglet.netlify.com
 41%|████      | 74/180 [01:32<02:03,  1.17s/it]INFO:__main__:Requesting https://ruderich.org/simon/notes/append-only-backups-with-restic-and-rclone
INFO:__main__:Getting metadata for https://ruderich.org/simon/notes/append-only-backups-with-restic-and-rclone
 42%|████▏     | 75/180 [01:34<02:47,  1.60s/it]INFO:__main__:Requesting http://www.squidi.net/three/index.php
 42%|████▏     | 76/180 [01:34<02:01,  1.17s/it]INFO:__main__:Requesting http://www.squidi.net/three/entry.php?id=207
 43%|████▎     | 77/180 [01:34<01:27,  1.17it/s]INFO:__main__:Requesting https://techcrunch.com/2010/08/25/scvngr-game-mechanics/
ERROR:__main__:Could not reach https://techcrunch.com/2010/08/25/scvngr-game-mechanics/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 43%|████▎     | 78/180 [01:35<01:05,  1.57it/s]INFO:__main__:Requesting http://virt10.itu.chalmers.se/index.php
INFO:__main__:Getting metadata for http://virt10.itu.chalmers.se/index.php/Main_Page
 44%|████▍     | 79/180 [01:38<02:18,  1.37s/it]INFO:__main__:Requesting http://www.squidi.net/comic/amd/
INFO:__main__:Requesting https://twitter.com/joeerl/status/1104298407231922176
INFO:__main__:Getting metadata for https://twitter.com/joeerl/status/1104298407231922176
 45%|████▌     | 81/180 [01:39<01:50,  1.11s/it]INFO:__main__:Requesting https://twitter.com/devoncestes/status/1104000439987683328
INFO:__main__:Getting metadata for https://twitter.com/devoncestes/status/1104000439987683328
 46%|████▌     | 82/180 [01:40<01:41,  1.03s/it]INFO:__main__:Requesting http://paulgraham.com/avg.html
INFO:__main__:Getting metadata for http://paulgraham.com/avg.html
 46%|████▌     | 83/180 [01:41<02:02,  1.26s/it]INFO:__main__:Requesting https://www.activestate.com/resources/webinars/perl-paradox/
INFO:__main__:Getting metadata for https://www.activestate.com/resources/webinars/perl-paradox/
 47%|████▋     | 84/180 [01:42<01:42,  1.07s/it]INFO:__main__:Requesting https://twitter.com/guieevc/status/1002494428748140544
INFO:__main__:Getting metadata for https://twitter.com/guieevc/status/1002494428748140544
 47%|████▋     | 85/180 [01:43<01:38,  1.03s/it]INFO:__main__:Requesting https://www.ericsson.com/en/news/2018/5/erlang-celebrates-20-years-as-open-source
INFO:__main__:Getting metadata for https://www.ericsson.com/en/news/2018/5/erlang-celebrates-20-years-as-open-source
 48%|████▊     | 86/180 [01:44<01:38,  1.04s/it]INFO:__main__:Requesting https://jobs.ericsson.com/jobs?keywords=erlang&page=1
INFO:__main__:Getting metadata for https://jobs.ericsson.com/jobs?keywords=erlang&page=1
 48%|████▊     | 87/180 [01:45<01:42,  1.11s/it]INFO:__main__:Requesting https://www.linkedin.com/jobs/view/master-thesis-erlang-json-for-the-5g-core-network-at-ericsson-958913296/?originalSubdomain=se
 49%|████▉     | 88/180 [01:46<01:20,  1.14it/s]INFO:__main__:Requesting http://paulgraham.com/pypar.html
INFO:__main__:Getting metadata for http://paulgraham.com/pypar.html
 49%|████▉     | 89/180 [01:47<01:39,  1.09s/it]INFO:__main__:Requesting https://elixir-lang.org/getting-started/introduction.html
INFO:__main__:Getting metadata for https://elixir-lang.org/getting-started/introduction.html
 50%|█████     | 90/180 [01:47<01:14,  1.20it/s]INFO:__main__:Requesting https://www.scala-lang.org/old/node/11982
INFO:__main__:Getting metadata for https://www.scala-lang.org/old/node/11982
 51%|█████     | 91/180 [01:51<02:18,  1.55s/it]INFO:__main__:Requesting https://codestool.coding-gnome.com/courses/elixir-for-programmers
INFO:__main__:Getting metadata for https://codestool.coding-gnome.com/courses/elixir-for-programmers
 51%|█████     | 92/180 [01:51<01:58,  1.35s/it]INFO:__main__:Requesting https://github.com/elixirkoans/elixir-koans
INFO:__main__:Getting metadata for https://github.com/elixirkoans/elixir-koans
 52%|█████▏    | 93/180 [01:52<01:46,  1.23s/it]INFO:__main__:Requesting https://reasonml.github.io
INFO:__main__:Getting metadata for https://reasonml.github.io
 52%|█████▏    | 94/180 [01:53<01:18,  1.10it/s]INFO:__main__:Requesting https://learnyousomeerlang.com/recursion
INFO:__main__:Getting metadata for https://learnyousomeerlang.com/recursion
 53%|█████▎    | 95/180 [01:54<01:28,  1.04s/it]INFO:__main__:Requesting https://learnyousomeerlang.com/dialyzer
INFO:__main__:Getting metadata for https://learnyousomeerlang.com/dialyzer
 53%|█████▎    | 96/180 [01:56<01:44,  1.24s/it]INFO:__main__:Requesting http://wiki.c2.com/?SoftTyping
INFO:__main__:Getting metadata for http://wiki.c2.com/?SoftTyping
 54%|█████▍    | 97/180 [01:56<01:17,  1.07it/s]INFO:__main__:Requesting https://github.com/patriknw/akka-typed-blog/blob/master/src/main/java/blog/typed/javadsl/Greeter1.java
INFO:__main__:Getting metadata for https://github.com/patriknw/akka-typed-blog/blob/master/src/main/java/blog/typed/javadsl/Greeter1.java
 54%|█████▍    | 98/180 [01:57<01:11,  1.14it/s]INFO:__main__:Requesting https://thedailywtf.com/articles/A_Case_of_the_MUMPS
INFO:__main__:Getting metadata for https://thedailywtf.com/articles/A_Case_of_the_MUMPS
 55%|█████▌    | 99/180 [01:59<01:38,  1.21s/it]INFO:__main__:Requesting https://probablydance.com/2019/03/09/a-programmers-take-on-six-memos-for-the-next-millenium/
ERROR:__main__:Could not reach https://probablydance.com/2019/03/09/a-programmers-take-on-six-memos-for-the-next-millenium/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 56%|█████▌    | 100/180 [01:59<01:11,  1.12it/s]INFO:__main__:Requesting https://www.theparisreview.org/blog/2019/03/05/dice-roll-the-phantom-gambler/
INFO:__main__:Getting metadata for https://www.theparisreview.org/blog/2019/03/05/dice-roll-the-phantom-gambler/
 56%|█████▌    | 101/180 [01:59<00:54,  1.45it/s]INFO:__main__:Requesting https://gaming.nv.gov/index.aspx?page=72
INFO:__main__:Getting metadata for https://gaming.nv.gov/index.aspx?page=72
 57%|█████▋    | 102/180 [02:02<01:46,  1.37s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/William_Lee_Bergstrom
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/William_Lee_Bergstrom
 57%|█████▋    | 103/180 [02:03<01:31,  1.19s/it]INFO:__main__:Requesting https://techcrunch.com/2019/03/08/tufts-grade-hacking/
ERROR:__main__:Could not reach https://techcrunch.com/2019/03/08/tufts-grade-hacking/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 58%|█████▊    | 104/180 [02:03<01:05,  1.15it/s]INFO:__main__:Requesting https://outline.com/ZTzSYa
INFO:__main__:Getting metadata for https://outline.com/ZTzSYa
 58%|█████▊    | 105/180 [02:04<01:09,  1.08it/s]INFO:__main__:Requesting https://youtu.be/0xVF7yCKWno?t=60
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=0xVF7yCKWno&feature=youtu.be&t=60
 59%|█████▉    | 106/180 [02:05<01:09,  1.06it/s]INFO:__main__:Requesting https://www.washingtonpost.com/nation/2018/11/16/his-ex-accused-him-an-attack-that-could-have-meant-life-prison-selfie-saved-him/
ERROR:__main__:Could not reach https://www.washingtonpost.com/nation/2018/11/16/his-ex-accused-him-an-attack-that-could-have-meant-life-prison-selfie-saved-him/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)
 59%|█████▉    | 107/180 [02:11<03:01,  2.49s/it]INFO:__main__:Requesting https://medium.com/@niant/why-deadlines-and-sprints-are-bad-for-you-7ee87be5d0f0
INFO:__main__:Getting metadata for https://medium.com/@niant/why-deadlines-and-sprints-are-bad-for-you-7ee87be5d0f0
 60%|██████    | 108/180 [02:11<02:14,  1.87s/it]INFO:__main__:Requesting https://apenwarr.ca/log/?m=201712
INFO:__main__:Getting metadata for https://apenwarr.ca/log/?m=201712
 61%|██████    | 109/180 [02:14<02:25,  2.05s/it]INFO:__main__:Requesting https://www.scrum.org/resources/commitment-vs-forecast
INFO:__main__:Getting metadata for https://www.scrum.org/resources/commitment-vs-forecast
 61%|██████    | 110/180 [02:14<01:49,  1.57s/it]INFO:__main__:Requesting https://www.linkedin.com/pulse/scrum-evening-james-coplien-vassilis-hardalias
INFO:__main__:Getting metadata for https://www.linkedin.com/pulse/scrum-evening-james-coplien-vassilis-hardalias
 62%|██████▏   | 111/180 [02:15<01:33,  1.35s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Indentation_style#Allman_style
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Indentation_style#Allman_style
 62%|██████▏   | 112/180 [02:17<01:37,  1.43s/it]INFO:__main__:Requesting https://github.com/OSSIA/score/blob/master/.clang-format
INFO:__main__:Getting metadata for https://github.com/OSSIA/score/blob/master/.clang-format
 63%|██████▎   | 113/180 [02:17<01:21,  1.21s/it]INFO:__main__:Requesting https://clang.llvm.org/extra/clang-tidy/checks/list.html
INFO:__main__:Getting metadata for https://clang.llvm.org/extra/clang-tidy/checks/list.html
 63%|██████▎   | 114/180 [02:19<01:18,  1.19s/it]INFO:__main__:Requesting https://clang.llvm.org/extra/clang-tidy/checks/bugprone-string-constructor.html
INFO:__main__:Getting metadata for https://clang.llvm.org/extra/clang-tidy/checks/bugprone-string-constructor.html
 64%|██████▍   | 115/180 [02:20<01:12,  1.12s/it]INFO:__main__:Requesting https://www.pdx.edu/clas/news/bullying-bosses-negatively-impact-employee-performance-and-behavior-study-finds
INFO:__main__:Getting metadata for https://www.pdx.edu/clas/news/bullying-bosses-negatively-impact-employee-performance-and-behavior-study-finds
 64%|██████▍   | 116/180 [02:21<01:25,  1.33s/it]INFO:__main__:Requesting https://www.reuters.com/article/us-netherlands-pharmaceuticals-insight-idUSKCN1QP0M4
INFO:__main__:Getting metadata for https://www.reuters.com/article/us-netherlands-pharmaceuticals-insight-idUSKCN1QP0M4
 65%|██████▌   | 117/180 [02:22<01:05,  1.04s/it]INFO:__main__:Requesting https://www.ontrackdiabetes.com/type-1-diabetes/insulin-prices-still-high
INFO:__main__:Getting metadata for https://www.ontrackdiabetes.com/type-1-diabetes/insulin-prices-still-high
 66%|██████▌   | 118/180 [02:22<00:52,  1.18it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Enantiopure_drug
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Enantiopure_drug
 66%|██████▌   | 119/180 [02:23<00:49,  1.24it/s]INFO:__main__:Requesting http://rooseveltinstitute.org/wp-content/uploads/2019/02/RI_..
 67%|██████▋   | 120/180 [02:25<01:17,  1.30s/it]INFO:__main__:Requesting https://www.kff.org/news-summary/india-brazil-launch-trade-dispute-against-eu-netherlands-over-seizures-of-generic-drugs/
ERROR:__main__:Could not reach https://www.kff.org/news-summary/india-brazil-launch-trade-dispute-against-eu-netherlands-over-seizures-of-generic-drugs/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 67%|██████▋   | 121/180 [02:25<00:56,  1.04it/s]INFO:__main__:Requesting https://www.oncode.nl/research/programs
ERROR:__main__:Could not reach https://www.oncode.nl/research/programs
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.oncode.nl', port=443): Max retries exceeded with url: /research/programs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.oncode.nl', port=443): Max retries exceeded with url: /research/programs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
 68%|██████▊   | 122/180 [02:26<00:47,  1.23it/s]INFO:__main__:Requesting https://www.healthcareers.nhs.uk/explore-roles/pharmacy/studying-pharmacy
INFO:__main__:Getting metadata for https://www.healthcareers.nhs.uk/explore-roles/pharmacy/studying-pharmacy
 68%|██████▊   | 123/180 [02:29<01:28,  1.56s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/ISDS
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/ISDS
 69%|██████▉   | 124/180 [02:31<01:23,  1.50s/it]INFO:__main__:Requesting https://nos.nl/artikel/2266712-hoe-nederlands-kankeronderzoek-novartis-aan-miljarden-gaat-helpen.html
INFO:__main__:Getting metadata for https://nos.nl/artikel/2266712-hoe-nederlands-kankeronderzoek-novartis-aan-miljarden-gaat-helpen.html
 69%|██████▉   | 125/180 [02:32<01:15,  1.38s/it]INFO:__main__:Requesting http://sourceonhealthcare.org/orphan-drug-act-fostering-innovation-or-abuse/
INFO:__main__:Getting metadata for http://sourceonhealthcare.org/orphan-drug-act-fostering-innovation-or-abuse/
 70%|███████   | 126/180 [02:33<01:10,  1.30s/it]INFO:__main__:Requesting https://philanthropynewsdigest.org/news/cystic-fibrosis-foundation-receives-3.3-billion-royalty-pay-out
INFO:__main__:Getting metadata for https://philanthropynewsdigest.org/news/cystic-fibrosis-foundation-receives-3.3-billion-royalty-pay-out
 71%|███████   | 127/180 [02:34<00:59,  1.13s/it]INFO:__main__:Requesting https://latinamericareports.com/the-demolition-of-escobar-monaco-in-medellins-historical-memory
INFO:__main__:Getting metadata for https://latinamericareports.com/the-demolition-of-escobar-monaco-in-medellins-historical-memory/1294/
 71%|███████   | 128/180 [02:36<01:12,  1.40s/it]INFO:__main__:Requesting https://blog.granthika.co/panini/
INFO:__main__:Getting metadata for https://blog.granthika.co/panini/
 72%|███████▏  | 129/180 [02:36<01:03,  1.24s/it]INFO:__main__:Requesting https://www.jefftk.com/p/nomic-game-3
INFO:__main__:Getting metadata for https://www.jefftk.com/p/nomic-game-3
 72%|███████▏  | 130/180 [02:39<01:17,  1.55s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Nomic
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Nomic
 73%|███████▎  | 131/180 [02:40<01:06,  1.36s/it]INFO:__main__:Requesting https://agoranomic.org
INFO:__main__:Getting metadata for https://agoranomic.org
 73%|███████▎  | 132/180 [02:40<00:57,  1.20s/it]INFO:__main__:Requesting https://www.bbc.com/news/science-environment-47478537
INFO:__main__:Getting metadata for https://www.bbc.com/news/science-environment-47478537
 74%|███████▍  | 133/180 [02:41<00:44,  1.06it/s]INFO:__main__:Requesting https://ichef.bbci.co.uk/news/624/cpsprodpb/01A6/production/_105922400_47478537.jpg
INFO:__main__:Getting metadata for https://ichef.bbci.co.uk/news/624/cpsprodpb/01A6/production/_105922400_47478537.jpg
 74%|███████▍  | 134/180 [02:43<00:54,  1.18s/it]INFO:__main__:Requesting https://www.coe.int/en/web/conventions/full-list/-/conventions/rms/090000168008482e
INFO:__main__:Getting metadata for https://www.coe.int/en/web/conventions/full-list/-/conventions/rms/090000168008482e
 75%|███████▌  | 135/180 [02:45<01:05,  1.45s/it]INFO:__main__:Requesting https://xkcd.com/435/
INFO:__main__:Getting metadata for https://xkcd.com/435/
 76%|███████▌  | 136/180 [02:45<00:51,  1.16s/it]INFO:__main__:Requesting https://www.theguardian.com/science/2005/jan/18/educationsgendergap.genderissues
INFO:__main__:Getting metadata for https://www.theguardian.com/science/2005/jan/18/educationsgendergap.genderissues
 76%|███████▌  | 137/180 [02:46<00:40,  1.05it/s]INFO:__main__:Requesting http://www.smallpianokeyboards.org/uploads/3/4/1/6/34165129/right-hand-span-results-with-dots-dec-2016_1_orig.jpg
INFO:__main__:Getting metadata for http://www.smallpianokeyboards.org/uploads/3/4/1/6/34165129/right-hand-span-results-with-dots-dec-2016_1_orig.jpg
 77%|███████▋  | 138/180 [02:51<01:35,  2.27s/it]INFO:__main__:Requesting http://www.smallpianokeyboards.org/hand-span-data.html
INFO:__main__:Getting metadata for http://www.smallpianokeyboards.org/hand-span-data.html
 77%|███████▋  | 139/180 [02:51<01:09,  1.70s/it]INFO:__main__:Requesting https://press.cern/press-releases/2018/09/updated-statement-cern-stands-diversity*
 78%|███████▊  | 140/180 [02:53<01:09,  1.74s/it]INFO:__main__:Requesting https://news.ycombinator.com/newsguidelines.html
INFO:__main__:Getting metadata for https://news.ycombinator.com/newsguidelines.html
 78%|███████▊  | 141/180 [02:54<01:00,  1.55s/it]INFO:__main__:Requesting https://news.ycombinator.com/newswelcome.html
INFO:__main__:Getting metadata for https://news.ycombinator.com/newswelcome.html
 79%|███████▉  | 142/180 [02:55<00:53,  1.41s/it]INFO:__main__:Requesting https://news.ycombinator.com/hackernews.html
INFO:__main__:Getting metadata for https://news.ycombinator.com/hackernews.html
 79%|███████▉  | 143/180 [02:56<00:48,  1.32s/it]INFO:__main__:Requesting http://www.paulgraham.com/hackernews.html
INFO:__main__:Getting metadata for http://www.paulgraham.com/hackernews.html
 80%|████████  | 144/180 [02:57<00:39,  1.10s/it]INFO:__main__:Requesting http://www.paulgraham.com/trolls.html
INFO:__main__:Getting metadata for http://www.paulgraham.com/trolls.html
 81%|████████  | 145/180 [02:57<00:31,  1.11it/s]INFO:__main__:Requesting https://drive.google.com/file/d/1c_NyUhOZ8erdqU2AGZJZtNfFeA91Kefj/view
INFO:__main__:Getting metadata for https://drive.google.com/file/d/1c_NyUhOZ8erdqU2AGZJZtNfFeA91Kefj/view
 81%|████████  | 146/180 [03:00<00:42,  1.26s/it]INFO:__main__:Requesting https://onlinelibrary.wiley.com/doi/epdf/10.1111/evo.12224
INFO:__main__:Getting metadata for https://onlinelibrary.wiley.com/doi/epdf/10.1111/evo.12224
 82%|████████▏ | 147/180 [03:02<00:57,  1.74s/it]INFO:__main__:Requesting https://i.imgur.com/4E6FUXN.png
INFO:__main__:Getting metadata for https://i.imgur.com/4E6FUXN.png
 82%|████████▏ | 148/180 [03:06<01:12,  2.25s/it]INFO:__main__:Requesting https://www.splcenter.org/fighting-hate/intelligence-report/2002/ally-christian-right-heavyweight-paul-weyrich-addresses-holocaust-denial-conference
INFO:__main__:Getting metadata for https://www.splcenter.org/fighting-hate/intelligence-report/2002/ally-christian-right-heavyweight-paul-weyrich-addresses-holocaust-denial-conference
 83%|████████▎ | 149/180 [03:06<00:50,  1.64s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/The_Emperor%27s_New_Clothes
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/The_Emperor%27s_New_Clothes
 83%|████████▎ | 150/180 [03:07<00:44,  1.50s/it]INFO:__main__:Requesting https://www.scottaaronson.com/blog/?p=304
 84%|████████▍ | 151/180 [03:08<00:33,  1.15s/it]INFO:__main__:Requesting http://resonaances.blogspot.com/2016/06/game-of-thrones-750-gev-edition.html
INFO:__main__:Getting metadata for http://resonaances.blogspot.com/2016/06/game-of-thrones-750-gev-edition.html
 84%|████████▍ | 152/180 [03:08<00:27,  1.03it/s]INFO:__main__:Requesting https://www.particlesforjustice.org
INFO:__main__:Getting metadata for https://www.particlesforjustice.org
 85%|████████▌ | 153/180 [03:09<00:23,  1.14it/s]INFO:__main__:Requesting https://justiceforstrumia.org
INFO:__main__:Getting metadata for https://justiceforstrumia.org
 86%|████████▌ | 154/180 [03:10<00:22,  1.18it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Emmy_Noether
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Emmy_Noether
 86%|████████▌ | 155/180 [03:11<00:28,  1.15s/it]INFO:__main__:Requesting https://www.theguardian.com/education/2017/aug/28/university-gender-gap-at-record-high-as-30000-more-women-accepted
INFO:__main__:Getting metadata for https://www.theguardian.com/education/2017/aug/28/university-gender-gap-at-record-high-as-30000-more-women-accepted
 87%|████████▋ | 156/180 [03:12<00:22,  1.07it/s]INFO:__main__:Requesting https://www.hesa.ac.uk/news/11-01-2018/sfr247-higher-education-student-statistics/subjects
INFO:__main__:Getting metadata for https://www.hesa.ac.uk/news/11-01-2018/sfr247-higher-education-student-statistics/subjects
 87%|████████▋ | 157/180 [03:13<00:24,  1.04s/it]INFO:__main__:Requesting http://backreaction.blogspot.com/2018/10/gender-bias-in-academia-case-strumia.html?m=1
INFO:__main__:Getting metadata for http://backreaction.blogspot.com/2018/10/gender-bias-in-academia-case-strumia.html?m=1
 88%|████████▊ | 158/180 [03:14<00:20,  1.09it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=sOCIke7zLMo
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=sOCIke7zLMo
 88%|████████▊ | 159/180 [03:15<00:19,  1.10it/s]INFO:__main__:Requesting http://gltr.io/
INFO:__main__:Getting metadata for http://gltr.io
 89%|████████▉ | 160/180 [03:15<00:13,  1.45it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Mojibake
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Mojibake
 89%|████████▉ | 161/180 [03:17<00:19,  1.03s/it]INFO:__main__:Requesting https://www.theatlantic.com/technology/archive/2019/03/china-has-stopped-accepting-our-trash/584131/
INFO:__main__:Getting metadata for https://www.theatlantic.com/technology/archive/2019/03/china-has-stopped-accepting-our-trash/584131/
 90%|█████████ | 162/180 [03:17<00:14,  1.27it/s]INFO:__main__:Requesting https://www.bath.ac.uk/case-studies/debunking-big-tobaccos-arguments-against-standardised-packaging/
INFO:__main__:Getting metadata for https://www.bath.ac.uk/case-studies/debunking-big-tobaccos-arguments-against-standardised-packaging/
 91%|█████████ | 163/180 [03:19<00:19,  1.18s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Dry_ice#Manufacture
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Dry_ice#Manufacture
 91%|█████████ | 164/180 [03:20<00:19,  1.22s/it]INFO:__main__:Requesting https://www.youtube.com/watch?time_continue=254&v=4FpsH_ETT7c
INFO:__main__:Getting metadata for https://www.youtube.com/watch?time_continue=254&v=4FpsH_ETT7c
 92%|█████████▏| 165/180 [03:21<00:17,  1.18s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=f0OZ7Mlmkvk
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=f0OZ7Mlmkvk
 92%|█████████▏| 166/180 [03:22<00:15,  1.08s/it]INFO:__main__:Requesting https://www.kcet.org/shows/socal-connected/carbonlite-inside-the-worlds-largest-plastic-bottle-recycling-plant-0
INFO:__main__:Getting metadata for https://www.kcet.org/shows/socal-connected/carbonlite-inside-the-worlds-largest-plastic-bottle-recycling-plant-0
 93%|█████████▎| 167/180 [03:23<00:12,  1.02it/s]INFO:__main__:Requesting https://www.wastedive.com/news/china-contamination-standard-MRFs/519659/
INFO:__main__:Getting metadata for https://www.wastedive.com/news/china-contamination-standard-MRFs/519659/
 93%|█████████▎| 168/180 [03:24<00:11,  1.05it/s]INFO:__main__:Requesting https://www.thisiseco.co.uk/news_and_blog/what-happens-to-waste-to-energy-incineration-ash.html
INFO:__main__:Getting metadata for https://www.thisiseco.co.uk/news_and_blog/what-happens-to-waste-to-energy-incineration-ash.html
 94%|█████████▍| 169/180 [03:26<00:13,  1.22s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Green_Dot_(symbol)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Green_Dot_(symbol)
 94%|█████████▍| 170/180 [03:26<00:10,  1.08s/it]INFO:__main__:Requesting https://slate.com/business/2013/01/yacht-economics-rich-people-don-t-consume-very-much.html
INFO:__main__:Getting metadata for https://slate.com/business/2013/01/yacht-economics-rich-people-don-t-consume-very-much.html
 95%|█████████▌| 171/180 [03:27<00:08,  1.12it/s]INFO:__main__:Requesting https://www.dailymotion.com/video/x6klo0p
INFO:__main__:Getting metadata for https://www.dailymotion.com/video/x6klo0p
 96%|█████████▌| 172/180 [03:28<00:07,  1.00it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Mobro_4000
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Mobro_4000
 96%|█████████▌| 173/180 [03:29<00:06,  1.16it/s]INFO:__main__:Requesting https://www.plasticchina.org/
INFO:__main__:Getting metadata for https://www.plasticchina.org
 97%|█████████▋| 174/180 [03:34<00:13,  2.25s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Plasma_gasification
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Plasma_gasification
 97%|█████████▋| 175/180 [03:35<00:09,  1.86s/it]INFO:__main__:Requesting https://purecycletech.com/
INFO:__main__:Getting metadata for https://purecycletech.com
 98%|█████████▊| 176/180 [03:36<00:06,  1.54s/it]INFO:__main__:Requesting https://earlymodernmedicine.com/the-man-with-an-elephants-nose/
 98%|█████████▊| 177/180 [03:36<00:03,  1.17s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Alejandro_Jodorowsky#Psychomagic
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Alejandro_Jodorowsky#Psychomagic
 99%|█████████▉| 178/180 [03:38<00:02,  1.38s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Cotard_delusion
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Cotard_delusion
 99%|█████████▉| 179/180 [03:39<00:01,  1.26s/it]INFO:__main__:Requesting https://youtu.be/WaVzajICS-w
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=WaVzajICS-w&feature=youtu.be
100%|██████████| 180/180 [03:40<00:00,  1.14s/it]
