INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  3%|▎         | 1/30 [00:00<00:03,  7.77it/s]  7%|▋         | 2/30 [00:00<00:04,  5.62it/s] 10%|█         | 3/30 [00:01<00:11,  2.30it/s] 13%|█▎        | 4/30 [00:01<00:11,  2.30it/s] 20%|██        | 6/30 [00:02<00:09,  2.48it/s] 33%|███▎      | 10/30 [00:03<00:07,  2.62it/s] 43%|████▎     | 13/30 [00:04<00:05,  3.09it/s] 50%|█████     | 15/30 [00:04<00:04,  3.69it/s] 53%|█████▎    | 16/30 [00:04<00:03,  4.25it/s] 57%|█████▋    | 17/30 [00:05<00:03,  3.80it/s] 60%|██████    | 18/30 [00:05<00:05,  2.40it/s] 67%|██████▋   | 20/30 [00:06<00:03,  3.06it/s] 73%|███████▎  | 22/30 [00:08<00:04,  1.96it/s] 83%|████████▎ | 25/30 [00:08<00:01,  2.67it/s] 87%|████████▋ | 26/30 [00:08<00:01,  2.14it/s] 97%|█████████▋| 29/30 [00:09<00:00,  2.91it/s]100%|██████████| 30/30 [00:09<00:00,  3.46it/s]
  0%|          | 0/186 [00:00<?, ?it/s]INFO:__main__:Requesting https://jakevdp.github.io/blog/2012/10/07/xkcd-style-plots-in-matplotlib/
INFO:__main__:Getting metadata for https://jakevdp.github.io/blog/2012/10/07/xkcd-style-plots-in-matplotlib/
  1%|          | 1/186 [00:01<03:50,  1.25s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=inN8seMm7UI&t=4s
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=inN8seMm7UI&t=4s
  1%|          | 2/186 [00:02<03:29,  1.14s/it]INFO:__main__:Requesting https://stackoverflow.com/questions/12675147/how-can-we-make-xkcd-style-graphs
INFO:__main__:Getting metadata for https://stackoverflow.com/questions/12675147/how-can-we-make-xkcd-style-graphs
  2%|▏         | 3/186 [00:02<02:45,  1.11it/s]INFO:__main__:Requesting https://roughjs.com/
INFO:__main__:Getting metadata for https://roughjs.com
  2%|▏         | 4/186 [00:02<02:15,  1.35it/s]INFO:__main__:Requesting https://nanxiao.me/en/what-you-need-may-be-pipeline-unix-commands-only/
  3%|▎         | 5/186 [00:03<02:07,  1.42it/s]INFO:__main__:Requesting https://adamdrake.com/command-line-tools-can-be-235x-faster-than-your-hadoop-cluster.html
INFO:__main__:Getting metadata for https://adamdrake.com/command-line-tools-can-be-235x-faster-than-your-hadoop-cluster.html
  3%|▎         | 6/186 [00:03<01:39,  1.82it/s]INFO:__main__:Requesting http://widgetsandshit.com/teddziuba/2010/10/taco-bell-programming.html
INFO:__main__:Getting metadata for http://widgetsandshit.com/teddziuba/2010/10/taco-bell-programming.html
  4%|▍         | 7/186 [00:04<01:29,  2.00it/s]INFO:__main__:Requesting https://github.com/jlevy/the-art-of-command-line
INFO:__main__:Getting metadata for https://github.com/jlevy/the-art-of-command-line
  4%|▍         | 8/186 [00:05<01:55,  1.55it/s]INFO:__main__:Requesting https://www.gnu.org/software/coreutils/manual/html_node/index.html
INFO:__main__:Getting metadata for https://www.gnu.org/software/coreutils/manual/html_node/index.html
  5%|▍         | 9/186 [00:07<03:05,  1.05s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/AWK#History
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/AWK#History
  5%|▌         | 10/186 [00:08<03:24,  1.16s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/GNU#History
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/GNU#History
  6%|▌         | 11/186 [00:10<03:46,  1.30s/it]INFO:__main__:Requesting https://digit.fyi/teen-hacker-earns-1m-via-bug-bounties/
INFO:__main__:Getting metadata for https://digit.fyi/teen-hacker-earns-1m-via-bug-bounties/
  6%|▋         | 12/186 [00:11<04:04,  1.41s/it]INFO:__main__:Requesting http://writecodeeveryday.github.io/projects/badqr/
INFO:__main__:Getting metadata for http://writecodeeveryday.github.io/projects/badqr/
  7%|▋         | 13/186 [00:11<03:00,  1.04s/it]INFO:__main__:Requesting https://www.amazon.jobs/en/jobs/750254/security-engineer-ii-bug-bounties
INFO:__main__:Getting metadata for https://www.amazon.jobs/en/jobs/750254/security-engineer-ii-bug-bounties
  8%|▊         | 14/186 [00:12<02:34,  1.11it/s]INFO:__main__:Requesting https://aws.amazon.com/security/vulnerability-reporting/
INFO:__main__:Getting metadata for https://aws.amazon.com/security/vulnerability-reporting/
  8%|▊         | 15/186 [00:12<02:05,  1.36it/s]INFO:__main__:Requesting https://overthewire.org/wargames/bandit/
INFO:__main__:Getting metadata for https://overthewire.org/wargames/bandit/
  9%|▊         | 16/186 [00:13<01:50,  1.54it/s]INFO:__main__:Requesting http://overthewire.org/wargames/natas/
INFO:__main__:Getting metadata for http://overthewire.org/wargames/natas/
  9%|▉         | 17/186 [00:13<01:27,  1.92it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Predictably_Irrational
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Predictably_Irrational
 10%|▉         | 18/186 [00:14<01:46,  1.58it/s]INFO:__main__:Requesting https://security.stackexchange.com
INFO:__main__:Getting metadata for https://security.stackexchange.com
 10%|█         | 19/186 [00:14<01:28,  1.89it/s]INFO:__main__:Requesting https://blog.trailofbits.com/2019/01/14/on-bounties-and-boffins/
ERROR:__main__:Could not reach https://blog.trailofbits.com/2019/01/14/on-bounties-and-boffins/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 11%|█         | 20/186 [00:14<01:09,  2.39it/s]INFO:__main__:Requesting https://mitpress.mit.edu/books/new-solutions-cybersecurity
INFO:__main__:Getting metadata for https://mitpress.mit.edu/books/new-solutions-cybersecurity
 11%|█▏        | 21/186 [00:15<01:13,  2.24it/s]INFO:__main__:Requesting https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.md
INFO:__main__:Getting metadata for https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.md
 12%|█▏        | 22/186 [00:16<01:26,  1.90it/s]INFO:__main__:Requesting https://dilbert.com/strip/1995-11-13
INFO:__main__:Getting metadata for https://dilbert.com/strip/1995-11-13
 12%|█▏        | 23/186 [00:17<01:50,  1.47it/s]INFO:__main__:Requesting https://slate.com/technology/2013/02/hacker-photos-how-hacker-dojo-pranked-wired-with-hilariously-stereotypical-stock-images.html
INFO:__main__:Getting metadata for https://slate.com/technology/2013/02/hacker-photos-how-hacker-dojo-pranked-wired-with-hilariously-stereotypical-stock-images.html
 13%|█▎        | 24/186 [00:17<01:49,  1.49it/s]INFO:__main__:Requesting https://techiavellian.com/intellectual-denial-of-service-attacks
INFO:__main__:Getting metadata for https://techiavellian.com/intellectual-denial-of-service-attacks
 13%|█▎        | 25/186 [00:18<01:43,  1.55it/s]INFO:__main__:Requesting https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.0020124
INFO:__main__:Getting metadata for https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.0020124
 14%|█▍        | 26/186 [00:19<02:02,  1.31it/s]INFO:__main__:Requesting https://www.smithsonianmag.com/science-nature/scientists-replicated-100-psychology-studies-and-fewer-half-got-same-results-180956426/
INFO:__main__:Getting metadata for https://www.smithsonianmag.com/science-nature/scientists-replicated-100-psychology-studies-and-fewer-half-got-same-results-180956426/
 15%|█▍        | 27/186 [00:20<01:56,  1.36it/s]INFO:__main__:Requesting https://www.nature.com/news/1-500-scientists-lift-the-lid-on-reproducibility-1.19970
INFO:__main__:Getting metadata for https://www.nature.com/news/1-500-scientists-lift-the-lid-on-reproducibility-1.19970
 15%|█▌        | 28/186 [00:21<02:53,  1.10s/it]INFO:__main__:Requesting https://www.nytimes.com/2016/05/08/opinion/sunday/a-confession-of-liberal-intolerance.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2016/05/08/opinion/sunday/a-confession-of-liberal-intolerance.html
 16%|█▌        | 29/186 [00:22<02:39,  1.02s/it]INFO:__main__:Requesting https://www.newyorker.com/science/maria-konnikova/social-psychology-biased-republicans
INFO:__main__:Getting metadata for https://www.newyorker.com/science/maria-konnikova/social-psychology-biased-republicans
 16%|█▌        | 30/186 [00:23<02:35,  1.00it/s]INFO:__main__:Requesting https://slatestarcodex.com/2015/06/06/against-tulip-subsidies/
INFO:__main__:Getting metadata for https://slatestarcodex.com/2015/06/06/against-tulip-subsidies/
 17%|█▋        | 31/186 [00:27<04:55,  1.91s/it]INFO:__main__:Requesting http://deadstate.org/vaccinations-increase-500-in-anti-vaxxer-stronghold-after-measles-outbreak/
INFO:__main__:Getting metadata for http://deadstate.org/vaccinations-increase-500-in-anti-vaxxer-stronghold-after-measles-outbreak/
 17%|█▋        | 32/186 [00:28<03:37,  1.41s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Gish_gallop
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Gish_gallop
 18%|█▊        | 33/186 [00:28<03:07,  1.22s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=0FPsEwWT6K0
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=0FPsEwWT6K0
 18%|█▊        | 34/186 [00:29<02:51,  1.13s/it]INFO:__main__:Requesting https://www.americamagazine.org/arts-culture/2017/09/26/corrosion-high-school-debate-and-how-it-mirrors-american-politics
INFO:__main__:Getting metadata for https://www.americamagazine.org/arts-culture/2017/09/26/corrosion-high-school-debate-and-how-it-mirrors-american-politics
 19%|█▉        | 35/186 [00:30<02:13,  1.13it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/The_Ego_and_Its_Own
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/The_Ego_and_Its_Own
 19%|█▉        | 36/186 [00:31<02:20,  1.07it/s]INFO:__main__:Requesting http://www.paulgraham.com/identity.html
INFO:__main__:Getting metadata for http://www.paulgraham.com/identity.html
 20%|█▉        | 37/186 [00:31<02:01,  1.23it/s]INFO:__main__:Requesting https://cryptome.org/2012/07/gent-forum-spies.htm
INFO:__main__:Getting metadata for https://cryptome.org/2012/07/gent-forum-spies.htm
 20%|██        | 38/186 [00:33<02:32,  1.03s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Bullshit#Bullshit_asymmetry_principle
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Bullshit#Bullshit_asymmetry_principle
 21%|██        | 39/186 [00:33<02:14,  1.09it/s]INFO:__main__:Requesting https://old.reddit.com/r/dredmorbius/comments/28ge14/on_nonsense_forms_thereof_falsifiability/
INFO:__main__:Getting metadata for https://old.reddit.com/r/dredmorbius/comments/28ge14/on_nonsense_forms_thereof_falsifiability/
 22%|██▏       | 40/186 [00:34<01:53,  1.28it/s]INFO:__main__:Requesting https://www.pikapkg.com/about
INFO:__main__:Getting metadata for https://www.pikapkg.com/about
 22%|██▏       | 41/186 [00:35<01:55,  1.25it/s]INFO:__main__:Requesting http://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/
INFO:__main__:Getting metadata for http://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/
 23%|██▎       | 42/186 [00:36<02:11,  1.10it/s]INFO:__main__:Requesting https://github.com/libguestfs/libguestfs
INFO:__main__:Getting metadata for https://github.com/libguestfs/libguestfs
 23%|██▎       | 43/186 [00:37<02:15,  1.05it/s]INFO:__main__:Requesting https://reasonml.github.io/reason-react/
INFO:__main__:Getting metadata for https://reasonml.github.io/reason-react/
 24%|██▎       | 44/186 [00:37<01:41,  1.40it/s]INFO:__main__:Requesting http://dev.realworldocaml.org/toc.html
INFO:__main__:Getting metadata for http://dev.realworldocaml.org/toc.html
 24%|██▍       | 45/186 [00:38<01:40,  1.41it/s]INFO:__main__:Requesting http://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/intro/ocaml.html
INFO:__main__:Getting metadata for http://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/intro/ocaml.html
 25%|██▍       | 46/186 [00:39<02:03,  1.13it/s]INFO:__main__:Requesting https://amturing.acm.org/award_winners/milner_1569367.cfm
INFO:__main__:Getting metadata for https://amturing.acm.org/award_winners/milner_1569367.cfm
 25%|██▌       | 47/186 [00:41<03:09,  1.37s/it]INFO:__main__:Requesting https://twitter.com/etiennemillon/status/1095250528467079169
INFO:__main__:Getting metadata for https://twitter.com/etiennemillon/status/1095250528467079169
 26%|██▌       | 48/186 [00:42<02:41,  1.17s/it]INFO:__main__:Requesting https://reasonml.github.io/en/try?rrjsx=true&reason=DYUwLgBAlgdgDgV0gXggbwD4CgIQDwAWYAtsAHw674EgCGAJhVVXmFGKGQIIQDKUxOKAgAJACoBZADIQAIgHsAxgmIgYYPAHo2HEExaaaDfbjwAjefQCeJlnDJiCUAM7RXtCADcQAJysRnASEQUUkZeiUVNQ1Ne0pmPHsASUh5GGB-AlpXMAB3eQg4Wh9aAHMSuAJnLTiEzQtrfS0iUgoMAF8AbiwsUEgfEGcEYBQIAClnADpeMB9YUsniWjBFAgAKAG0AUgH0DE1EsjXJgCoAfgBKPAAdWLJNUqgOgF0AGmh4JAvurGdc9lWEDWAyGIwu6CwGD48lUwMGwzA4OQZHGUy4PhKVkmADN5D4AKK0VZrCaTYDyUrvEEIi6QiAAOTSIWRqLJFLWACIYAUlisaM4ObSukA
INFO:__main__:Getting metadata for https://reasonml.github.io/en/try?rrjsx=true&reason=DYUwLgBAlgdgDgV0gXggbwD4CgIQDwAWYAtsAHw674EgCGAJhVVXmFGKGQIIQDKUxOKAgAJACoBZADIQAIgHsAxgmIgYYPAHo2HEExaaaDfbjwAjefQCeJlnDJiCUAM7RXtCADcQAJysRnASEQUUkZeiUVNQ1Ne0pmPHsASUh5GGB-AlpXMAB3eQg4Wh9aAHMSuAJnLTiEzQtrfS0iUgoMAF8AbiwsUEgfEGcEYBQIAClnADpeMB9YUsniWjBFAgAKAG0AUgH0DE1EsjXJgCoAfgBKPAAdWLJNUqgOgF0AGmh4JAvurGdc9lWEDWAyGIwu6CwGD48lUwMGwzA4OQZHGUy4PhKVkmADN5D4AKK0VZrCaTYDyUrvEEIi6QiAAOTSIWRqLJFLWACIYAUlisaM4ObSukA
 26%|██▋       | 49/186 [00:42<01:58,  1.16it/s]INFO:__main__:Requesting https://github.com/revery-ui/revery
INFO:__main__:Getting metadata for https://github.com/revery-ui/revery
 27%|██▋       | 50/186 [00:43<02:03,  1.11it/s]INFO:__main__:Requesting https://github.com/Schniz/fnm
INFO:__main__:Getting metadata for https://github.com/Schniz/fnm
 27%|██▋       | 51/186 [00:44<02:04,  1.08it/s]INFO:__main__:Requesting https://github.com/ostera/reactor
INFO:__main__:Getting metadata for https://github.com/ostera/reactor
 28%|██▊       | 52/186 [00:45<01:56,  1.15it/s]INFO:__main__:Requesting http://keleshev.com/composable-error-handling-in-ocaml
INFO:__main__:Getting metadata for http://keleshev.com/composable-error-handling-in-ocaml
 28%|██▊       | 53/186 [00:45<01:33,  1.43it/s]INFO:__main__:Requesting https://victor.darvariu.me/jekyll/update/2018/06/19/ppx-tutorial.html
INFO:__main__:Getting metadata for https://victor.darvariu.me/jekyll/update/2018/06/19/ppx-tutorial.html
 29%|██▉       | 54/186 [00:48<02:35,  1.18s/it]INFO:__main__:Requesting http://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/intro/ocaml.html#beauty
INFO:__main__:Getting metadata for http://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/intro/ocaml.html#beauty
 30%|██▉       | 55/186 [00:49<02:39,  1.22s/it]INFO:__main__:Requesting http://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/basics/interacting.html
INFO:__main__:Getting metadata for http://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/basics/interacting.html
 30%|███       | 56/186 [00:50<02:42,  1.25s/it]INFO:__main__:Requesting https://v1.realworldocaml.org/v1/en/html/the-compiler-backend-byte-code-and-native-code.html#the-untyped-lambda-form
INFO:__main__:Getting metadata for https://v1.realworldocaml.org/v1/en/html/the-compiler-backend-byte-code-and-native-code.html#the-untyped-lambda-form
 31%|███       | 57/186 [00:52<02:56,  1.37s/it]INFO:__main__:Requesting https://ocaml.org/learn/tutorials/99problems.html
INFO:__main__:Getting metadata for https://ocaml.org/learn/tutorials/99problems.html
 31%|███       | 58/186 [00:54<03:37,  1.70s/it]INFO:__main__:Requesting https://reasonml.github.io/docs/en/overview
INFO:__main__:Getting metadata for https://reasonml.github.io/docs/en/overview
 32%|███▏      | 59/186 [00:55<02:37,  1.24s/it]INFO:__main__:Requesting https://esy.sh/
INFO:__main__:Getting metadata for https://esy.sh
 32%|███▏      | 60/186 [00:55<02:02,  1.02it/s]INFO:__main__:Requesting https://github.com/jaredly/redoc
INFO:__main__:Getting metadata for https://github.com/jaredly/redoc
 33%|███▎      | 61/186 [00:56<01:57,  1.06it/s]INFO:__main__:Requesting https://github.com/janestreet/ppx_inline_test
INFO:__main__:Getting metadata for https://github.com/janestreet/ppx_inline_test
 33%|███▎      | 62/186 [00:57<01:50,  1.12it/s]INFO:__main__:Requesting https://dune.build/
INFO:__main__:Getting metadata for https://dune.build
 34%|███▍      | 63/186 [00:57<01:42,  1.20it/s]INFO:__main__:Requesting http://caml.inria.fr/pub/ml-archives/caml-list/2006/11/d921ca59f12d434a3f005dfd07256d91.en.html
INFO:__main__:Getting metadata for http://caml.inria.fr/pub/ml-archives/caml-list/2006/11/d921ca59f12d434a3f005dfd07256d91.en.html
 34%|███▍      | 64/186 [00:59<02:02,  1.01s/it]INFO:__main__:Requesting https://m.dw.com/en/german-police-storing-bodycam-footage-on-amazon-cloud/a-47751028
INFO:__main__:Getting metadata for https://m.dw.com/en/german-police-storing-bodycam-footage-on-amazon-cloud/a-47751028
 35%|███▍      | 65/186 [01:00<02:06,  1.04s/it]INFO:__main__:Requesting https://www.dw.com/en/german-police-storing-bodycam-footage-on-amazon-cloud/a-47751028
INFO:__main__:Getting metadata for https://www.dw.com/en/german-police-storing-bodycam-footage-on-amazon-cloud/a-47751028
 35%|███▌      | 66/186 [01:01<02:12,  1.11s/it]INFO:__main__:Requesting https://www.publicbooks.org/counter-histories-of-the-internet/
INFO:__main__:Getting metadata for https://www.publicbooks.org/counter-histories-of-the-internet/
 36%|███▌      | 67/186 [01:02<01:48,  1.09it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Internet_taxes
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Internet_taxes
 37%|███▋      | 68/186 [01:03<01:53,  1.04it/s]INFO:__main__:Requesting http://emacsninja.com/posts/smooth-video-game-emulation-in-emacs.html
INFO:__main__:Getting metadata for http://emacsninja.com/posts/smooth-video-game-emulation-in-emacs.html
 37%|███▋      | 69/186 [01:04<02:00,  1.03s/it]INFO:__main__:Requesting https://www.bloomberg.com/news/articles/2019-03-02/square-inc-co-founder-tristan-o-tierney-dies-at-35
INFO:__main__:Getting metadata for https://www.bloomberg.com/tosv2.html?vid=&uuid=e9ed2ff0-3da3-11e9-9850-91b30e6adaa6&url=L25ld3MvYXJ0aWNsZXMvMjAxOS0wMy0wMi9zcXVhcmUtaW5jLWNvLWZvdW5kZXItdHJpc3Rhbi1vLXRpZXJuZXktZGllcy1hdC0zNQ==
 38%|███▊      | 70/186 [01:04<01:43,  1.13it/s]INFO:__main__:Requesting http://time.com/3399433/quit-smoking-psychedelic-drugs-acid-test/
INFO:__main__:Getting metadata for http://time.com/3399433/quit-smoking-psychedelic-drugs-acid-test/
 38%|███▊      | 71/186 [01:05<01:27,  1.31it/s]INFO:__main__:Requesting https://cthreefoundation.org/find-a-physician
INFO:__main__:Getting metadata for https://cthreefoundation.org/find-a-physician
 39%|███▊      | 72/186 [01:05<01:23,  1.37it/s]INFO:__main__:Requesting https://www.mdproactive.com/what-we-treat/alcohol-use-disorder
INFO:__main__:Getting metadata for https://www.mdproactive.com/what-we-treat/alcohol-use-disorder
 39%|███▉      | 73/186 [01:07<01:40,  1.13it/s]INFO:__main__:Requesting https://scholar.google.com/scholar?hl=en&as_sdt=0%2C14&q=sinclair+method+alcohol&btnG=&oq=sinclair+method+alc
INFO:__main__:Getting metadata for https://scholar.google.com/scholar?hl=en&as_sdt=0%2C14&q=sinclair+method+alcohol&btnG=&oq=sinclair+method+alc
 40%|███▉      | 74/186 [01:07<01:18,  1.43it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Naltrexone
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Naltrexone
 40%|████      | 75/186 [01:09<01:57,  1.06s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=53JObexh0w0
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=53JObexh0w0
 41%|████      | 76/186 [01:10<02:03,  1.12s/it]INFO:__main__:Requesting https://www.amazon.com/Cure-Alcoholism-Medically-Eliminate-Addiction/dp/1937856135/
INFO:__main__:Getting metadata for https://www.amazon.com/Cure-Alcoholism-Medically-Eliminate-Addiction/dp/1937856135/
 41%|████▏     | 77/186 [01:13<02:59,  1.65s/it]INFO:__main__:Requesting https://www.youtube.com/channel/UCdeh0LP6kuSQ9GsorQpVnUw
INFO:__main__:Getting metadata for https://www.youtube.com/channel/UCdeh0LP6kuSQ9GsorQpVnUw
 42%|████▏     | 78/186 [01:14<02:51,  1.59s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2746426/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2746426/
 42%|████▏     | 79/186 [01:16<02:42,  1.52s/it]INFO:__main__:Requesting https://www.theatlantic.com/magazine/archive/2015/04/the-irrationality-of-alcoholics-anonymous/386255/
INFO:__main__:Getting metadata for https://www.theatlantic.com/magazine/archive/2015/04/the-irrationality-of-alcoholics-anonymous/386255/
 43%|████▎     | 80/186 [01:16<02:03,  1.17s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4285560/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4285560/
 44%|████▎     | 81/186 [01:17<02:03,  1.17s/it]INFO:__main__:Requesting https://academic.oup.com/alcalc/article/36/1/2/137995
INFO:__main__:Getting metadata for https://academic.oup.com/alcalc/article/36/1/2/137995
ERROR:__main__:Could not get metadata for https://academic.oup.com/alcalc/article/36/1/2/137995
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
 44%|████▍     | 82/186 [01:19<02:12,  1.27s/it]INFO:__main__:Requesting https://www.hellosundaymorning.org
INFO:__main__:Getting metadata for https://www.hellosundaymorning.org
 45%|████▍     | 83/186 [01:20<02:07,  1.23s/it]INFO:__main__:Requesting https://www.theguardian.com/news/datablog/2016/jan/22/alcohol-and-the-nhs-five-key-questions
INFO:__main__:Getting metadata for https://www.theguardian.com/news/datablog/2016/jan/22/alcohol-and-the-nhs-five-key-questions
 45%|████▌     | 84/186 [01:20<01:42,  1.00s/it]INFO:__main__:Requesting http://otierney.net/cities
INFO:__main__:Getting metadata for http://otierney.net/cities
 46%|████▌     | 85/186 [01:21<01:19,  1.26it/s]INFO:__main__:Requesting https://500px.com/tristan
INFO:__main__:Getting metadata for https://500px.com/tristan
 46%|████▌     | 86/186 [01:24<02:38,  1.59s/it]INFO:__main__:Requesting https://instagram.com/tristan
ERROR:__main__:Could not reach https://instagram.com/tristan
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/opt/python/3.6.3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
 47%|████▋     | 87/186 [01:25<02:10,  1.31s/it]INFO:__main__:Requesting https://www.flickr.com/photos/tristanotierney/
INFO:__main__:Getting metadata for https://www.flickr.com/photos/tristanotierney/
 47%|████▋     | 88/186 [01:28<02:57,  1.81s/it]INFO:__main__:Requesting http://otierney.net/tutorials/2014/4/24/long-exposure-light-trails
INFO:__main__:Getting metadata for http://otierney.net/tutorials/2014/4/24/long-exposure-light-trails
 48%|████▊     | 89/186 [01:28<02:13,  1.38s/it]INFO:__main__:Requesting https://pages.nist.gov/800-63-3/sp800-63b.html
INFO:__main__:Getting metadata for https://pages.nist.gov/800-63-3/sp800-63b.html
 48%|████▊     | 90/186 [01:29<01:49,  1.14s/it]INFO:__main__:Requesting https://github.com/vreeze/eboy
INFO:__main__:Getting metadata for https://github.com/vreeze/eboy
 49%|████▉     | 91/186 [01:30<01:35,  1.00s/it]INFO:__main__:Requesting https://www.emacswiki.org/emacs/Evil
INFO:__main__:Getting metadata for https://www.emacswiki.org/emacs/Evil
 49%|████▉     | 92/186 [01:34<03:25,  2.19s/it]INFO:__main__:Requesting https://aeva.online/2019/03/what-happened-to-openstack/
INFO:__main__:Getting metadata for https://aeva.online/2019/03/what-happened-to-openstack/
 50%|█████     | 93/186 [01:36<03:15,  2.10s/it]INFO:__main__:Requesting https://awsinsider.net/articles/2018/11/01/azure-fastest-but-aws-biggest.aspx
INFO:__main__:Getting metadata for https://awsinsider.net/articles/2018/11/01/azure-fastest-but-aws-biggest.aspx
 51%|█████     | 94/186 [01:37<02:43,  1.78s/it]INFO:__main__:Requesting https://www.bloomberg.com/news/articles/2018-11-13/google-may-have-to-get-used-to-third-place-in-the-cloud
INFO:__main__:Getting metadata for https://www.bloomberg.com/tosv2.html?vid=&uuid=fdf00540-3da3-11e9-b727-1fb3c3d8af17&url=L25ld3MvYXJ0aWNsZXMvMjAxOC0xMS0xMy9nb29nbGUtbWF5LWhhdmUtdG8tZ2V0LXVzZWQtdG8tdGhpcmQtcGxhY2UtaW4tdGhlLWNsb3Vk
 51%|█████     | 95/186 [01:38<02:06,  1.39s/it]INFO:__main__:Requesting https://www.geekwire.com/2018/state-cloud-amazon-web-services-bigger-four-major-competitors-combined/
INFO:__main__:Getting metadata for https://www.geekwire.com/2018/state-cloud-amazon-web-services-bigger-four-major-competitors-combined/
 52%|█████▏    | 96/186 [01:40<02:23,  1.60s/it]INFO:__main__:Requesting https://www.canalys.com/newsroom/cloud-infrastructure-spend-reaches-us%2420-billion-in-q2-2018-with-hybrid-it-approach-dominant
INFO:__main__:Getting metadata for https://www.canalys.com/newsroom/cloud-infrastructure-spend-reaches-us%2420-billion-in-q2-2018-with-hybrid-it-approach-dominant
 52%|█████▏    | 97/186 [01:43<02:56,  1.98s/it]INFO:__main__:Requesting https://www.srgresearch.com/articles/cloud-revenues-continue-grow-50-top-four-providers-tighten-grip-market
INFO:__main__:Getting metadata for https://www.srgresearch.com/articles/cloud-revenues-continue-grow-50-top-four-providers-tighten-grip-market
 53%|█████▎    | 98/186 [01:44<02:44,  1.87s/it]INFO:__main__:Requesting https://www.datacenterdynamics.com/news/google-cloud-head-diane-greene-step-down-be-succeeded-oracles-thomas-kurian/
INFO:__main__:Getting metadata for https://www.datacenterdynamics.com/news/google-cloud-head-diane-greene-step-down-be-succeeded-oracles-thomas-kurian/
 53%|█████▎    | 99/186 [01:45<02:00,  1.39s/it]INFO:__main__:Requesting https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0
INFO:__main__:Getting metadata for https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0
 54%|█████▍    | 100/186 [01:47<02:11,  1.53s/it]INFO:__main__:Requesting https://kubernetes.io/docs/concepts/cluster-administration/networking/
INFO:__main__:Getting metadata for https://kubernetes.io/docs/concepts/cluster-administration/networking/
 54%|█████▍    | 101/186 [01:48<02:11,  1.55s/it]INFO:__main__:Requesting https://penguindreams.org/blog/my-love-hate-relationship-with-docker-and-container-orchestration-systems/
INFO:__main__:Getting metadata for https://penguindreams.org/blog/my-love-hate-relationship-with-docker-and-container-orchestration-systems/
 55%|█████▍    | 102/186 [01:49<01:42,  1.22s/it]INFO:__main__:Requesting https://sourcemaking.com/antipatterns/design-by-committee
INFO:__main__:Getting metadata for https://sourcemaking.com/antipatterns/design-by-committee
 55%|█████▌    | 103/186 [01:49<01:19,  1.05it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Mirantis
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Mirantis
 56%|█████▌    | 104/186 [01:50<01:22,  1.00s/it]INFO:__main__:Requesting https://www.mirantis.com/
INFO:__main__:Getting metadata for https://www.mirantis.com
 56%|█████▋    | 105/186 [01:51<01:17,  1.05it/s]INFO:__main__:Requesting https://github.com/openstack/kolla
INFO:__main__:Getting metadata for https://github.com/openstack/kolla
 57%|█████▋    | 106/186 [01:52<01:14,  1.08it/s]INFO:__main__:Requesting https://www.sdxcentral.com/articles/news/att-5g-airship-plans-powered-by-mirantis/2019/02/
INFO:__main__:Getting metadata for https://www.sdxcentral.com/articles/news/att-5g-airship-plans-powered-by-mirantis/2019/02/
 58%|█████▊    | 107/186 [01:52<00:54,  1.46it/s]INFO:__main__:Requesting https://blogs.dxc.technology/2015/04/02/nebula-openstack-cloud-vendor-just-shut-down-with-no-notice/
ERROR:__main__:Could not reach https://blogs.dxc.technology/2015/04/02/nebula-openstack-cloud-vendor-just-shut-down-with-no-notice/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 58%|█████▊    | 108/186 [01:52<00:46,  1.66it/s]INFO:__main__:Requesting https://slate.com/technology/2017/08/the-19th-century-moral-panic-over-paper-technology.html
INFO:__main__:Getting metadata for https://slate.com/technology/2017/08/the-19th-century-moral-panic-over-paper-technology.html
 59%|█████▊    | 109/186 [01:53<00:37,  2.03it/s]INFO:__main__:Requesting https://www.insee.fr/fr/statistiques/graphique/1281410/graphique1.jpg
INFO:__main__:Getting metadata for https://www.insee.fr/fr/statistiques/graphique/1281410/graphique1.jpg
 59%|█████▉    | 110/186 [01:58<02:35,  2.05s/it]INFO:__main__:Requesting https://www.insee.fr/fr/statistiques/1281410
INFO:__main__:Getting metadata for https://www.insee.fr/fr/statistiques/1281410
 60%|█████▉    | 111/186 [02:03<03:31,  2.82s/it]INFO:__main__:Requesting https://www.bloomberg.com/news/articles/2019-03-01/one-of-wall-street-s-most-popular-trading-strategies-is-now-failing
INFO:__main__:Getting metadata for https://www.bloomberg.com/tosv2.html?vid=&uuid=0d1b88f0-3da4-11e9-967b-1597c639de51&url=L25ld3MvYXJ0aWNsZXMvMjAxOS0wMy0wMS9vbmUtb2Ytd2FsbC1zdHJlZXQtcy1tb3N0LXBvcHVsYXItdHJhZGluZy1zdHJhdGVnaWVzLWlzLW5vdy1mYWlsaW5n
 60%|██████    | 112/186 [02:03<02:36,  2.12s/it]INFO:__main__:Requesting https://qiao.github.io/PathFinding.js/visual/
INFO:__main__:Getting metadata for https://qiao.github.io/PathFinding.js/visual/
 61%|██████    | 113/186 [02:04<01:57,  1.61s/it]INFO:__main__:Requesting https://anvaka.github.io/ngraph.path.demo/
INFO:__main__:Getting metadata for https://anvaka.github.io/ngraph.path.demo/
 61%|██████▏   | 114/186 [02:04<01:24,  1.17s/it]INFO:__main__:Requesting https://github.com/anvaka/ngraph.path
INFO:__main__:Getting metadata for https://github.com/anvaka/ngraph.path
 62%|██████▏   | 115/186 [02:05<01:16,  1.08s/it]INFO:__main__:Requesting http://razorcode.net/articles/vehicle-path-planning.html
INFO:__main__:Getting metadata for http://razorcode.net/articles/vehicle-path-planning.html
 62%|██████▏   | 116/186 [02:08<01:53,  1.62s/it]INFO:__main__:Requesting https://weeklyrobotics.com/
INFO:__main__:Getting metadata for https://weeklyrobotics.com
 63%|██████▎   | 117/186 [02:08<01:22,  1.19s/it]INFO:__main__:Requesting https://www.redblobgames.com/pathfinding/a-star/introduction.html
INFO:__main__:Getting metadata for https://www.redblobgames.com/pathfinding/a-star/introduction.html
 63%|██████▎   | 118/186 [02:08<01:04,  1.05it/s]INFO:__main__:Requesting http://mikolalysenko.github.io/l1-path-finder/www/
INFO:__main__:Getting metadata for http://mikolalysenko.github.io/l1-path-finder/www/
 64%|██████▍   | 119/186 [02:09<00:51,  1.29it/s]INFO:__main__:Requesting https://github.com/qiao/PathFinding.js/blob/master/visual/index.html
INFO:__main__:Getting metadata for https://github.com/qiao/PathFinding.js/blob/master/visual/index.html
 65%|██████▍   | 120/186 [02:09<00:51,  1.28it/s]INFO:__main__:Requesting https://johncarlosbaez.wordpress.com/2019/03/02/negative-carbon-emissions/
ERROR:__main__:Could not reach https://johncarlosbaez.wordpress.com/2019/03/02/negative-carbon-emissions/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 65%|██████▌   | 121/186 [02:10<00:38,  1.71it/s]INFO:__main__:Requesting https://iopscience.iop.org/article/10.1088/1748-9326/aabf9b
ERROR:__main__:Could not reach https://iopscience.iop.org/article/10.1088/1748-9326/aabf9b
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='iopscience.iop.org', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='iopscience.iop.org', port=443): Read timed out. (read timeout=6)
 66%|██████▌   | 122/186 [02:16<02:28,  2.33s/it]INFO:__main__:Requesting https://iopscience.iop.org/article/10.1088/1748-9326/aabf9f
ERROR:__main__:Could not reach https://iopscience.iop.org/article/10.1088/1748-9326/aabf9f
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='iopscience.iop.org', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='iopscience.iop.org', port=443): Read timed out. (read timeout=6)
 66%|██████▌   | 123/186 [02:22<03:42,  3.53s/it]INFO:__main__:Requesting https://iopscience.iop.org/article/10.1088/1748-9326/aabff4
ERROR:__main__:Could not reach https://iopscience.iop.org/article/10.1088/1748-9326/aabff4
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='iopscience.iop.org', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='iopscience.iop.org', port=443): Read timed out. (read timeout=6)
 67%|██████▋   | 124/186 [02:29<04:31,  4.37s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Great_Oxygenation_Event
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Great_Oxygenation_Event
 67%|██████▋   | 125/186 [02:30<03:30,  3.44s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Biochar
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Biochar
 68%|██████▊   | 126/186 [02:31<02:54,  2.90s/it]INFO:__main__:Requesting https://www.latimes.com/science/sciencenow/la-sci-sn-more-efficient-photosynthesis-20191003-story.html
INFO:__main__:Getting metadata for https://www.latimes.com/science/sciencenow/la-sci-sn-more-efficient-photosynthesis-20191003-story.html
 68%|██████▊   | 127/186 [02:33<02:35,  2.63s/it]INFO:__main__:Requesting https://www.avclub.com/the-day-after-traumatized-a-generation-with-the-horrors-1798447330
INFO:__main__:Getting metadata for https://www.avclub.com/the-day-after-traumatized-a-generation-with-the-horrors-1798447330
 69%|██████▉   | 128/186 [02:34<01:59,  2.06s/it]INFO:__main__:Requesting https://www.nytimes.com/interactive/2018/08/01/magazine/climate-change-losing-earth.html
INFO:__main__:Getting metadata for https://www.nytimes.com/interactive/2018/08/01/magazine/climate-change-losing-earth.html
 69%|██████▉   | 129/186 [02:35<01:32,  1.62s/it]INFO:__main__:Requesting https://www.bloomberg.com/news/articles/2019-03-01/quadriga-has-6-cold-wallets-but-they-don-t-hold-any-crypto
INFO:__main__:Getting metadata for https://www.bloomberg.com/tosv2.html?vid=&uuid=202fb880-3da4-11e9-8cf2-47b83fabbeec&url=L25ld3MvYXJ0aWNsZXMvMjAxOS0wMy0wMS9xdWFkcmlnYS1oYXMtNi1jb2xkLXdhbGxldHMtYnV0LXRoZXktZG9uLXQtaG9sZC1hbnktY3J5cHRv
 70%|██████▉   | 130/186 [02:35<01:13,  1.31s/it]INFO:__main__:Requesting https://twitter.com/brian_armstrong/status/1098656491609849856
INFO:__main__:Getting metadata for https://twitter.com/brian_armstrong/status/1098656491609849856
 70%|███████   | 131/186 [02:36<01:07,  1.23s/it]INFO:__main__:Requesting https://outline.com/MS67gd
INFO:__main__:Getting metadata for https://outline.com/MS67gd
 71%|███████   | 132/186 [02:38<01:05,  1.21s/it]INFO:__main__:Requesting https://outline.com/TdWDgM
INFO:__main__:Getting metadata for https://outline.com/TdWDgM
 72%|███████▏  | 133/186 [02:39<01:09,  1.31s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Dysentery#Bacillary_dysentery
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Dysentery#Bacillary_dysentery
 72%|███████▏  | 134/186 [02:41<01:10,  1.36s/it]INFO:__main__:Requesting https://knowyourmeme.com/memes/you-have-died-of-dysentery
INFO:__main__:Getting metadata for https://knowyourmeme.com/memes/you-have-died-of-dysentery
 73%|███████▎  | 135/186 [02:41<00:56,  1.11s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1856159/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1856159/
 73%|███████▎  | 136/186 [02:42<00:56,  1.13s/it]INFO:__main__:Requesting https://www.newsbtc.com/2019/02/06/ceo-who-held-150m-in-crypto-died-in-a-region-known-for-having-a-fake-death-mafia/
INFO:__main__:Getting metadata for https://www.newsbtc.com/2019/02/06/ceo-who-held-150m-in-crypto-died-in-a-region-known-for-having-a-fake-death-mafia/
 74%|███████▎  | 137/186 [02:43<00:45,  1.09it/s]INFO:__main__:Requesting https://bitcoincharts.com/charts/krakenUSD#rg730ztgSza1gSMAzm1g10zm2g25zl
INFO:__main__:Getting metadata for https://bitcoincharts.com/charts/krakenUSD#rg730ztgSza1gSMAzm1g10zm2g25zl
 74%|███████▍  | 138/186 [02:49<02:00,  2.51s/it]INFO:__main__:Requesting https://www.coindesk.com/kraken-exchange-offers-100k-reward-for-missing-quadrigacx-crypto
INFO:__main__:Getting metadata for https://www.coindesk.com/kraken-exchange-offers-100k-reward-for-missing-quadrigacx-crypto
 75%|███████▍  | 139/186 [02:49<01:25,  1.82s/it]INFO:__main__:Requesting https://www.simplypsychology.org/cognitive-dissonance.html
INFO:__main__:Getting metadata for https://www.simplypsychology.org/cognitive-dissonance.html
 75%|███████▌  | 140/186 [02:54<02:09,  2.83s/it]INFO:__main__:Requesting https://www.reddit.com/r/BitcoinCA/comments/avzh7s/community_call_to_action_submit_your_verified?sort=confidence
INFO:__main__:Getting metadata for https://www.reddit.com/r/BitcoinCA/comments/avzh7s/community_call_to_action_submit_your_verified/?sort=confidence
 76%|███████▌  | 141/186 [02:55<01:42,  2.28s/it]INFO:__main__:Requesting https://www.reddit.com/r/BitcoinCA/comments/ar86lf/report_shows_quadrigacx_cold_wallets_actively?sort=confidence
INFO:__main__:Getting metadata for https://www.reddit.com/r/BitcoinCA/comments/ar86lf/report_shows_quadrigacx_cold_wallets_actively/?sort=confidence
 76%|███████▋  | 142/186 [02:57<01:30,  2.06s/it]INFO:__main__:Requesting https://blog.zerononcense.com/2019/02/28/quadrigacx-ethereum-storage-found/
ERROR:__main__:Could not reach https://blog.zerononcense.com/2019/02/28/quadrigacx-ethereum-storage-found/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 77%|███████▋  | 143/186 [02:57<01:04,  1.49s/it]INFO:__main__:Requesting https://github.com/olalonde/proof-of-liabilities
INFO:__main__:Getting metadata for https://github.com/olalonde/proof-of-liabilities
 77%|███████▋  | 144/186 [02:58<00:55,  1.32s/it]INFO:__main__:Requesting https://www.theguardian.com/lifeandstyle/2019/mar/02/apps-that-track-babies-and-give-data-to-tech-firms-parents
INFO:__main__:Getting metadata for https://www.theguardian.com/lifeandstyle/2019/mar/02/apps-that-track-babies-and-give-data-to-tech-firms-parents
 78%|███████▊  | 145/186 [02:58<00:41,  1.01s/it]INFO:__main__:Requesting https://www.cnn.com/2019/02/28/us/hoodwinker-sunfish-north-america-trnd/index.html
INFO:__main__:Getting metadata for https://www.cnn.com/2019/02/28/us/hoodwinker-sunfish-north-america-trnd/index.html
 78%|███████▊  | 146/186 [02:59<00:32,  1.24it/s]INFO:__main__:Requesting https://m.facebook.com/photo.php?fbid=1874957885867615&id=100000602658648&set=a.669037176459698
INFO:__main__:Getting metadata for https://m.facebook.com/photo.php?fbid=1874957885867615&id=100000602658648&set=a.669037176459698
 79%|███████▉  | 147/186 [02:59<00:26,  1.45it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=-nwA1hW0kUw
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=-nwA1hW0kUw
 80%|███████▉  | 148/186 [03:00<00:28,  1.35it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=A1WBilMrDIU
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=A1WBilMrDIU
 80%|████████  | 149/186 [03:01<00:30,  1.22it/s]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4403024/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4403024/
 81%|████████  | 150/186 [03:02<00:35,  1.02it/s]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5401880/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5401880/
 81%|████████  | 151/186 [03:05<00:48,  1.39s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Helminthic_therapy
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Helminthic_therapy
 82%|████████▏ | 152/186 [03:05<00:42,  1.25s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Ophiocordyceps_unilateralis
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Ophiocordyceps_unilateralis
 82%|████████▏ | 153/186 [03:07<00:40,  1.22s/it]INFO:__main__:Requesting https://www.merckmanuals.com/home/infections/parasitic-infections/trichinosis
INFO:__main__:Getting metadata for https://www.merckmanuals.com/home/infections/parasitic-infections/trichinosis
 83%|████████▎ | 154/186 [03:09<00:48,  1.51s/it]INFO:__main__:Requesting https://blog.ycombinator.com/startup-school-advisor-edition/
INFO:__main__:Getting metadata for https://blog.ycombinator.com/startup-school-advisor-edition/
 83%|████████▎ | 155/186 [03:09<00:36,  1.18s/it]INFO:__main__:Requesting https://editorconfig.org/
INFO:__main__:Getting metadata for https://editorconfig.org
 84%|████████▍ | 156/186 [03:10<00:29,  1.02it/s]INFO:__main__:Requesting https://www.gnu.org/software/bison/manual/html_node/Shift_002fReduce.html
INFO:__main__:Getting metadata for https://www.gnu.org/software/bison/manual/html_node/Shift_002fReduce.html
 84%|████████▍ | 157/186 [03:11<00:29,  1.01s/it]INFO:__main__:Requesting https://prettier.io/docs/en/options.html#tabs
INFO:__main__:Getting metadata for https://prettier.io/docs/en/options.html#tabs
 85%|████████▍ | 158/186 [03:11<00:23,  1.20it/s]INFO:__main__:Requesting https://github.com/prettier/eslint-plugin-prettier
INFO:__main__:Getting metadata for https://github.com/prettier/eslint-plugin-prettier
 85%|████████▌ | 159/186 [03:12<00:22,  1.18it/s]INFO:__main__:Requesting http://nickgravgaard.com/elastic-tabstops/
INFO:__main__:Getting metadata for http://nickgravgaard.com/elastic-tabstops/
 86%|████████▌ | 160/186 [03:14<00:28,  1.09s/it]INFO:__main__:Requesting http://blog.gngcreative.com/wp-content/uploads/2015/02/mi0fg2Q.jpg
INFO:__main__:Getting metadata for http://blog.gngcreative.com/wp-content/uploads/2015/02/mi0fg2Q.jpg
 87%|████████▋ | 161/186 [03:23<01:28,  3.53s/it]INFO:__main__:Requesting https://standardjs.com
INFO:__main__:Getting metadata for https://standardjs.com
 87%|████████▋ | 162/186 [03:25<01:12,  3.02s/it]INFO:__main__:Requesting https://metacpan.org/pod/perltidy
INFO:__main__:Getting metadata for https://metacpan.org/pod/perltidy
 88%|████████▊ | 163/186 [03:28<01:09,  3.04s/it]INFO:__main__:Requesting https://github.com/wincent/wincent/blob/db33e22c1/roles/dotfiles/files/.vim/plugin/autocmds.vim#L61
INFO:__main__:Getting metadata for https://github.com/wincent/wincent/blob/db33e22c1/roles/dotfiles/files/.vim/plugin/autocmds.vim#L61
 88%|████████▊ | 164/186 [03:29<00:51,  2.35s/it]INFO:__main__:Requesting https://github.com/wincent/wincent/blob/db33e22c1/roles/dotfiles/files/.vim/autoload/wincent/liferay.vim#L5-L26
INFO:__main__:Getting metadata for https://github.com/wincent/wincent/blob/db33e22c1/roles/dotfiles/files/.vim/autoload/wincent/liferay.vim#L5-L26
 89%|████████▊ | 165/186 [03:29<00:38,  1.84s/it]INFO:__main__:Requesting https://github.com/wincent/wincent/blob/db33e22c1/roles/dotfiles/files/.vim/autoload/wincent/git.vim#L1-L15
INFO:__main__:Getting metadata for https://github.com/wincent/wincent/blob/db33e22c1/roles/dotfiles/files/.vim/autoload/wincent/git.vim#L1-L15
 89%|████████▉ | 166/186 [03:30<00:29,  1.47s/it]INFO:__main__:Requesting https://github.com/wincent/wincent/blob/db33e22c1/roles/dotfiles/files/.vim/autoload/wincent/autocmds.vim#L182-L202
INFO:__main__:Getting metadata for https://github.com/wincent/wincent/blob/db33e22c1/roles/dotfiles/files/.vim/autoload/wincent/autocmds.vim#L182-L202
 90%|████████▉ | 167/186 [03:31<00:24,  1.27s/it]INFO:__main__:Requesting https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties
INFO:__main__:Getting metadata for https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties
 90%|█████████ | 168/186 [03:31<00:20,  1.11s/it]INFO:__main__:Requesting https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017
INFO:__main__:Getting metadata for https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017
 91%|█████████ | 169/186 [03:32<00:16,  1.05it/s]INFO:__main__:Requesting https://marketplace.visualstudio.com/items?itemName=siegebell.prettify-symbols-mode
INFO:__main__:Getting metadata for https://marketplace.visualstudio.com/items?itemName=siegebell.prettify-symbols-mode
 91%|█████████▏| 170/186 [03:33<00:13,  1.19it/s]INFO:__main__:Requesting https://www.jetbrains.com/mps/
INFO:__main__:Getting metadata for https://www.jetbrains.com/mps/
 92%|█████████▏| 171/186 [03:33<00:12,  1.24it/s]INFO:__main__:Requesting https://code.fb.com/security/homomorphic-hashing/
INFO:__main__:Getting metadata for https://code.fb.com/security/homomorphic-hashing/
 92%|█████████▏| 172/186 [03:34<00:09,  1.53it/s]INFO:__main__:Requesting http://c0de517e.blogspot.com/2019/03/what-i-learned-at-activision.html
INFO:__main__:Getting metadata for http://c0de517e.blogspot.com/2019/03/what-i-learned-at-activision.html
 93%|█████████▎| 173/186 [03:34<00:06,  1.89it/s]INFO:__main__:Requesting https://www.sciencedirect.com/science/article/abs/pii/S0376635716303424
INFO:__main__:Getting metadata for https://www.sciencedirect.com/science/article/abs/pii/S0376635716303424
 94%|█████████▎| 174/186 [03:35<00:09,  1.29it/s]INFO:__main__:Requesting https://daily.jstor.org/regulating-sex-work-in-medieval-europe/
INFO:__main__:Getting metadata for https://daily.jstor.org/regulating-sex-work-in-medieval-europe/
 94%|█████████▍| 175/186 [03:35<00:06,  1.65it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Drug_policy_of_the_Netherlands
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Drug_policy_of_the_Netherlands
 95%|█████████▍| 176/186 [03:36<00:06,  1.47it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Gropecunt_Lane
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Gropecunt_Lane
 95%|█████████▌| 177/186 [03:37<00:07,  1.23it/s]INFO:__main__:Requesting https://www.toolsofthetrade.net/trucks-equipment/jobsite-equipment/three-legged-saw-horse_o
 96%|█████████▌| 178/186 [03:38<00:05,  1.58it/s]INFO:__main__:Requesting https://www.newyorker.com/magazine/2017/01/23/constructed-worlds
INFO:__main__:Getting metadata for https://www.newyorker.com/magazine/2017/01/23/constructed-worlds
 96%|█████████▌| 179/186 [03:38<00:03,  1.82it/s]INFO:__main__:Requesting https://github.com/giann/croissant
INFO:__main__:Getting metadata for https://github.com/giann/croissant
 97%|█████████▋| 180/186 [03:39<00:03,  1.60it/s]INFO:__main__:Requesting http://fabiensanglard.net/rayTracing_back_of_business_card/index.php
 97%|█████████▋| 181/186 [03:39<00:02,  2.07it/s]INFO:__main__:Requesting https://www.dwitter.net/
INFO:__main__:Getting metadata for https://www.dwitter.net
 98%|█████████▊| 182/186 [03:44<00:07,  1.91s/it]INFO:__main__:Requesting https://mzucker.github.io/2016/08/03/miniray.html
INFO:__main__:Getting metadata for https://mzucker.github.io/2016/08/03/miniray.html
 98%|█████████▊| 183/186 [03:45<00:04,  1.45s/it]INFO:__main__:Requesting http://fabiensanglard.net/postcard_pathtracer/index.html
INFO:__main__:Requesting https://www.wsj.com/articles/facebook-ads-will-follow-you-even-when-your-privacy-settings-are-dialed-up-11551362400
INFO:__main__:Getting metadata for https://www.wsj.com/articles/facebook-ads-will-follow-you-even-when-your-privacy-settings-are-dialed-up-11551362400
 99%|█████████▉| 185/186 [03:46<00:01,  1.16s/it]INFO:__main__:Requesting https://arstechnica.com/tech-policy/2012/08/future-changes-to-facebook-privacy-settings-to-be-opt-in/
INFO:__main__:Getting metadata for https://arstechnica.com/tech-policy/2012/08/future-changes-to-facebook-privacy-settings-to-be-opt-in/
100%|██████████| 186/186 [03:46<00:00,  1.11it/s]
